### ISSUE TITLE
setLanguage warning

### ISSUE THREAD

**Issue by damek24** [PHPMailer/PHPMailer#1008]
in PHP 7.0/7.1, Yii Framework 2.0.11 with PHPMailer 5.2.23
this code produces PHP warning "Illegal offset type in isset or empty"
```
    public function setLanguage($langcode = 'en', $lang_path = '')
    {
        // Backwards compatibility for renamed language codes
        $renamed_langcodes = array(
            'br' => 'pt_br',
            'cz' => 'cs',
            'dk' => 'da',
            'no' => 'nb',
            'se' => 'sv',
        );

        if (isset($renamed_langcodes[$langcode])) {
            $langcode = $renamed_langcodes[$langcode];
        }
```

As I debugged $langcode  in this case is instanceof `yii\web\Cookie` 
solution I suggest (in my case works) is:
```
        if (!empty($langcode) && is_string($langcode) && isset($renamed_langcodes[$langcode])) {
            $langcode = $renamed_langcodes[$langcode];
        }
```

can you fix this in next version?

**Comment by Synchro** [comment]
This is a Yii bug, It shouldn't be passing in an instance of `yii\web\Cookie` when the function is expecting a string - here's the phpdoc description for the `$langcode` param:

    * @param string $langcode ISO 639-1 2-character language code (e.g. French is "fr")

If I make the change as you describe, all I'm doing is suppressing the error (which isn't "making it work") instead of fixing the source of the problem. Please report this to Yii.
