### ISSUE TITLE
Server answer splitting problems

### ISSUE THREAD

**Issue by MXStayeR** [PHPMailer/PHPMailer#1017]
In class.smtp.php file at method get_lines() ( line 1094 ) v 5.5.23 script can not break the loop when SMTP-server answers something like "334\r\n" or "250\n". It happens because script wants the 4th character be a  " ", 
` 
if ((isset($str[3]) and $str[3] == ' ')) {
                break;
}
`
but it may be any whitespace character, that matches with preg_match pattern ''/\s/".
You can see this design at ZendMail library:

  ` list($cmd, $more, $msg) = preg_split('/([\s-]+)/', $result, 2, PREG_SPLIT_DELIM_CAPTURE);`

**Comment by Synchro** [comment]
RFC5321 S4.2 says that servers 'should not' send bare codes. I've never seen them in the wild - do you have an example of such a misbehaving host? The relevant bit of the RFC says:

>in the general case, any text, no text at all (although senders SHOULD NOT send bare codes), MUST be acceptable.  The space (blank) following the reply code is considered part of the text.

In light of that, I've pushed a change that will accept bare codes.

It also says that the 4th char may only ever be a `-` or a literal space (the definition - all the way back from RFC821 - is `<SP> ::= the space character (ASCII code 32)`), not any other chars, so I'm not going to do that. It doesn't need to match line break chars because they are read using `fgets`, which strips them before it gets to that point. SwiftMailer may be using that to handle the line breaks, though it also means it would let through and mishandle invalid responses like `250\t \t\r\n`.

Using a regex for such trivial string processing is overkill and will give horrible performance, plus `list` is inherently unsafe (it will throw notices if `preg_split` returns < 3 items). The reason that PHPMailer uses string array access for these checks is that it's *really* fast - changing to this from `strlen` (which was already quite fast) resulted in a real-world performance boost of around 20% on a whole message, probably significantly more relative to a regex. Performance is important to me - my current config can send up to around 700,000 messages/hour (about 200/sec) using a single server.

**Comment by MXStayeR** [comment]
Thank's a lot, you was right. Server don't sends any bare codes. It simply sends status codes in 3 digits without any comments.

**Comment by Synchro** [comment]
Er, 3 digits without a comment is what a bare code is...
