### ISSUE TITLE
undefined method PHPMailer::isSMTP()

### ISSUE THREAD

**Issue by Graphap** [PHPMailer/PHPMailer#1039]
I'm working with PHPMailer and Codeigniter. I've written a function in Controller and PHPMailer works perfectly. I'm using `PHPMailerOAuth`.  After that I decided to use PHPmailer as library to access PHPMailer anywhere I want but I received this error :

> Call to undefined method PHPMailer::isSMTP()

I've asked in StackOverFlow but there is nothing to solve it. Path to this site : [http://stackoverflow.com/questions/43870847/unable-load-files-within-library-in-codeigniter](url)
It's library called PHPMailer.php :
```php
class PHPMailer {

public function singleMail($setFromTitle,$setToMail,$setToName,$setSubject,$setMessage)
{
    date_default_timezone_set('Etc/UTC');
    require 'vendor/phpmailer/phpmailer/PHPMailerAutoload.php';
    require 'vendor/autoload.php'; // I've uploaded vendor folder to my server and this path works fine in controller. I removed it but doesn't work!
    $mail = new PHPMailerOAuth;
    $mail->CharSet = 'UTF-8';
    $mail->isSMTP();
    $mail->SMTPDebug = 2;
    $mail->Debugoutput = 'html';
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 587;
    $mail->SMTPSecure = 'tls';
    $mail->SMTPAuth = true;
    $mail->AuthType = 'XOAUTH2';
    $mail->oauthUserEmail = "XXX@gmail.com";
    $mail->oauthClientId = "XXX";
    $mail->oauthClientSecret = "XXX";
    $mail->oauthRefreshToken = "XXX";
    $mail->setFrom('XXXy@zounkan.com', $setFromTitle);
    $mail->addAddress($setToMail, $setToName);
    $mail->Subject = $setSubject;
    $mail->msgHTML($setMessage);
    if (!$mail->send()) {
        echo "Mailer Error: " . $mail->ErrorInfo;
    } else {
        echo "Message sent!";
    }
}
```

And it's how I load this library within Controller's function :

`$this->load->library('PHPMailer');
$this->phpmailer->singleMail($setFromTitle,$setToMail,$setToName,$setSubject,$setMessage);`

**Comment by Synchro** [comment]
There's one simple, obvious thing that I missed in your SO question - look what you have called your class: `PHPMailer`. You effectively have a naming clash, which is why namespaces were introduced (and are supported in PHPMailer 6.0). Just call your class something other than PHPMailer and you should be fine.

Also as I observed in the SO Q: if you're using composer, you don't need to load PHPMailer's own autoloader, but why are you calling `vendor/autoload.php` from in here? This should be loaded way earlier by your framework's init/bootstrap function. By doing it here you're really undermining much of the point of using composer at all. Is PHPMailer really the only library you're loading with composer?

**Comment by Graphap** [comment]
That's the right answer which is never I have seen! I changed the class name and it works fine as well! Thank you!!!
