### ISSUE TITLE
SingleTo with SMTP transport.

### ISSUE THREAD

**Issue by maximmasiutin** [PHPMailer/PHPMailer#1042]
PHPMailer just silently ignores SingleTo with SMTP, sending duplicate messages. Although there is an information in the comments that SingleTo does only work with sendmail or mail transports, not with smtp, this is not very obvious to the users and very easy to miss. We should make a robust way to check the parameter consistency. For example, if SingleTo is true and the transport is smtp, the PHPMailer should trow an exception with the appropriate message or return an appropriate error.

**Comment by Synchro** [comment]
I think a better idea would be to remove the SingleTo functionality altogether. It's better to control this at a higher level - PHPMailer isn't a mailing list sender.

**Comment by maximmasiutin** [comment]
I have just spotted a potential problem - but you decide the rest :-) I don't think that removing the SingleTo  is a good idea, since it did exist for ages and many people are using it, so if you remove it, people will have to rewrite the code. Besides that, anyway, they will have to be somehow notified that the property have been removed. Otherwise, they will continue running the old code on the new class and they will anyway need some form of exception or error to be aware that it is no longer supported ;-)

**Comment by Synchro** [comment]
Sure - This is called a backward compatibility (BC) break, and we are about to have a big one with the release of PHPMailer 6.0 anyway. I won't remove it just yet, but I will mark the SingleTo functionality as deprecated, to be removed in 7.0. Use of the PHP `mail()` function needs to be discouraged because it's [extremely difficult to use safely](https://exploitbox.io/paper/Pwning-PHP-Mail-Function-For-Fun-And-RCE.html); SMTP is faster, safer, and gives more control and feedback.
