### ISSUE TITLE
Respect Content-Type header length

### ISSUE THREAD

**Issue by szepeviktor** [PHPMailer/PHPMailer#1052]
Hello!

I am using Mailjet which is a fine transactional email service.
They provide no mailboxes but having an API they provide a callback sending a JSON.

Would it be possible to recreate a DSN by PHPMailer as per https://tools.ietf.org/html/rfc3464?

My plan is a main message: `Content-Type: multipart/report; report-type=delivery-status`
with a text/plain and a message/delivery-status part.

**Comment by szepeviktor** [comment]
Seems to be workgin
```php
$mail->ContentType = 'multipart/report; report-type=delivery-status; boundary="=_mailjet_bounce_0"';
```

But here we have an extra long line:
```
Content-Type: multipart/report; report-type=delivery-status; boundary="=_mailjet_bounce_0"; charset=iso-8859-1
```

Please advise.

**Comment by szepeviktor** [comment]
Is there a function to wrap header lines?

**Comment by Synchro** [comment]
Thanks for posting. Yes there is, it's called `encodeHeader`, however, it was mainly focused on encoding rather than folding, though it does both for B and Q-encoded headers. The omission was that long lines that do not require B or Q encoding did not get folded - if you add a character that does require encoding (like `é`), you'll find it does wrap correctly.

I've fixed this in the 6.0 branch, see b25f93e, and also the related #818. Please give it a try and let me know your results.

**Comment by szepeviktor** [comment]
Thank you.
Do you think the Content-Type header should be encoded.
I've never seen such an email.

**Comment by Synchro** [comment]
That content-type is fine. The root problem is that PHPMailer doesn't support arbitrary MIME structures, which is what you really need here. You might be better off with Zend_Mail for that.

**Comment by szepeviktor** [comment]
Thank you very much!
