### ISSUE TITLE
unsubscribe link not working in gmail

### ISSUE THREAD

**Issue by bydbest** [PHPMailer/PHPMailer#1058]
i have added below code in my list but unsubscribe list is not appearing in gmail top. my dkim and spf records are verified correctly and gmail shows email from verified site.

$mail->AddCustomHeader("List-Unsubscribe: <mailto:arjun@something.com?subject=Unsubscribe>, <http://something.com/unsubscribe.php/".$urlid." \r\n");

**Comment by Synchro** [comment]
I suspect you asked the same question on Stack Overflow. Read the spec in [RFC2369](https://tools.ietf.org/html/rfc2369). It says that all URLs must be enclosed in `<>`, which your `mailto` is not. Also, why would you think that PHPMailer would be too dumb to deal with the line break after a header?

Try this instead:

```php
$mail->AddCustomHeader('List-Unsubscribe', "<mailto:arjun@something.com?subject=Unsubscribe>,<http://something.com/unsubscribe.php/".$urlid);
```

Mailto URLs are often not sent interactively, but automatically by host systems, so the URL you have there is probably not gong to work anyway, and you should look into [VERP](https://en.wikipedia.org/wiki/Variable_envelope_return_path)-style addressing in order to handle these without user action (this isn't VERP itself as these are not bounces, but the same principle applies).

Finally, client handling of unsubscribe links like this is very patchy; there is no guarantee that they will be presented any particular way, or at all.

**Comment by q2apro** [comment]
> The unsubscribe option is only shown for senders with a high reputation.

https://stackoverflow.com/q/28497332/1066234
