### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by abeer93** [PHPMailer/PHPMailer#1082]
please i want to use PHPMailer in custom library which i create and use in zend application .
i have a problem with require phpmailer .
if i make require phpmailer from my vendor && later someone use mylibrary the require  statment will throw error && it can't Force on user to require to give vendor path to make require for phpmailer.
why there no namespace ?

**Comment by Synchro** [comment]
Because PHPMailer 5.x is compatible with older PHP versions that don't support namespaces. You need to look at [the 6.0 branch](https://github.com/PHPMailer/PHPMailer/tree/6.0), which does use a namespace, and will be released soon. That said, you can `use` a class from the global namespace anyway, so there's no reason you can't make it work without it having its own namespace.
