### ISSUE TITLE
isShellSafe() is causing return path to no longer work

### ISSUE THREAD

**Issue by NicktheGeek** [PHPMailer/PHPMailer#1090]
I got a complaint from our support team last week that our customers are having deliverability errors. We narrowed this down to the return path no longer working correctly.

After a fair bit of debugging I found this ended up being a problem in the `isShellSafe` method.

When using a valid email address like `name@domain.com` the method returns false. I did some reading and it is expected that certain valid email addresses might return false because they are using some unusual ISO standards which allow += and other characters that might have shell meaning but I think it may be that the command is being too aggressive.

I tried several variations including explicitly adding quotes to the sender parameter but nothing could get past that check unless I change `or` to `and`.

I checked the output from each part of the check with this code:

```
$string   = 'name@domain.com';
$shellcmd = escapeshellcmd($string);
$shellarg = escapeshellarg($string);
echo '$shellcmd<pre><code>'; var_dump( $shellcmd ); echo '</code></pre>';
echo '$shellarg<pre><code>'; var_dump( $shellarg ); echo '</code></pre>'; exit; 
```

and received this output:

```
$shellcmd
NULL
$shellarg
string(17) "'name@domain.com'"
```

As you can see, `escapeshellcmd($string)` is returning NULL. I found this to be true for several valid email addresses I tried. 

Update

For reference, this is occurring with PHP 5.5.9-1ubuntu4.21

**Comment by Synchro** [comment]
Unfortunately this is a necessary measure. The reason it was added is because there are many RFC-compliant email addresses that are also functional attack strings (see CVE-2016-10045). The results of PHP's escaping can't really be trusted in the `mail()` function because locale behaviour is so unpredictable, and in many cases undefined. There is a simple workaround though - don't send using `mail()`, use SMTP to localhost instead. Since `mail()` requires a local mail server anyway, this imposes no additional config, and it's also faster, more efficient, and provides better feedback, and avoids the draconian measures inherent in `isShellSafe()`. If your server works with `mail()`, then it should also work with `$mail->isSMTP();`.

**Comment by NicktheGeek** [comment]
@Synchro did you read the issue I reported? This is failing with every email address I've tried. This isn't just some limited scope, fringe email addresses. It fails on `name@domain.com` (which isn't valid for actual use but is just an example instead of posting my real world addresses that I tried).

**Comment by Synchro** [comment]
I double checked - If I run the same code:

```
$shellcmd:
string(15) "name@domain.com"
$shellarg:
string(17) "'name@domain.com'"
```

This is with PHP 7.1.6 on OS X - this is the kind of problem that escaping presents - it's very dependent on config and just doesn't always work predictably, or safely.

**Comment by NicktheGeek** [comment]
@Synchro what about in PHP 5.5.9-1ubuntu4.21 (that is why I intentionally added the PHP version)

Unfortunately I've got to support a wide variety of PHP and cannot force users into SMTP or PHP7 on OSX

I suspect that this can be done in a way that works with simple email addresses.

**Comment by Synchro** [comment]
I'm not saying that everyone should update to PHP 7, just that different environments will produce different results, which is exactly what your'e seeing. To do this safely requires complete comprehension of the entire shell locale (which is probably why `escapeshellcmd`'s behaviour is different in your env), and it's simply impossible to do safely because we can't control (or even see) how `mail()` behaves internally. `isShellSafe` simply asks "is this string likely to need any escaping whatsoever according to PHP's own escaping functions?", and the slightest hint that it might is grounds for rejection. While it might be causing some inconvenience, it's simply not safe to follow any other path.

**Comment by Synchro** [comment]
For deeper info, I recommend reading [this](https://exploitbox.io/paper/Pwning-PHP-Mail-Function-For-Fun-And-RCE.html)
