### ISSUE TITLE
syntax error in phpMailer (use of $$)

### ISSUE THREAD

**Issue by moeHaydar** [PHPMailer/PHPMailer#1125]

**Comment by Synchro** [comment]
That's not a syntax error. It's a [variable variable](http://php.net/manual/en/language.variables.variable.php).

**Comment by moeHaydar** [comment]
but is it intended ?

**Comment by Synchro** [comment]
Very probably - I'm using them in a few places, but I can't tell if you don't give me a reference.

**Comment by moeHaydar** [comment]
I updated the comment directly to include the ref:
class.phpmailer.php line 3889

**Comment by moeHaydar** [comment]
Actually, just by reading the code i dont see where $current is used anyway and why it is needed.
Maybe I am missing something.

php is not my language so maybe I am missing something, so just ignore if there is a usage and ill look it up :)

**Comment by Synchro** [comment]
Yes, it's intentional. While it's not very pretty, `$current` is used in [several places in that function](https://github.com/PHPMailer/PHPMailer/blob/master/class.phpmailer.php#L3880). It's like pointer dereferencing in C - it's not `$current` itself we are interested in, it's the the thing that `$current` points at. When `$current == 'from_header'`, `$$current` is `$from_header`. It might help to think of it like `$($current)`.

**Comment by moeHaydar** [comment]
Yes I see, all makes sense now :), read the doc and understood its usage
