### ISSUE TITLE
How to automate the To email  and automate attached  file ?

### ISSUE THREAD

**Issue by alielkamel** [PHPMailer/PHPMailer#1129]
Hi All 
It is a tool that has helped me so much in my project but I have a question and I would like you to help me if you can, I am a beginner in Php, if I want to create a button that will appeal PHP script how to do?
And the second question which is the most difficult: if I display data in a notif.php page from a database (I will have lines with fields like email address, phone number, address and field ID that contains this person's ID and I put a button that generates a PDF that contains the information of that ID. Now I want to create this button in this notif.php page, and when I click this button then Email and send to this person by attaching the generated file so I will have automated the email import and attached the generated file that is stored in /var/files_id ( in one click )

**Comment by Benjamin0000** [comment]
I'm assuming that you know how to  make the functionalities  that will send the email and that will bring out the users information from the database base on the users id.   I think all you need to do is just to create a method or function for the functionalities and then call it well the button to send the email is being  clicked  like this      
![git](https://user-images.githubusercontent.com/30612040/29343100-dc7c414c-8226-11e7-875e-ebe99673d491.PNG)

**Comment by Synchro** [comment]
This is really too vague a question - this is a place to report bugs in PHPMailer, not learn PHP. Generally speaking, you need to break down your problem into small pieces, make each part work by itself, then join them together. Creating a button on a web page is one thing; getting it to submit to a PHP script is another; accepting and identifying that request is another; using the data in it is another; and so on. Trying to do everything in one go just makes it all confusing. When you ask questions, you need to extract the single, identifiable thing that you don't understand - but the process of doing that will often help you find what the problem is anyway.

**Comment by alielkamel** [comment]
okay i'm sorry for that .
