### ISSUE TITLE
NTLM AuthType not working anymore

### ISSUE THREAD

**Issue by OliverLeitner** [PHPMailer/PHPMailer#1145]
this worked for me before switching to latest phpmailer:
```

				$mail->AuthType = 'NTLM';
				$mail->Realm = $mailconfig['realm'];
```

now im getting the following error:

```
2017-09-06 07:05:24 SERVER -&gt; CLIENT: 220 MAIL2010.someserver.local Microsoft ESMTP MAIL Service ready at Wed, 6 Sep 2017 09:05:24 +0200<br>
2017-09-06 07:05:24 CLIENT -&gt; SERVER: EHLO localhost<br>
2017-09-06 07:05:24 SERVER -&gt; CLIENT: 250-MAIL2010.someserver.local Hello [192.168.169.114]250-SIZE250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-X-ANONYMOUSTLS250-AUTH NTLM250-X-EXPS GSSAPI NTLM250-8BITMIME250-BINARYMIME250-CHUNKING250-XEXCH50250-XRDST250 XSHADOW<br>
2017-09-06 07:05:24 CLIENT -&gt; SERVER: STARTTLS<br>
2017-09-06 07:05:24 SERVER -&gt; CLIENT: 220 2.0.0 SMTP server ready<br>
SMTP Error: Could not connect to SMTP host.<br>
2017-09-06 07:05:25 CLIENT -&gt; SERVER: QUIT<br>
2017-09-06 07:05:25 SERVER -&gt; CLIENT: <br>
2017-09-06 07:05:25 SMTP ERROR: QUIT command failed: <br>
SMTP Error: Could not connect to SMTP host.<br>
SMTP Error: Could not connect to SMTP host.
```

switching back to the older version of phpmailer (~6 weeks ago archived from git) it works

of course i have put the changes in the code to adapt to the new version.

use PHPMailer\PHPMailer\PHPMailer;
use ...Exception;
require 'path/to/phpmailer/vendor/autoload.php';
...
...

and i have looked into your wiki, and into the api documentation $AuthType exists, the NTLM option isnt mentoined though...

**Comment by Synchro** [comment]
Indeed it doesn't, as stated in the changelog for 6.0. `AuthType` is there, but `Realm` and `Workstation` were removed. The implementation that was there was broken anyway because it was missing some dependencies. Bundling third party scripts is a very bad practice, and [the script it used](https://www.phpclasses.org/package/1888-PHP-Single-API-for-standard-authentication-mechanisms.html) has not been updated since 2005.

If you need NTLM, I'd suggest you reimplement it in a subclass using a more up to date library - [there are several on packagist](https://packagist.org/search/?q=ntlm).

**Comment by OliverLeitner** [comment]
first of all: thank you for the information.

secondly: sadly non of the things on the list youve linked is that fresh anymore, seems ntlm auth isnt getting much love... or could it be that the authentification is a few lines that kinda dont have that much around them that the security risks of not having it patched in a long time dont hurt so much?

anyways, i respect that you dont want to do ntlm handshakes and ignore ms exchange in intranet setups.

**Comment by Synchro** [comment]
Well at least they have had updates in the last year or so, vs the 12 years of the old phpclasses library! It's also true that it's probably not that complex - but there are likely bugs/changes in PHP itself over that kind of time frame that probably need taking into account. When I tried testing the old PHPMailer version I found that it didn't work anyway because it was missing a dependency - that single class file was just not sufficient for doing NTLM - it needed some other classes from the same project. That was also a key reason for removing it, on top of the overall "bundling is bad" policy.
