### ISSUE TITLE
Variable by reference

### ISSUE THREAD

**Issue by romseb** [PHPMailer/PHPMailer#1157]
Hi.

I have been using php mailer 5.2.15 with php 5.2.x. has been worked correctly.
I had to upgrade php to 5.3. 
After upgrade:
I am getting error while running  phpmailer 5.2.25 under php 5.3. Error message is: 

 Only variables can be passed by reference in /server/skrypty-php/class.phpmailer.php on line 1192

And line number 1192 is:
idn_to_ascii($domain, 0, INTL_IDNA_VARIANT_UTS46) : in class.phpmailer.php

This line is a part of if statement.

What shouald I do to make this version of phpmailer working? I am NOT ABLE to upgrade to php 5.5 and use phpmailer 6 respectively. It is impossible at the moment. I must keep php 5.3
 
Thanks in advance

romseb

**Comment by peter279k** [comment]
Hi @romseb, I think this is the PHP version problem.
According to the [function](http://php.net/manual/en/function.idn-to-ascii.php) manual, the ```UTS#46``` has been added since PHP 5.4.You can see the changelog to get more details.
However, you use the PHP 5.3.
I think the current way is to upgrade your PHP version to 5.4.

Thanks.

**Comment by peter279k** [comment]
BTW, I also found that the PHPMailer 5.2 is not tested completely under the Travis-CI.
It usually presents the building [error](https://travis-ci.org/PHPMailer/PHPMailer/builds/269151885) during testing PHPMailer 5.2 with PHP 5.2.

**Comment by Synchro** [comment]
If you're running a site on anything less than PHP 5.6, upgrading should be your absolute top priority. PHP 5.3 has not received security patches for over 3 years, and as a result, **your site is vulnerable to attack and may be compromised**. Small issues like this should be the least of your concerns...

The build error is because Travis-CI no longer supports PHP 5.2 or 5.3, so I've removed 5.3 from the test suite, and now it's building with no errors.

The code checks that the `INTL_IDNA_VARIANT_UTS46` constant is defined before using it, specifically to provide compatibility with older PHP versions.

Now, as to the error you're seeing, that's a bit of a mystery. The docs on `idn_to_ascii` show the method signature is:

    string idn_to_ascii ( string $domain [, int $options = 0 [, int $variant = INTL_IDNA_VARIANT_2003 [, array &$idna_info ]]] )

The only parameter passed by reference is the fourth, `$idna_info` – but we are not providing that parameter at all, and the third, `$variant`, does not exist in PHP 5.3, so will be ignored. That leaves `$domain` and `$options`, neither of which are marked as by-reference. The only one of those that is not passed as a variable is `$options`. Can you try changing this:

                $domain = mb_convert_encoding($domain, 'UTF-8', $this->CharSet);
                if (($punycode = defined('INTL_IDNA_VARIANT_UTS46') ?
                    idn_to_ascii($domain, 0, INTL_IDNA_VARIANT_UTS46) :
                    idn_to_ascii($domain)) !== false) {

to

                $domain = mb_convert_encoding($domain, 'UTF-8', $this->CharSet);
                $options = 0;
                if (($punycode = defined('INTL_IDNA_VARIANT_UTS46') ?
                    idn_to_ascii($domain, $options, INTL_IDNA_VARIANT_UTS46) :
                    idn_to_ascii($domain)) !== false) {

If that fixes it for you (I don't have any means of testing on 5.3), please let me know and I'll push that change.

**Comment by peter279k** [comment]
I think the @romseb cannot upgrade the PHP version so changing the source code is necessary.

**Comment by Synchro** [comment]
That's what I suggested?

**Comment by peter279k** [comment]
Yes.If possible, I think he can try to use the PHP 5.4.
Perhaps it will be fine.

**Comment by romseb** [comment]
Hi

I am running phpmailer 6 on php 5.6 now. And I am obtaining the following
message

 Class 'PHPMailer' not found in /server/skrypty-php/test_poczty2.php on
line 4

Where line 2,3,4 in test_poczty2.php is

require_once('PHPMailer.php');    //dodanie klasy phpmailer
 require_once('SMTP.php');    //dodanie klasy smtp
 $mail = new PHPMailer();

is something else required?

Thanks in advance

 Romek


2017-09-14 9:43 GMT+02:00 Marcus Bointon <notifications@github.com>:

**Comment by peter279k** [comment]
Hi @romseb, did you install the phpmailer 6 via Composer?I think this is the general PHP error.
You have to consider this [example](https://github.com/PHPMailer/PHPMailer/tree/v6.0.0#a-simple-example).

Thanks.

**Comment by Synchro** [comment]
I'd suggest getting composer working, but loading classes manually is also documented in the readme - the class files now live in `src/` so you may just need to say:

    require_once('src/PHPMailer.php');
    require_once('src/SMTP.php');

or prefix it with wherever you're keeping it.

**Comment by peter279k** [comment]
I think the @romseb does not add the namespace after including the PHPMailer library files.
Try to add the ```use PHPMailer\PHPMailer\PHPMailer;``` and ```use PHPMailer\PHPMailer\Exception;``` before creating an instance of the PHPMailer class.

**Comment by peter279k** [comment]
BTW, I think changing the @Synchro's manual approach to
```
require_once __DIR__.'/src/PHPMailer.php';
require_once __DIR__.'/src/SMTP.php';
```
.And this approach is proper.

**Comment by Synchro** [comment]
That would only be necessary if the CWD was not in the same place as the script, which is extremely unlikely for a simple script like this.
