### ISSUE TITLE
mail doesnt go if i keep $mail->isSMTP();

### ISSUE THREAD

**Issue by avchandan** [PHPMailer/PHPMailer#1180]
when i comment isSMTP(); and send mail. mail goes sucessfully but after 5 sucessful mails it stops sendin mail for few minutes and than it accepts the new requests. if keep isSMTP enabled it says that smtp.gmail.com is unreachable

require 'phpmailer/PHPMailerAutoload.php';
            //Create a new PHPMailer instance
            $mail = new PHPMailer;
            //$mail->isSMTP();
            $mail->SMTPDebug = 2;
            //Ask for HTML-friendly debug output
            $mail->Debugoutput = 'html';
            //Set the hostname of the mail server
            $mail->Host = 'smtp.gmail.com';
            $mail->Port = 587;
            $mail->SMTPSecure = 'tls';
            $mail->SMTPAuth = true;
            $mail->Username = "Gusername";
            $mail->Password = "Gpassword";
            $mail->IsHTML(true);
            $mail->setFrom('Gusername', 'myname');
            $mail->addAddress('xxx@gmail.com', 'Chandan');
            $mail->Subject = 'test subject';
            $msg=" Chandan ";
            $mail->Body = $msg;
            if (!$mail->send()) {
                echo "Mailer Error: " . $mail->ErrorInfo;
            } else {
                echo "<script>alert('Check your mail')</script>";
            }

**Comment by Synchro** [comment]
This is nothing to do with PHPMailer. When you comment out isSMTP, it defaults to the mail() function, which submits to a local mail server, so this limit is being imposed by your mail server, which sounds like it has some kind of rate limiting. I suggest you look in your mail server's logs. You could try using isSMTP to localhost and see if it acts any differently.

Not being able to reach gmail's server is probably because your ISP blocks outbound SMTP, which is common. They probably provide their own mail server for you to use instead - refer to their documentation.
