### ISSUE TITLE
Invalid email address, but it isn't

### ISSUE THREAD

**Issue by miachm** [PHPMailer/PHPMailer#1211]
I have an email account in my pc whose username is: "miguel@localhost". This account works great and i can send emails using thunderbird.

But when i tried to do it in PHPMailer i have an exception by "invalid address":

```
$mail = new PHPMailer(true); 
$mail->setFrom('miguel@localhost', 'whatever');
// more code...
```
If i put "dot com", it works propely

```
$mail = new PHPMailer(true); 
$mail->setFrom('miguel@localhost.com', 'whatever');
// more code...
```
But obviously, this is not the adress which i want.

**Comment by Synchro** [comment]
That's because `localhost` is not a publicly routable hostname, plus "dotless" domains are also banned by ICANN. That said, you can easily disable validation by injecting your own validator:

```php
PHPMailer::$validator = function($addr) {
    return true;
};
```

Even if you do this, there's no guarantee that your mail relay will accept the message, for the same reason.
