### ISSUE TITLE
setFrom didn't work as expected

### ISSUE THREAD

**Issue by sagarvd01** [PHPMailer/PHPMailer#1214]
Please check these things before submitting your issue:

- [x ] Make sure you're using the latest version of PHPMailer
- [x ] Check that your problem is not dealt with in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting), especially if you're having problems connecting to Gmail or GoDaddy
- [x ] Include sufficient code to reproduce your problem
- [ ] If you're having an SMTP issue, include the debug output generated with `SMTPDebug = 2` set
- [ ] If you have a question about how to use PHPMailer (rather than reporting a bug in it), tag a question on Stack Overflow with `phpmailer`, but [**search first**](http://stackoverflow.com/questions/tagged/phpmailer)!

# Problem description

The expected working of function `setFrom` is set a header indicate the from field. But in the received mail, it shows the from address as the authenticated gmail address.

# Code to reproduce

The example you've given in the readme

# Pictorial Representation

![image](https://user-images.githubusercontent.com/15938422/32122718-f5ca1fd4-bb7e-11e7-9ab9-dcacb05bf293.png)

**Comment by fbonzon** [comment]
This is expected behavior, there is nothing wrong in PHPMailer itself.

The rewriting of the From address is done by Gmail for security reason (fight SPAM, phishing, etc.), not by PHPMailer. Gmail doesn't allow random From addresses.

To fix your problem, do one of:
- Use another From address than from@example.com, a real address that you own. If this is not the same address that the Gmail account you connect with for sending the e-mail, also add that address in your Gmail account according to instructions on https://support.google.com/mail/answer/22370?hl=en
- Use another SMTP server than Gmail, one that does not rewrite From addresses.
