### ISSUE TITLE
no show error

### ISSUE THREAD

**Issue by gorge2004** [PHPMailer/PHPMailer#1230]
excuse , i need their help . would like the errors will not appears the users:
it is my code 👍 
```php
$mail = new PHPMailer();
				$mail->SMTPDebug = false;
				$mail->do_debug = 0;
				try {
						$mail->IsSMTP();                                      // set mailer to use SMTP
						$mail->SMTPSecure = 'tls';
						$mail->Host = 'smtp.gmail.com';
						$mail->Port = 587;
						  // specify main and backup server
						$mail->SMTPAuth = true;     // turn on SMTP authentication
						$mail->Username = "***************@gmail.com";  // SMTP username
						$mail->Password = "***********"; // SMTP password
						$mail->From = "*******@gmail.com";
						$mail->FromName = "********";
						$mail->AddAddress($correo , "*****");
						$mail->Subject = $asunto;
						$mail->Body    = $txt;  
						$mail->AltBody = $txtAlt;
						$mail->Send();
				} catch (phpmailerException $e) {
				  //echo $e->errorMessage(); //Pretty error messages from PHPMailer
				} catch (Exception $e) {
				  //echo $e->getMessage(); //Boring error messages from anything else!
				}
```

**Comment by Synchro** [comment]
This code does not display error messages. You have turned off debug output, are catching exceptions, and are not echoing anything.

**Comment by gorge2004** [comment]
For this reason i do the new issue . I test my views and the smtpError and another appear and the user can read it

**Comment by Synchro** [comment]
Please post some example output.

**Comment by gorge2004** [comment]
example sometimes print  : 

> SMTP Error: Could not connect to SMTP host.

> Invalid address: 

but i want that it doesnt print because when no send i save the information and dont want to show it to users

**Comment by gusbemacbe** [comment]
Syncro, he means he wants to see the errors only for himself and but not for the users. 

Syncro, il dit qu'il veut voir les fautes seulement pour lui-même, mais pas pour les utilisateurs.

**Comment by Synchro** [comment]
If you want PHPMailer to throw exceptions, pass `true` to the constructor:

    $mail = new PHPMailer(true);

If a send is successful, `send()` will return `true`. If it returns false, you know that there is a problem. You can get information about any error by looking at `$mail->ErrorInfo`, or in the message attached to an exception, so either of:

```php
if ($mail->send()) {
    //all ok
} else {
    $error_message = $mail->ErrorInfo;
}
```
```php
try {
    ...
    $mail->send();
} catch (Exception $e) {
    $error_message = $e->getMessage();
}
```

Note that **all** of the examples provided with PHPMailer show how to do this.

If you want more detail, for example if you want to capture the whole SMTP conversation, look at the `Debugoutput` property - inject a closure to retain the debug output and store it somewhere instead of displaying it.
