### ISSUE TITLE
Official on-line Documentation

### ISSUE THREAD

**Issue by peter279k** [PHPMailer/PHPMailer#1238]
As title, I found that this repo has the ```gh-pages``` branch.
But it's not available now.
I think we can publish the documentations to be the static sites and I also want to contribute some sample in ```examples``` folder.
How can I contribute this? Perhaps I can be responsible for this.

Thanks.

**Comment by Synchro** [comment]
I'm not sure what you mean - The gh-pages branch _is_ used and is published as a static site [here](http://phpmailer.github.io/PHPMailer/), as linked from the readme. The content is generated directly from the source code using PHPDocumentor. It would be very useful to update that automatically on every push rather than relying on manual updates - is that something you could look at?

With the release of 6.0 I was keen to reduce the number of examples, as there is a lot of duplication and overlap in the examples, and historically there have been many complaints about having too many files (though also of course, when I reduced the number of files, we had people complaining about that too 🙄). Also, the more examples you have, the more there is to keep up to date. What new examples were you proposing?

**Comment by peter279k** [comment]
Ok, I mean the documentation is like [this](https://irazasyed.github.io/telegram-bot-sdk/).
But I see it has the wiki in this repository.
I can provide the example is about connecting the third-party SMTP server.
For example, the third-party services is like [Mailgun](https://www.mailgun.com/) and [mailjet](https://www.mailjet.com/).

Thanks.

**Comment by Synchro** [comment]
That documentation is basically what's in the PHPMailer readme, just spread over more pages. [The API documentation](https://irazasyed.github.io/telegram-bot-sdk/api/v2.0.0/) they have is more or less identical to PHPMailer's - it just uses a different generator - I don't particularly like how the phpdoc generator pages look, but it does the job. There are probably better templates it could use.

I don't see much point in adding entire example files when the only real difference between them is what goes in the `Host` property, which is essentially what using any 3rd-party mail server involves. That said, I can see a good use for a wiki page that collects connection info on such providers. I don't think things like that should be in the code repo itself as it's just clutter that's hard to maintain, which is what I've been trying to get away from. It's also easier for others to contribute/update on the wiki as it doesn't require the whole fork/push/PR/merge procedure that's difficult for newcomers / non-techies.

**Comment by peter279k** [comment]
Hi @Synchro, thank you for your reply.
I know that. If I want to add the third-party tutorial on the wiki, how can I contribute them?
Just edit page on this [tutorial](https://github.com/PHPMailer/PHPMailer/wiki/Tutorial)?

Thanks.

**Comment by Synchro** [comment]
Yes, the wiki editing is completely open. You can create new articles, edit existing ones as you like. I'd recommend putting connection details in a new one rather than adding to an existing one, and cross-reference it from the tutorial.
