### ISSUE TITLE
UPGRADING.md out of sync

### ISSUE THREAD

**Issue by risototh** [PHPMailer/PHPMailer#1242]
I think, that at least this (below) part of the UPGRADING.md doc is not in sync with the code.

- PHPMailer:$LE removed
- PHPMailer::CRLF line ending constant renamed to PHPMailer::LE, defaults to "\r\n", used everywhere
- All uses of PHPMailer::$LE property converted to use static:LE constant for consistency and ease of overriding

**The PHPMailer:$LE is still in current codebase. 
There is no PHPMailer::LE constant, but the PHPMailer::CRLF is already missing. 
And the whole code still uses self::$LE property, not the self::LE constant.**

Can you please adjust these issues? I used the PHPMailer::CRLF in my extension, so i need some "replacement" and protected property $LE is not a way, as i'm not extending the class.

Thanks.

**Comment by Synchro** [comment]
I've updated the doc. What it said was true at one point before 6.0 was released - it wasn't clear at the time that mail() on some OSs breaks if you use CRLF breaks. The CRLF constant is gone (because there is no longer any need for it), but you can get the current break string with `getLE()`. The line break format is manipulated automatically at `send()` time, so setting it beforehand is likely to not work as you expect. I don't know why your'e using it, but generally line breaks within message bodies are normalised to the sending format before use. This avoids problems with mixed line breaks which were a persistent problem in 5.2; 6.0 is far more consistent.

**Comment by risototh** [comment]
Ok, thanks, i will use the `getLE()`, i overlooked this method. 

While i'm using it? It's a special filter that switches all data-uri and external images into embedded attachments and also manipulates Body and AltBody...

**Comment by Synchro** [comment]
Similar to what `msgHTML()` does?
