### ISSUE TITLE
Quick question about spam

### ISSUE THREAD

**Issue by pwpx2** [PHPMailer/PHPMailer#1244]
All e-mails are going into spam on google. Any solution for this?
In the domain dns i have valid spf, dkim and dmarc keys. In the config file i only set the e-mail address from where the e-mail is sent.
Should this affect anything if the other variables aren't sent? Using the 'mail' method.

**Comment by jd440** [comment]
spf, dkim and dmarc keys is good things but not enough.

You can register to  postmaster.google.com that could help to determine you problem.
But is oftenly problem of domain/ip reputation… inbox rates is a large topic.
Bu you can share header of one of your newsletter on the forum to check!!

**Comment by Synchro** [comment]
You may find there is additional info in your received message headers in gmail. Select the "show original" option to see the raw message. You're doing the right thing with DKIP & SPF, but beyond that, gmail's inbox policy is wildly inconsistent and unpredictable - I get spam in my inbox, messages from relatives in spam. You may be able to get spam feedback by setting List-Unsubscribe headers containing a `mailto` URL, if you're sending to lists. I'd also recommend using `isSMTP` rather than going via mail(). It can save a hop and it is faster and safer.

**Comment by pwpx2** [comment]
Ok, thank you for the info.

**Comment by jd440** [comment]
@Synchro could you devellop 

>  You may be able to get spam feedback by setting List-Unsubscribe headers containing a mailto URL,

By setting List-Unsubscribe headers containing a mailto, you will just receive email when receipe will click on gmails' action button "unsubscribe" but not any feedback about spam?

**Comment by Synchro** [comment]
Gmail has a requirement that you have a mailto list-unsubscribe header before they will send you spam notifications. The header itself doesn't do it, it's just one of gmail's conditions.

**Comment by jd440** [comment]
Ok. Thanks
but how will they send you notification of spam? by postmaster tools?

**Comment by Synchro** [comment]
Read the docs on [gmail's feedback loop](https://support.google.com/mail/answer/6254652?hl=en)
