### ISSUE TITLE
Sender field in mail header

### ISSUE THREAD

**Issue by adrium** [PHPMailer/PHPMailer#1250]
# Problem description

The behaviour of `PHPMailer::Sender` does not work as expected and the `Sender` field of a message can not be set.

# Code to reproduce

Set `PHPMailer::Sender` and send the message. The `Sender` header is not included in the message.

# Notes

I think the comment closing #1249 is not quiet correct.
Since I am not allowed to reopen, I need to open this issue...

Please allow me to elaborate on the statements by @Synchro:

> The Sender property is used to set the SMTP-level envelope sender -
> the address that is used in a MAIL FROM SMTP command.

That may be true for the PHPMailer implementation, but it is not what the `Sender` header is intended for.

From [RFC 5322](https://tools.ietf.org/html/rfc5322):

> The "Sender:" field specifies the
> mailbox of the agent responsible for the actual transmission of the
> message.  For example, if a secretary were to send a message for
> another person, the mailbox of the secretary would appear in the
> "Sender:" field and the mailbox of the actual author would appear in
> the "From:" field.

The server that receives a `MAIL FROM` command
will put the address in a `Return-Path`.

From [RFC 5321](https://tools.ietf.org/html/rfc5321):

> The return-path line preserves the information in the <reverse-
> path> from the MAIL command.

The `MAIL FROM` and `RCPT TO` commands are called *envelope commands* in RFC 5321.

I think the following statement is plain wrong (or please link to a reference supporting the claim):

> It should never be put in a header

The following statement is wrong as well:

> though it's very common for it to be the same value as what is in the "From" header

From [RFC 5322](https://tools.ietf.org/html/rfc5322):

> If the originator of the message can be indicated
> by a single mailbox and the author [`From`] and transmitter [`Sender`] are identical, the
> "Sender:" field SHOULD NOT be used.  Otherwise, both fields SHOULD
> appear.

I agree to the following:

> it's also common for it to be entirely different (e.g for VERP addressing).
> The envelope sender is added to a message in the form of a Return-Path header by the receiver,
> so again, this is not something you should add as a sender

**Comment by adrium** [comment]
Oh sorry, I misinterpreted the statement concerning the return-path... Sure, it should not be put in a header and is common to be the same as the ffrom address.

Nevertheless, the sender field should be allowed to be set.

**Comment by Synchro** [comment]
> The MAIL FROM and RCPT TO commands are called envelope commands in RFC 5321.

Yes, that's what I said; The `Sender` property in PHPMailer is used to set the address used in the `MAIL FROM` command. It should not be used to set a Sender *header* within a message as that has an entirely different meaning and purpose.

You're right on section 3.6.2 - you can have a sender header, though it has no functional purpose (it's informational only) - but there's nothing stopping you setting it as a custom header.

**Comment by adrium** [comment]
Thanks for your reply. I haven't noticed the method.

> The `Sender` property in PHPMailer is used to set the address used in the `MAIL FROM` command

The naming is quite a bit misleading when there is a public property of the same name.

> you can have a sender header, though it has no functional purpose.

Well, our software sends a lot of mails to users with a lot of different hosts. Sometimes we even end on blacklists. It is important that we carefully set the necessary headers. And though `Sender` has no functional purpose, it has a semantic meaning. The headers `From` and `Sender` are perfectly suited, since the mails are often triggered by a person, but sent by our mail server.

I assume that mail servers check the *Originator Fields* of incoming mails for credibility. Therefore, `Sender` plays a crucial role and it is misleading that it has to be set by a method called `addCustomHeader`. The name is more associated with `X-Something` headers.

Also, how can I ensure correct encoding of the `name-addr` and `angle-addr` parts of the `mailbox`?

Hence, to get the intended result, both lines are necessary:

```php
$phpmailer->Sender = 'noreply@example.com';
$phpmailer->addCustomHeader('Sender', 'ACME <noreply@example.com>');
```

Because of the description above, `PHPMailer::Sender` shoud set **both,** the `Sender` and the envelope sender. And it should be possible, to set a `mailbox` (the ABNF rule name). This would not break BC, although there is a new header (iff it does differ from `From`).

There should be another property or method to also override the envelope sender.

**Comment by Synchro** [comment]
No, it should absolutely not set a sender header by default, especially not from the envelope sender. You are getting their purposes confused. The `Sender` property in PHPMailer sets the SMTP envelope sender, nothing else. A sender *message header* is a completely different, independent, unrelated thing, used for entirely different purposes, both technically and semantically - for example it would be pointless to put a VERP address in a sender header (what you suggested), and very likely wrong to use a semantic sender header value as an envelope sender. The sender header has nothing to do with saying that it was sent by your server - that's what the envelope sender is for. You *could* set it to the same value, but it won't actually do anything.

The ambiguous naming of the `Sender` property may be unfortunate, however, it was chosen for that purpose 16 years ago so it's not going to be subject to an arbitrary BC break when millions of sites don't use it as you describe.

You're right in that adding it as a custom header offers no validation - though you could make use of PHPMailer's header building functions to do that - however, I don't know how much value it has anyway - I did a quick test and a sender header is not displayed in gmail, Apple Mail (macOS or iOS) or Outlook web client (even with extended headers shown) - it apparently works in desktop Outlook, but I can't test that. I have seen gmail and Outlook displaying an "on behalf of" or "via" message, however, that's due to misconfigured domain auth, not a sender header. Envelope sender settings OTOH work fine everywhere - SMTP wouldn't work properly otherwise.

**Comment by adrium** [comment]
Thanks for clearing up some things. I did not know about VERP addressing. It seems my confusion mainly originated from the ambiguous naming of the Sender property. 🙈 Thanks for your time to reply!

Of course, changing the semantics or the name of the Sender property is not a good idea. However, maybe a hint in the documentation would be helpful for novice users of the library...

I implemented mail sending from our server as described above. Let's see, if the recipient's servers accept the mails.

This issue is closed for me.
