### ISSUE TITLE
Sending mail as Plaintext allways sets ContentType as "multipart/alternative"

### ISSUE THREAD

**Issue by larsmw** [PHPMailer/PHPMailer#1274]
When making a subclass of PHPMailer it replaces ContentType with "multipart/alternative" when setting it to "text/plain"
This results in outlook displaying the mail as html and skips newlines.

**Comment by Synchro** [comment]
No, you're doing it wrong. You should have looked at how `alternativeExists()` works along with the `ContentType` property (which defaults to `text/plain`). If you want to send plain text email, just do this:

    $mail->Body = 'plain text body';

You don't need to call `isHTML` because it defaults to plain-text; I suspect you're setting `AltBody`, which will cause it to switch to a multipart/alternative structure.

**Comment by larsmw** [comment]
Thanks, I will try that again.
