### ISSUE TITLE
"Could not instantiate mail function" is not a helpful error message

### ISSUE THREAD

**Issue by JonasT** [PHPMailer/PHPMailer#1288]
# Problem description

"Could not instantiate mail function" is not a helpful error message. It seems to be a catch all for many different conditions (invalid parameters like not a valid mail address, problems locating sendmail, no permission to run sendmail, ...). sendmail is installed, so this error message tells me absolutely *nothing* except that some random thing is wrong. This is extremely frustrating. Therefore, please find a way to provide a better error message.

# Code to reproduce

use php mailer example on a system e.g. without sendmail

# Debug output

**Comment by Synchro** [comment]
I can't tell. The only thing I have to go on is [the boolean returned by the `mail()` function](http://php.net/manual/en/function.mail.php). PHPMailer isn't (and shouldn't be) responsible for your entire PHP and OS configuration; it's just a small component. That said, you might like to put some effort into the diagnostic utility idea in #612; PRs welcome.

I strongly recommend (as do the docs) not using `mail()` anyway since [it's impossible to use securely](https://exploitbox.io/paper/Pwning-PHP-Mail-Function-For-Fun-And-RCE.html), and it's also slower and provides less feedback (as you're finding) than SMTP to localhost.
