### ISSUE TITLE
Possible Issue with Doing a 7-bit Downgrade?

### ISSUE THREAD

**Issue by gtilflm** [PHPMailer/PHPMailer#1299]
I posted this issue on SO: https://stackoverflow.com/questions/47916568/unintended-indents-with-plain-text-email

In trying to figure out what the problem was, I theorized that it was related to the character set **always** defaulting to us-ascii as posted by the SO user: https://stackoverflow.com/questions/43022838/phpmailer-altbody-plain-text-version-of-message-has-always-us-ascii-charset

Basically, I think that this kind of thing...
        //Can we do a 7-bit downgrade?
        if ('8bit' == $bodyEncoding and !$this->has8bitChars($this->Body)) {
           $bodyEncoding = '7bit';
           All ISO 8859, Windows codepage and UTF-8 charsets are ascii compatible up to 7-bit
           $bodyCharSet = 'us-ascii';
        }

overrides the user's intended CharSet.  If you do `$mail->CharSet = 'utf-8';`, then depending on the type of content in the email, the choice of utf-8 can be overridden and us-ascii will be used.  Is this the intended behavior?

FYI: There are two instances of this kind of logic in PHPMailer.php and also two in class.phpmailer.php

BTW: This is PHPMailer version 5.5.  I know v.6 is the current version, but this version is coming as part of another open source package.

**Comment by Synchro** [comment]
Yes, this is intentional and isn't a problem. UTF-8 and ASCII are identical up to 7-bit characters if you're not using any non-ASCII characters. That's why there is that call to `has8bitChars()`. If your message body is `hello`, it's identical in ASCII and UTF-8, and it's an RFC contravention to encode as 8bit if the content will fit in 7bit, and it also means you can drop the need for a Content-Transfer-Encoding header since 7bit is assumed by default. If your body is `héllo`, then it contains 8-bit characters, and so it won't get downgraded to ASCII - though beware that if you fail to tell it to use an 8-bit or UTF-8 charset when you need one (e.g. if you leave `CharSet` at its default `iso-8859-1` and include emoji in your message), you'll run into encoding problems.

**Comment by gtilflm** [comment]
Ok, thanks for the explanation.  That makes sense.

Any ideas on my SO post (https://stackoverflow.com/questions/47916568/unintended-indents-with-plain-text-email) by chance?
