### ISSUE TITLE
500 error on get_oauth_token.php

### ISSUE THREAD

**Issue by vivinblack** [PHPMailer/PHPMailer#1306]
Currently my website folder is hosted on google cloud platform. And I am trying to point toward (et_oauth_token.php )  after creating client id and client secrete . And I got 500 Internal error and its obvious as no autoload in current folder . I go through some threads that and found that I need do it using composer . But I don't know how to do it on cloud platform . Is there any other way upload phpmailer without using composer.

**Comment by Synchro** [comment]
This is mentioned in the readme - if you can't run composer directly on your host, run it locally (which will create the vendor folder and pull in all the dependencies) and upload the whole lot along with all your other PHP files.

**Comment by vivinblack** [comment]
U made awesome script for us. But why don't u keep simple download full zip file as required by us. Now before setting up phpmailer, i have to deal with this composer stuff and still I am not getting it .

**Comment by vivinblack** [comment]
I got vendor folder with "composer" , "phpmaile" folders & autoload.php file . but little bit of confusion here,what to upload in my sites folder. I moved vendor folder in my sites /html  but still its throwing an error 500.

**Comment by Synchro** [comment]
It's not that complicated. As the readme says, run composer locally and upload the vendor folder, then `require` the autoload.php file from where you upload that to. The reason for using composer for this is that it is *much less* complicated than managing dependencies yourself. Not everyone wants to use XOAUTH2, and since it's implemented using third-party libraries (just as you own app uses PHPMailer), it is an extremely bad idea to bundle such packages directly as it just makes for a massive management overhead. Composer makes it all much, much easier to manage; for the most part all you need to do is add one line to your project's `composer.json` file and run `composer install` - that's literally all there is to it.
