### ISSUE TITLE
ssl operation failed with code 1

### ISSUE THREAD

**Issue by miguelk5** [PHPMailer/PHPMailer#1308]
I get this error with PHP 5.6 , i think you should check your project before make it public ... i know that PHP 5.6 mark as invalid self certificates but that isnt my problem , the program should avoid that .

**Comment by Synchro** [comment]
No, this is exactly your problem. Rejecting invalid certificates is default PHP behaviour, and it's up to you to deal with it. Anything else is compromising your security and defeating the point of using encryption at all.

**Comment by miguelk5** [comment]
No , is not up to me , program should send valid certificate , learn to code lol !

**Comment by miguelk5** [comment]
95% of open-source is garbage ...

**Comment by Synchro** [comment]
Wrong. It's the server that you connect to that provides the certificate; PHPMailer does not send any certificates at all. If you're going to insult people, know what you're talking about first.

**Comment by miguelk5** [comment]
Typical open source fan ... so a programmer need to know everything what OS do on background , i think you use your own OS coded 100% on ASM , No , i dont know every detail of what PHPEmailer does , i just get stupid error message  . On computer A with php 5.6 works , on computer B with php5.6 do not works , people say it can be about certificate . 

However fail project , and looking for my own solution .

BTW i created Bulk emailer application using java mail api without any problem , so dont talk to me like i dont know what im doing.

Consider close this project PHPEmailer sucks..

**Comment by Synchro** [comment]
No, but you do need to understand the parts that you're using. Java had exactly the same issue when it did the same switch, as did ruby, perl, and python - this isn't a new problem. It's entirely possible that different installations of PHP 5.6 can have different results because they may be using different CA certificate bundles - the same applies to any other language using system-provided CA certs. Don't blame others for your own ignorance; learn, read documentation, and don't insult those that try to help you.
