### ISSUE TITLE
Problem using smpt of gmail

### ISSUE THREAD

**Issue by Deldros** [PHPMailer/PHPMailer#1310]
# Problem description
I'm Trying to send emails using the smpt of gmail but the server show me errors when I excecute the code.

# Code to reproduce

>     use PHPMailer\PHPMailer\PHPMailer;
>     use PHPMailer\PHPMailer\SMTP;
>     use PHPMailer\PHPMailer\Exception;
> 
>     require 'PHPMailer/src/PHPMailer.php';
>     require 'PHPMailer/src/SMTP.php';
>     require 'PHPMailer/src/Exception.php';
> 	
>     $mail = new PHPMailer();
>     $mail->IsSMTP();
>     $mail->CharSet = 'UTF-8';
>     $mail->Host = 'smtp.gmail.com';  
>     $mail->SMTPDebug  = 4;    
>     $mail->SMTPAuth   = true; 
>     $mail->Port       = 587;     
>     $mail->SMTPSecure = 'tls';  
>     $mail->Username = 'contacto@lexvirtual.cl';
>     $mail->Password = '******';     
>     //Recipients
>     $mail->setFrom('contacto@lexvirtual.cl', 'Lexvirtual.cl');
>     $mail->addAddress('rolo4436@gmail.com', 'Rolando'); 
>     //Content
>     $mail->isHTML(true); 
>     $mail->Subject = 'mesnajito de prueba';
>     $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
>     $mail->Body    = 'Probando el envio de  email, que opinas, fnciona´ra?</br> talves no pero hay que intentarlo';
>     if($mail->send()){
>         echo 'mensaje enviado';
>     }
>     else
>     {
>         echo 'No se udo enviar el mensaje';
>     }
>         

# Debug output

> 2017-12-27 20:05:02 Connection: opening to smtp.gmail.com:587, timeout=300, options=array()
> 2017-12-27 20:05:02 Connection: opened
> 2017-12-27 20:05:02 SMTP INBOUND: "220-id24426.grupoallegra.com ESMTP Exim 4.89_1 #1 Wed, 27 Dec 2017 15:05:02 -0500"
> 2017-12-27 20:05:02 SMTP INBOUND: "220-We do not authorize the use of this system to transport unsolicited,"
> 2017-12-27 20:05:02 SMTP INBOUND: "220 and/or bulk e-mail."
> 2017-12-27 20:05:02 SERVER -> CLIENT: 220-id24426.grupoallegra.com ESMTP Exim 4.89_1 #1 Wed, 27 Dec 2017 15:05:02 -0500 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail.
> 2017-12-27 20:05:02 CLIENT -> SERVER: EHLO lexvirtual.cl
> 2017-12-27 20:05:02 SMTP INBOUND: "250-id24426.grupoallegra.com Hello lexvirtual.cl [45.32.3.98]"
> 2017-12-27 20:05:02 SMTP INBOUND: "250-SIZE 52428800"
> 2017-12-27 20:05:02 SMTP INBOUND: "250-8BITMIME"
> 2017-12-27 20:05:02 SMTP INBOUND: "250-PIPELINING"
> 2017-12-27 20:05:02 SMTP INBOUND: "250-AUTH PLAIN LOGIN"
> 2017-12-27 20:05:02 SMTP INBOUND: "250-STARTTLS"
> 2017-12-27 20:05:02 SMTP INBOUND: "250 HELP"
> 2017-12-27 20:05:02 SERVER -> CLIENT: 250-id24426.grupoallegra.com Hello lexvirtual.cl [45.32.3.98]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250-STARTTLS250 HELP
> 2017-12-27 20:05:02 CLIENT -> SERVER: STARTTLS
> 2017-12-27 20:05:02 SMTP INBOUND: "220 TLS go ahead"
> 2017-12-27 20:05:02 SERVER -> CLIENT: 220 TLS go ahead
> 2017-12-27 20:05:02 Connection failed. Error #2: stream_socket_enable_crypto(): Peer certificate CN=`id24426.grupoallegra.com' did not match expected CN=`smtp.gmail.com' [/home/xelvirtu/public_html/pablo<3/PHPMailer/src/SMTP.php line 405]
> SMTP Error: Could not connect to SMTP host.
> 2017-12-27 20:05:02 CLIENT -> SERVER: QUIT
> 2017-12-27 20:05:02 SMTP INBOUND: "221 id24426.grupoallegra.com closing connection"
> 2017-12-27 20:05:02 SERVER -> CLIENT: 221 id24426.grupoallegra.com closing connection
> 2017-12-27 20:05:02 Connection: closed
> SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
> No se udo enviar el mensaje
> 

Where is the error? I think it's a server error but I'm not sure

**Comment by Synchro** [comment]
I'm to sure what you mean - it's showing the error quite clearly, and it's a problem described [in the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#certificate-verification-failure). You're asking to connect to `smtp.gmail.com`, but you are actually connecting to `id24426.grupoallegra.com`, and so of course the name on the TLS certificate does not match. This is because your ISP is transparently redirecting SMTP traffic to their own server, and the certificate mismatch is allowing you to detect that this is happening, and is then refusing to continue - so it's working exactly as intended. If it did not do this, it would proceed and give away your gmail credentials to what could be an unknown man-in-the-middle attacker, though it's more likely to just be your ISP.

The solution to this is to connect directly to your ISP's server intentionally (see their documentation or support services for what they want you to do - every ISP is different), and then the certificate will match. Unfortunately, this also means that you will not be able to use your gmail address as a from address as that's forgery and your messages will be rejected by SPF checks, so you will need to change your from address as well. You may be able to ask your ISP to allow SMTP connections to gmail.
