### ISSUE TITLE
Composer Autoloader - Not Working (>= 1.6.0)

### ISSUE THREAD

**Issue by laurin1** [PHPMailer/PHPMailer#1316]
As of Composer 1.6.0, autoloader does not work. I've confirmed in Composer 1.5.6 and 1.6.0-RC, it works, but in 1.6.0, this fails to load.

https://github.com/composer/composer/compare/1.6.0-RC...1.6.0

"Class 'PHPMailer\PHPMailer\PHPMailer' not found"

Using PHPMailer 6.0.2.

**Comment by laurin1** [comment]
Fails in 1.6.1 as well. FYI, I have 2 packages failing:

https://github.com/mtdowling/cron-expression/issues/166

Oh, duh:

https://github.com/composer/composer/issues/6977

**Comment by Synchro** [comment]
I don't think there's anything I can do about this - it needs to be fixed in composer. PHPMailer accounts for just one line in a project's composer.json, and AFAIK the syntax for that has not changed at all. The PHPMailer file layout is bog-standard PSR-4. If PHPMailer has a problem, I suspect many other packages do too.

**Comment by laurin1** [comment]
I agree - I didn't see this as Composer issue until after I opened this one.
