### ISSUE TITLE
Can you pass the type of the message to the edebug function?

### ISSUE THREAD

**Issue by n-for-all** [PHPMailer/PHPMailer#1334]
example:
`protected function edebug($str, $type='exception')`
with types like "info", "error", "exception" etc...

Then pass it to the user defined function:
`call_user_func($this->Debugoutput, $str, $this->SMTPDebug, $type);`

- The purpose of this is to log only errors or unsent emails, capturing the type will allow us to check which emails was not sent and why.
- it will allow us to use debugging in production mode.
- simpler, smaller and much more accurate log.

Simply i am much more concerned about the unsent emails and not the sent ones.

Is this possible?

**Comment by Synchro** [comment]
Debug output is orthogonal to error handling; you shouldn't be using the former to do the latter. One thing you can do though is inject your own handler into `Debugoutput`, and use that to check the error status at the time you receive an error. The `Errorinfo` property will tell you what kind of error it is, and you can use that inside your error handler to decide whether/when/where/how to log it. There's an example of injecting a debug handler in the source and in [this example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/extending.phps).

Ultimately this needs addressing by replacing the exception system in PHPMailer; I wrote a better one back in about 2008, but the maintainer at the time made a bit of a mess of it which resulted in the strange use of constants like `self::STOP_CRITICAL` rather than different Exception subclasses, which we're stuck with until we choose to break BC.
