### ISSUE TITLE
How Can I get Delivery Report of sent mail?

### ISSUE THREAD

**Issue by codersaiful** [PHPMailer/PHPMailer#1335]
Actually I have made a script with PHPMailer.
Sometimes, I faced a problem. 

Problem is that: 
I want to sent a mail by using a my SMTP. SMTP information is right. There is no problem.
Even when I trying to send mail, I gotten message: Mail has sent.
But mail doesn't sent. I mean: No mail inboxing.  But script displaying: Mail has sent.

After that, when I check smtp's mail server, than follow that: there is "Delivery report of fail Message".

## In this situation, I would like to get Delivery report. 
# How can I get delivery Report. Is there any way?

**Comment by Synchro** [comment]
You need to set the `Sender` property in PHPMailer so that bounced messages go somewhere you can process them (also see [VERP addressing](https://en.wikipedia.org/wiki/Variable_envelope_return_path)). All mail servers have the ability to pipe inbound messages to a script, so you then need to do that. Be warned though, PHPMailer doesn't have anything to do with bounce processing, and writing bounce processors is very unpleasant; you can a start using packages though, such as [voku/bounce-mail-handler](https://packagist.org/packages/voku/bounce-mail-handler).
