### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by marwanelsamman** [PHPMailer/PHPMailer#1358]
Hello all,
I am less than a beginner in this field, I just want to use PHPMailer on a "SHARED HOSTING PLAN" from "GODADDY" because I tried all of the workarounds to send an attachment file in a mail using the php mail() function but it didn't work for me.

I tried to find someone who describes how to use this PHPMailer on a shared host but all of the articles I found is talking about autoload files and something like that which I don't find it in the zip file which I downloaded.

Please I would appreciate if someone explained to me how to use this in my case taking in consideration my level in this field while you are writing an answer.

Waiting for your responses and  thanks a lot.

**Comment by Synchro** [comment]
The most effective thing you can do as a beginner is *read the docs* and code examples (because most of what you've asked is answered in there). That way you don't have to waste time writing questions and waiting for replies.

Shared hosting on GoDaddy is unfortunately something of a worst-case scenario as far as sending email goes. It's cheap for a reason. GoDaddy has documentation that you should follow.

Read the readme, which tells you which files you need, and where autoload.php comes from (composer).

**Comment by asmaulhq** [comment]
Hi marwanelsamman,

I completely agree with @Synchro 

Here's the few steps to do it quickly.

1. Download composer from https://getcomposer.org/
2. Select php.exe while installing. E.g D:\xampp\php\php.exe
3. Create a new folder in htdocs
4. Open CMD and navigate to that folder
5. Paste "composer require phpmailer/phpmailer" and hit enter.
6. Use "Example" code from https://github.com/PHPMailer/PHPMailer#a-simple-example

You're DONE.

If you're still facing problem using xampp/composer, you can simply download files from the link below.
https://www.dropbox.com/s/1banmio6yg43rfi/phpmailer_with_autoload.php.zip?dl=0

-
Thanks

**Comment by marwanelsamman** [comment]
Thanks a lot for all of you.
Special Thanks for @asmaulhq for the great help.
It works for me and I got some new info about it which I hadn't before.
