### ISSUE TITLE
SMTP PHPMailer Problem With cPanel

### ISSUE THREAD

**Issue by Sibbern** [PHPMailer/PHPMailer#1359]
This is not a post about a bug but more recommending adding this to your troubleshoot guide for cPanel users. 

I was adding SMTP information but continued to get the error code "ERROR: Failed to connect to server: Connection refused (111)" and after 2 days of searching to find a solution I've found out that cPanel blocks all SMTP  connection from another server by default. 

Disable this restriction in WHM> Security Center > SMTP Restrictions Disable

Just posting this for others because I've been searching for ages and it should be on the troubleshoot page.

**Comment by Synchro** [comment]
You do know that all the wiki pages are publicly editable? Anyone can make changes, so go ahead and add it. That said, the troubleshooting page is getting a bit big - it may be a good idea to break out info about particular software or ISPs into a separate page.

**Comment by David263** [comment]
I think this information belongs in the README.MD file at https://github.com/PHPMailer/PHPMailer. Otherwise, I almost assumed that PHPMailer would somehow work with WHM > Home > Security Center > SMTP Restrictions Enabled. But it is clear that PHPMailer doesn't provide any special way to appear to run as root or the email server on a remote mailserver.

My conclusion is that if one decides to enable SMTP Restrictions in order to prevent relaying by spammers, there is no way one can also run applications that can send email notifications. This should be more widely known: it is a stupid problem caused by incomplete support for sending secure email from PHP (or anywhere else) using PHP fsockopen function or similar. If true security were implemented, fsockopen would supply the pathname of a private RSA or similar key for the remote mailserver, and there would be no need for the SMTP Restrictions hack. It should be simple and secure, but currently it's not.

Maybe we need an entirely new mail system, using the same security as the Web? It would get adopted quickly, especially if there were a deadline for migrating from current email.

Whatever. At least the https://github.com/PHPMailer/PHPMailer README should explain this limitation.

**Comment by Synchro** [comment]
That doesn't make much sense. PHPMailer is a library, not a script, and has absolutely no say in how it is used, so for example it cannot make any assumptions or assertions about the user it is running as. That said, it *does* support secure connections via the same mechanism that all mail servers support: SMTPS and SMTP+STARTTLS, and via SSL options you are able to supply a client certificate.

If you need to run as root to get around some limitation of cPanel then *the script that calls PHPMailer* needs to run as root - it's absolutely not up to PHPMailer.

Similarly, SMTP servers typically have two perfectly usable mechanisms to prevent relaying by spammers - authentication and source IP whitelisting. Again though, PHPMailer supports those protocols, but it's up to you to configure them on your server, it's not something that PHPMailer can do anything about. I don't see any circumstances where you would need the private key of a remote server; that just sounds broken.

Email does use exactly the same transport security protocols as the web: there is no difference at all between connecting to a mail server with implicit TLS and connecting to a web server over HTTPS; you literally cannot tell them apart before a secure connection is already established. If you're talking about enforcing TLS, then perhaps you should look into MTA-STS, which is the email equivalent of HSTS for HTTP. However, it requires that your mail server makes HTTP requests during mail transactions, which brings its own set of problems.
