### ISSUE TITLE
Troubleshooting wiki is gone

### ISSUE THREAD

**Issue by madsci77** [PHPMailer/PHPMailer#1426]
All of the links I've followed while trying to troubleshoot a TLS error have taken me to https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting, but the wiki was blank.  I've added a link to the archive.org cache for now.  If the guide has been moved elsewhere, maybe the wiki could at least have the new URL?

**Comment by dracken** [comment]
Doesn't look like the reversion that @syncro performed worked as I'm still seeing 'hhihi' on that page, the last good revision before user angilinea87 (who has since deleted their profile) is https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting/f5babff28c37b728c4230e23d781c6f97bec2a5d.  @Synchro Are you able to revert back to this branch in the wiki?

**Comment by Synchro** [comment]
I attempted to restore that version, (you can see it in the history now), but for some reason it didn't work. I've asked github for help.

**Comment by Synchro** [comment]
I didn't get a response so I restored it manually.
