### ISSUE TITLE
Add constants for standard charsets, content-types and encodings

### ISSUE THREAD

**Issue by maxbeckers** [PHPMailer/PHPMailer#1428]
It would be helpful to have constants for the following values:
charset: 'iso-8859-1', 'utf-8'
content-type: 'text/plain', 'text/html',...
encoding: "8bit", "7bit", "binary", "base64" and "quoted-printable"

**Comment by maxbeckers** [comment]
Our main problem was a typo in `utf-8` => `utf8`. But we also set the other headers sometimes manually. So we thought it'll be helpful for others too. And using a constant instead of writing a string often in code is also a best practice.

**Comment by Synchro** [comment]
There would certainly be an advantage in IDEs that validate properties that could flag a typo that would not happen on a string value.

I'd be tempted to abstract the charset more:

    const CHARSET_DEFAULT = static::CHARSET_ISO88591;

then:

    public $CharSet = static::CHARSET_DEFAULT;

One other issue is that this would be a BC break for anyone not using composer (possibly a majority of PHPMailer users). Since these constants are used *only* within the PHPMailer class, why put them outside?

**Comment by maxbeckers** [comment]
`utf8` is not a typo in IDE.
The issue/pr was just a solution to optimize the code. I didn't add it to the mailer class to have it separated from the logic part.

**Comment by maxbeckers** [comment]
I've moved the constants into the `PHPMailer`.
