### ISSUE TITLE
Debugoutput parameter missing from Readme example

### ISSUE THREAD

**Issue by mayavirtual** [PHPMailer/PHPMailer#1442]
# Problem description

The example in the Readme doesn't include $mail->Debugoutput, which caused $mail->send() to hang with no error output when the example was added to our application. Setting $mail->Debugoutput to 'error_log' resolved the issue.

The example should have:

//Server settings
$mail->SMTPDebug = 2;                                     // Enable verbose debug output
$mail->Debugoutput = 'error_log';			     // Direct Debug Output to PHP error_log

**Comment by Synchro** [comment]
No. The default value for `Debugoutput` is `echo`, which will output to both browser or command line. Output to `error_log` will usually be invisible, which isn't much use for interactive debugging. I don't know why it would cause your app to hang - perhaps you had some kind of output buffering enabled? Bear in mind that debug output is for debugging during development, not production logging. If you want it to act differently, inject your own implementation - that's why it's there.
