### ISSUE TITLE
phpMailer external style problem.! NOT WORKING

### ISSUE THREAD

**Issue by HaliAlduhoky** [PHPMailer/PHPMailer#1450]
Hello.

All thing going good with phpmailer, expect styling my mail template in the email.
This is my code.
```html
<html>
<head>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
</head>
<body>....
```

I do not know what's the problem exactly.
note: i sending my emails to !Yahoo mail.

**Comment by Synchro** [comment]
Er, HTML email doesn't support external style sheets.

**Comment by HaliAlduhoky** [comment]
So what is the best way to styling my template? please just give me the informations.

**Comment by Synchro** [comment]
http://lmgtfy.com/?q=how+to+style+email

**Comment by HaliAlduhoky** [comment]
hhh that was best sulation,
http://lmgtfy.com/?s=d&q=Thanks+a+loot.+but+i+already+searched+on+google+about+it+and+i+do+not+found+the+best+answer.

**Comment by Synchro** [comment]
You're just not trying. [The first linked article in that search](https://css-tricks.com/using-css-in-html-emails-the-real-story/) says:

>Link to an external stylesheet. Not many email clients support this, best to just forget it.

[The second one](https://litmus.com/blog/a-guide-to-css-inlining-in-email):

>While external stylesheets are a great option for web design, they aren’t the best option for email design—many webmail clients block links to external stylesheets.

There are absolutely tons of resources on styling email, but you do have to actually read them. There's no point in me listing them here because they are the same as in the search results, and you're not listening to what I say anyway.
