### ISSUE TITLE
Outgoing emails are not encrypted no matter what I do

### ISSUE THREAD

**Issue by miranor** [PHPMailer/PHPMailer#1475]
Please check these things before submitting your issue:

- [ ] *Read the error message* you're seeing - it often tells you what is wrong, and may contain useful links & instructions
- [ ] Make sure you're using the latest version of PHPMailer
- [ ] Check that your problem is not dealt with in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting), especially if you're having problems connecting to Gmail or GoDaddy
- [ ] Include sufficient code to reproduce your problem
- [ ] If you're having an SMTP issue, include the debug output generated with `SMTPDebug = 2` set
- [ ] If you have a question about how to use PHPMailer (rather than reporting a bug in it), tag a question on Stack Overflow with `phpmailer`, but [**search first**](http://stackoverflow.com/questions/tagged/phpmailer)!

# Problem description
PHPMailer works just fine from my localhost (no errors, nothing is printed even at SMTPDebug = 4), sends emails perfectly, except that they are not encrypted (no TLS/SSL).

I've specified as follows in my code before calling 'send' (and nothing else that relates to encryption):
$mail->Host='tls://localhost:587';

I have the following in php.ini:
extension=php_openssl.dll
openssl.cafile="C:\php54\cacert.pem"
curl.cainfo="C:\php54\cacert.pem"

Notes:
- cacert.pem file is valid and brand new, its location is correct
- openssl is loading fine, no errors
- I'm using the latest PHPMailer - version 6.0.5

The only problem I could possible imagine is that I'm using PHP 5.4, while PHPMailer 6.0.5 is supposedly compatible with PHP 5.6 and later. Could this be the problem or is it something simpler, given that it otherwise works perfectly? I'd rather not upgrade to PHP 5.6 unless I REALLY have to.

# Code to reproduce

# Debug output

**Comment by Synchro** [comment]
If you're seeing no SMTP debug output, it suggests you're not using SMTP - are you calling `isSMTP()`?

It's academic anyway; because your hostname is `localhost`, it will never match your certificate, and establishing an encrypted connection will fail - but there is nothing to be gained by encrypting a connection to localhost anyway.

You *really* have to upgrade your PHP, because 5.6 and 7.x are the only supported versions, and you're inviting security problems (not to mention ignoring the enormous performance gains) otherwise.
