### ISSUE TITLE
Word Wrap issue

### ISSUE THREAD

**Issue by patelriya5736** [PHPMailer/PHPMailer#1493]
In PHPMailer how word-wrap is worked?
html style property word-wrap is not working..
Plz help..
Thank you.

**Comment by Synchro** [comment]
You don't define "not working". Word wrap is only applied as internal formatting to prevent long lines, and because HTML collapses and ignores white space, line breaks in HTML do not appear in rendered output. This is a standard feature of HTML, not specific to email or PHPMailer. If you want line breaks to appear, you need to convert them to `<br>` tags in your HTML, for example using PHP's `nl2br()` function.
