### ISSUE TITLE
$SMTPOptions is not documented

### ISSUE THREAD

**Issue by ChazyTheBest** [PHPMailer/PHPMailer#1512]
I've been looking the wiki and then the docs but it looks like this property is not documented.

In the examples, there's a comment above this property stating that "these settings are INSECURE", it is also the only example.

I would really appreciate if you could document this a little. Thanks.

**Comment by ChazyTheBest** [comment]
Oh, in that case I won't use it, I thought I could specify some more options from my SMTP server (postfix) but it is already working without it.

For example, I saw in the example there's `allow_self_signed => true`, but I'm not using self signed certificates, is that the default option? If so I should probably change it to false. But I guess if I just leave the host option hardcoded, as the SMTP server is already properly configured (what to allow and what not) it should work without any problems.

**Comment by Synchro** [comment]
No, self-signed certs are not permitted by default. Allowing self-signed certs often gets lumped together with disabling certificate verification, presumably because you also need verification turned off if you do need to use self-signed certs, so it covers both use cases. That property is purely about the TLS phase of the connection, it has no effect on SMTP itself.
