### ISSUE TITLE
INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

### ISSUE THREAD

**Issue by oasfuyou** [PHPMailer/PHPMailer#1527]
Please check these things before submitting your issue:

- [ ] *Read the error message* you're seeing - it often tells you what is wrong, and may contain useful links & instructions
- [ ] Make sure you're using the latest version of PHPMailer
- [ ] Check that your problem is not dealt with in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting), especially if you're having problems connecting to Gmail or GoDaddy
- [ ] Include sufficient code to reproduce your problem
- [ ] If you're having an SMTP issue, include the debug output generated with `SMTPDebug = 2` set
- [ ] If you have a question about how to use PHPMailer (rather than reporting a bug in it), tag a question on Stack Overflow with `phpmailer`, but [**search first**](http://stackoverflow.com/questions/tagged/phpmailer)!

# Problem description

# Code to reproduce

# Debug output

**Comment by oasfuyou** [comment]
INI directive 'mbstring.func_overload' is deprecated since PHP 7.2,pelase add a new release

**Comment by Synchro** [comment]
I changed my mind about that last commit. That directive may be deprecated, but it may still be there and needs to be acted upon if it is set, even in 7.2. Once it's been removed (I assume in PHP 7.3), the ini value will no longer exist, and thus will no longer match the condition, so it will fail safely - this is quite different to the removal of a PHP built-in function. Because the current version maintains compatibility back to PHP 5.5, this reference should not be removed.
