### ISSUE TITLE
Mailer Error: SMTP connect() failed.    who konw this?

### ISSUE THREAD

**Issue by luoyajiang** [PHPMailer/PHPMailer#1582]
![image](https://user-images.githubusercontent.com/33601095/47500579-c3b5d300-d895-11e8-97f2-4b78ee95d6e7.png)

**Comment by Synchro** [comment]
The documentation knows.

**Comment by luoyajiang** [comment]
why close my issue?

**Comment by Synchro** [comment]
Because your question has been answered. Read the documentation linked from your error message; It tells you what this error might mean and how to solve it. Retyping the same thing here isn't going to make the problem or its solution any different. You've already avoided doing this at least 3 times.

**Comment by luoyajiang** [comment]
![image](https://user-images.githubusercontent.com/33601095/47501299-c3b6d280-d897-11e8-8879-e3b708deef1d.png)


![image](https://user-images.githubusercontent.com/33601095/47501326-d5987580-d897-11e8-89cf-211ea4634d08.png)


![image](https://user-images.githubusercontent.com/33601095/47501374-f52f9e00-d897-11e8-9e28-f5b083822288.png)

this can not help me?please

**Comment by luoyajiang** [comment]
thank you!   
because  163.com
so  
$mail->Host = 'smtp.163.com'; 
$mail->SMTPSecure = 'ssl';                           
$mail->Port = 465;
