### ISSUE TITLE
TLS Error Mailer

### ISSUE THREAD

**Issue by everdominguez** [PHPMailer/PHPMailer#1604]
Hi dear,

Days ago my PhpMailer worked fine but now it shows:

` Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure in /home/avintur1/public_html/avinsys/mailer/PHPMailer/class.smtp.php on line 344`

I'm using TLS, my php version is 5.6 and my phpMailer is 5.2.14

```
$mail = new PHPMailer;
$mail->isSMTP();                                   // Set mailer to use SMTP
$mail->Host = 'smtp.zoho.com';                    // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                            // Enable SMTP authentication
$mail->Username = 'EMAIL';          // SMTP username
$mail->Password = 'PASSWORD'; // SMTP password
$mail->SMTPSecure = 'tls';                         // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                 // TCP port to connect to 

``` 
I read this post but not yet I can't send an email

https://github.com/PHPMailer/PHPMailer/issues/542

**Comment by Synchro** [comment]
You ignored the very first thing in the issue template - make sure you are running the latest version of PHPMailer. The version you are running contains security vulnerabilities, along with numerous fixes. The PHP version you are running will be end of life next month too.

As for your specific problem, your code looks ok, so it will be an environmental problem - the mail server’s certificate may have expired or not be verifiable due to outdated CA certificates. Read the troubleshooting guide for how to deal with those issues.
