### ISSUE TITLE
get_oauth_token.php does not work

### ISSUE THREAD

**Issue by WereDuck** [PHPMailer/PHPMailer#1613]
Please check these things before submitting your issue:

- [x] *Read the error message* you're seeing - it often tells you what is wrong, and may contain useful links & instructions
- [x] Make sure you're using the latest version of PHPMailer
- [x] Check that your problem is not dealt with in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting), especially if you're having problems connecting to Gmail or GoDaddy
- [x] Include sufficient code to reproduce your problem
- [x] If you're having an SMTP issue, include the debug output generated with `SMTPDebug = 2` set
- [x] If you have a question about how to use PHPMailer (rather than reporting a bug in it), tag a question on Stack Overflow with `phpmailer`, but [**search first**](http://stackoverflow.com/questions/tagged/phpmailer)!

# Problem description
After selecting Google in the get_oauth_token.php script's menu the page remains blank, no errors or anything else is displayed.
# Code to reproduce
Run get_oauth_token.php in the /vendor/phpmailer/phpmailer directory.
# Debug output
None
# Solution
Change line 59 from:
require 'vendor/autoload.php';
to:
require '../../../vendor/autoload.php';
# Note
This took me days and luck to figure out but once done (and my creds were entered) I got the refresh token.
Also moving the script to the root directory did not work, the menu never appeared.

**Comment by Synchro** [comment]
This is project specific - we can't assume where the root of the project is when PHPMailer is included as a dependency - you need to do what you have done and adapt it for your specific project. You'll probably only ever need to run it once - the tokens you get can last forever. The path it uses works correctly when you check out PHPMailer as a standalone, but it should also work if your CWD is your project root, since require/include is always relative to that (which is different to the location of the current file).

The script is run in one of three ways:

1. It's run with no URL params, in which case the menu will appear.
2. It's run with a `provider` param, in which case it will try to fetch a token.
3. It's run as a callback by the service provider, and it will have the `code` value populated, and will then display the refresh token.

Because of this third option, it can't be run successfully on localhost as the callback will never work.
