### ISSUE TITLE
Request for example code for php NOT in same file as form and not using composer

### ISSUE THREAD

**Issue by wolfie42** [PHPMailer/PHPMailer#1623]
Any chance you could add to your wish list? Both of your example codes show what the code would look like if on the same page as the form. I need it separated out but can't find a good example. And my google search shows dozens of different options which is confusing. So figured I'd go to the source, that it couldn't hurt to ask :)

**Comment by Synchro** [comment]
Most of the examples do not contain any HTML at all, but when they do it provides context for the code in the way it’s commonly used. There are infinite ways of splitting up your code, but that’s really a subject for the PHP docs - what’s here is to explain how to use PHPMailer, not how to use PHP in general.

The readme describes how to load PHPMailer without composer, but I’ve not done that in any examples because it’s not a pattern of library usage that should be encouraged.
