### ISSUE TITLE
validateAddress() *always* uses 'php' as $patternselect

### ISSUE THREAD

**Issue by utrenkner** [PHPMailer/PHPMailer#1652]
Please check these things before submitting your issue:

- [ x] *Read the error message* you're seeing - it often tells you what is wrong, and may contain useful links & instructions
- [ x] Make sure you're using the latest version of PHPMailer
- [ x] Check that your problem is not dealt with in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting), especially if you're having problems connecting to Gmail or GoDaddy

# Problem description
I am about to migrate an old application to a new server, which runs PHP7.3 on HardenedBSD (essentially FreeBSD). So far, we still used the old 5.2 branch of PHPMailer and I ran into the problem described in [issue #1641](https://github.com/PHPMailer/PHPMailer/issues/1641): The REGEX in validateAddress() would not accept any legal email address such as test@example.com.

Then I upgraded to the latest 6.0 release, and to my surprise, this worked! I checked the REGEX of the old 5.2 and the latest 6.0 and they are the same! I quickly found that on my system, validateAddress() always used 'php' as $patternselect. I checked on a Debian system running PHP 5.6. Same. Even though PCRE is available on both systems.

Then I checked the PHPMailer.php, and I could not find any code, which could trigger the use of 'pcre8' - or _anything_ other than 'php'.

The code which used to [determine the $patternselect to use](https://github.com/PHPMailer/PHPMailer/blob/5.2-stable/class.phpmailer.php#L1082-L1103), seems to have been deleted from 6.0.

Thus, such code should either be reinstated. Or validateAddress() could be simplified to just use the PHP filter.

**Comment by Synchro** [comment]
The default validator was changed to the PHP one in 6.0 because there has been a history of particular versions of PCRE breaking (or hanging up for a long time) on the complex pattern used in `pcre8`. What it brings in benefits is not significant enough to continue with it as the default, given these problems, so it's really only there for backward compatibility. This is mentioned in the changelog.

You can change the pattern it uses by setting the class property `PHPMailer::$validator` ([source](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L523)) to a string, such as `php`, which will use the PHP built-in validator by default, or use it to inject your own validator, like this:

```php
PHPMailer::$validator = function($address) {
    return (strpos($address, '@') !== false);
};
```

`validateAddress()` will then use whatever you have set it to, even when it's called internally.

It's a static class property and not a dynamic one because it's very unlikely you would want inconsistent validation in a single app.

Alternatively, subclass PHPMailer and override the default value of the `$validator` property.

All of this is [documented in the source](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1204) for the `validateAddress` function.
