### ISSUE TITLE
PROBLEMS SMTP

### ISSUE THREAD

**Issue by leidyv1990** [PHPMailer/PHPMailer#1690]
hello 

I'm having a problem

× Successful addition
× SMTP connect () failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

When I create a record in my application I get this error and it does not let me send emails.

use phpmaker.
![1](https://user-images.githubusercontent.com/48773307/54720290-0b7f1480-4b2d-11e9-9172-5521fd15c91f.JPG)

the framework generates these files, update the
class.phpmailer
class.phpmaileroauth
class.pop3
class.smtp

with the code that is here

https://github.com/PHPMailer/PHPMailer/tree/master/src

when updating I get this error

Fatal error: Class 'PHPMailer' not found in D: \ InetPub \ vhosts \ aplicativossiis.com \ httpdocs \ apl \ test_settings \ phpfn12.php on line 6568

and the line is

// Function to send email
function ew_SendEmail ($ sFrEmail, $ sToEmail, $ sCcEmail, $ sBccEmail, $ sSubject, $ sMail, $ sFormat, $ sCharset, $ sSmtpSecure = "", $ arAttachments = array (), $ arImages = array (), $ arProperties = NULL) {
global $ Language, $ gsEmailErrDesc;
$ res = FALSE;
$ mail = new PHPMailer (); --------- **THIS IS THE LINE**
$ mail-> IsSMTP ();
$ mail-> Host = EW_SMTP_SERVER;
$ mail-> SMTPAuth = (EW_SMTP_SERVER_USERNAME <> "" && EW_SMTP_SERVER_PASSWORD <> "");
$ mail-> Username = EW_SMTP_SERVER_USERNAME;
$ mail-> Password = EW_SMTP_SERVER_PASSWORD;
$ mail-> Port = EW_SMTP_SERVER_PORT;
if ($ sSmtpSecure <> "") {
$ mail-> SMTPSecure = $ sSmtpSecure;
$ mail-> SMTPOptions = array ("ssl" => array ("verify_peer" => FALSE, "verify_peer_name" => FALSE, "allow_self_signed" => TRUE));
}

**Comment by Synchro** [comment]
You are doing something very strange - it looks like you're taking the current versions of the PHPMailer classes and pasting their contents into old files. There's a simple solution: **don't do that**. Use the library as it is; you should not have to touch the code *at all* to use it.

The error you are getting is because you're trying to use the new version as if it was the old version, which will not work. Base your code on the examples provided and it will work fine. How to load PHPMailer classes manually is described in the readme.
