### ISSUE TITLE
unable to hide the SMTP username

### ISSUE THREAD

**Issue by celleyes** [PHPMailer/PHPMailer#1692]
I am having a problem. i have created a temp account for SMTP emails because of disclosure of username and password and sending email to my client's email.

but when my client receive the email. it shows my temp account username on from eventhough i didn't setup my username account , instead i have emial of a username how it filling up the form

	$mail->setFrom($email, $first_name . ' ' . $last_name);

but it shows my username.

**Comment by Synchro** [comment]
Yes, that's because you're forging the from address, and many ISPs (such as gmail) don't allow that, and substitute your account address instead. The appropriate route is not to try to forge the address. Gmail does allow you to pre-configure account aliases for a gmail account, but you have to specify those in advance, numbers are limited, and you still can't use arbitrary from addresses.

What do you mean by "because of disclosure of username and password"?

**Comment by celleyes** [comment]
Thanks, i see how it works so it boils down to the gmail.
please never mind the disclosure, its not the phpmailer specific, it was only my concern for hardcoding or making constant of credentials which i always hesitate to do.
