### ISSUE TITLE
Strange situation, what I`m doing wrong

### ISSUE THREAD

**Issue by r0073rr0r** [PHPMailer/PHPMailer#1693]
Please check these things before submitting your issue:

- [ X ] *Read the error message* you're seeing - it often tells you what is wrong, and may contain useful links & instructions
- [ X ] Make sure you're using the latest version of PHPMailer
- [ X ] Check that your problem is not dealt with in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting), especially if you're having problems connecting to Gmail or GoDaddy
- [ X] Include sufficient code to reproduce your problem
- [ ] If you're having an SMTP issue, include the debug output generated with `SMTPDebug = 2` set
- [ ] If you have a question about how to use PHPMailer (rather than reporting a bug in it), tag a question on Stack Overflow with `phpmailer`, but [**search first**](http://stackoverflow.com/questions/tagged/phpmailer)!

# Problem description
I have a strange situation.
I setup correctly SPF, DKIM and DMARC records.
When i send mail via terminal telnet localhost 25
i got email with all headers SPF pass, DKIM pass, DMARC pass.

But when i sending via PHPMailer i only got SPF pass and DKIM pass, no DMARC in headers at all.

# Code to reproduce

```
$mail = new PHPMailer\PHPMailer\PHPMailer;
                $mail->Encoding = "base64";
                $mail->CharSet = "UTF-8";
                $mail->IsSMTP();
                $mail->SMTPDebug = false;
                $mail->SMTPAuth = false;
                $mail->SMTPOptions = array(
                    'ssl' => array(
                        'verify_peer' => false,
                        'verify_peer_name' => false,
                        'allow_self_signed' => true
                    )
                );
```
....

# Debug output
**From PHPMailer:**
```
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@xxx.xxx header.s=mailinfo header.b=pjeaGHo3;
       spf=pass (google.com: domain of info@xxx.xxx designates xxx.xxx.xxx.xxx as permitted sender) smtp.mailfrom=info@xxx.xxx
```

**From Terminal using telnet:**
```
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@xxx.xxx header.s=mailinfo header.b="kCd/7IYL";
       spf=pass (google.com: domain of info@xxx.xxxo designates xxx.xxx.xxx.xxx as permitted sender) smtp.mailfrom=info@xxx.xxx;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=xxx.xxx
```

Sry 4 reporting as issue, but I dont know what to do next :(

**Comment by Synchro** [comment]
Firstly, why are you disabling certificate verification? There is no need to do that, especially if you're using gmail - read the troubleshooting guide about that.

This is indeed strange - DMARC has no presence within messages at all - it's all indirect through SPF, DKIM and DMARC settings in your DNS. That said, you've not posted your complete code - if your from address is not set correctly it may be falling back to something generated like `www-data@localhost.localdomain`. Make sure you are setting the from address explicitly since DMARC *does* refer to the from address within the message (as well as the envelope sender/return path) so you need to make sure it's correct.

**Comment by r0073rr0r** [comment]
Thanks a lot, problem was in DNS propagation of all servers.
