### ISSUE TITLE
Plus sign in mail addresses isn't correctly encoded

### ISSUE THREAD

**Issue by m4z** [PHPMailer/PHPMailer#1730]
I just tried to register with the newsletter of a random website that seems to be using:
``
X-Mailer: PHPMailer 5.2.22 (https://github.com/PHPMailer/PHPMailer)
``

The confirmation mail contained the following link:
``
http://[redacted].de/?es=optin&db=90&email=myname+foo@gmail.com&guid=[redacted]&cache=[redacted]
``

With both links from that mail, I received an error message and was unable to confirm the registration. When I manually replaced the plus sign in my mail address with "`%2b`", I was able to register just fine.

**Comment by Synchro** [comment]
PHPMailer doesn't do anything with the content you put in your message body; that's entirely up to you. That means that you are responsible for encoding emails embedded in URLs like that, for example:

    $mail->Body = 'http://[redacted].de/?es=optin&db=90&email=' . rawurlencode($address) . '&guid=[redacted]&cache=[redacted]';

In a URL context, a `+` character is ambiguous as it is treated as a space by Javascript and possibly in other contexts, which is why you should use `rawurlencode` in preference to `urlencode`.

**Comment by m4z** [comment]
Thanks, I will notify the site owner.
