### ISSUE TITLE
Allow PHPMailer to automatically remove sent attachments from file system

### ISSUE THREAD

**Issue by mnewnham** [PHPMailer/PHPMailer#1732]
This is a trivial enhancement request, it's a feature that I've added to every version of PHPmailer I've used.

It relates to a simple cleanup of attachments in bulk email sent out where the attachment has been generated specifically to be emailed. This allows PHPmailer to do the task of removing the attachment from the file system. Happy to provide a pull if needed

in PHPMailer 

````php
/**
* Whether to remove the attachment from the filesystem if the mail is sent
*
* @var bool
*/
public $deleteAfterAttaching = false;
````

in function encodeFile()
replace
````php
return $file_buffer
````
With
````php
if ($this->deleteAfterAttaching)
	@unlink($path);

 return $file_buffer;
````

**Comment by Synchro** [comment]
Thanks for the suggestion, but I don’t think this is an appropriate addition. It’s really outside PHPMailer’s area of responsibility, in much the same way that it avoids being an HTTP client, because it opens the door to unexpected outcomes, and makes it responsible for error reporting, tests and so on, for things that are nothing to do with email. Also, in the most common use case (1 attachment), it adds more code than it saves.

**Comment by Synchro** [comment]
One thing - you shouldn't have to add things like this directly to PHPMailer at all; subclass it in your own code and add it there. That way you won't have to do it again when PHPMailer gets updated.
