### ISSUE TITLE
Validate an email address before send

### ISSUE THREAD

**Issue by felloz** [PHPMailer/PHPMailer#1770]
Hello,

Im trying to send multiples email with phpmailer but when a wrong email address appear in the array the code stops and dont send the rest of emails.

Im trying to use this code to validate the email:

`if(PHPMailer::validateAddress($to)){
		   if(!$mail->send()){
				 throw new Exception("Error al enviar: " . $mail->ErrorInfo);
			 }else{
			 return 1;
		   echo 'Message has been sent';
		}
	}else{
		//whaever
	}`

But this email for example "-email@domain.com" its wrong but the validation wont detected, i also used `if(filter_var($to, FILTER_VALIDATE_EMAIL)` but don't detect the wrong email, so he try it to send it, sends an error and the sends stops, any solution for this please? any help is appreciated.

**Comment by Synchro** [comment]
It validates because `-email@domain.com` *is* a valid address. It's true that this pattern is unusual, but that doesn't make it invalid. If you have found an implementation (e.g. a mail server) that rejects messages of this pattern, you could report it as a bug there. If you want to reject such messages in your own code, you can inject your own validator into PHPMailer. Look at the code for [an example of how to do this](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1227).
