### ISSUE TITLE
"220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail." using godaddy SMTP Settings. Mail sent but never received.

### ISSUE THREAD

**Issue by bchipre** [PHPMailer/PHPMailer#1781]
I am a newbie to PHPMailer. I am using GoDaddy SMTP Settings received from GoDaddy support team whenever I run the PHPMailer code, I get a success message at the end of the debug, but the mail is never received at the other end. The most common error that always shows is "220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail." Find the code being used and the debug messages below : 

# Code to reproduce
   Attached

# Debug output
   Attached
[PHPMailer_Code_Used_on_Godaddy.txt](https://github.com/PHPMailer/PHPMailer/files/3395570/PHPMailer_Code_Used_on_Godaddy.txt)
[Debug Messages.txt](https://github.com/PHPMailer/PHPMailer/files/3395572/Debug.Messages.txt)

**Comment by bchipre** [comment]
Anybody who is using GoDaddy Server, can they help out by giving me the correct SMTP settings, MX used and an answer to why a mail sent from Gmail ID never reaches the official email for the web application hosted on GoDaddy?

**Comment by Synchro** [comment]
That 220 message is not an error; it's a "welcome" banner. While your message may be accepted by GoDaddy's mail servers, you can't use GoDaddy to send *from* a gmail address because it's forgery, and is not possible without breaking SPF and DMARC so it won't work. Having the correct GoDaddy mail server settings will not help that. Ultimately the solution is not to use GoDaddy. They are cheap in every sense.

**Comment by bchipre** [comment]
"To be clear - you can send an email via GoDaddy's servers, but you can't use a Gmail from address when doing so." Agreed, but when I have hosted my web app on GoDaddy, I do need to use GoDaddy server to redirect my emails using the 3rd party SMTP servers (say smtp.gmail.com) isnt it ? Also if u check my code the from address is xxxx@otes.in and not a gmail email address.

**Comment by Synchro** [comment]
Yes - GoDaddy won't let you use external mail servers at all.

You can make it work for your own domain if you add GoDaddy to your SPF record. Obviously you can't do that for gmail addresses because you can't alter gmail's SPF.

**Comment by bchipre** [comment]
So I need to update my SPF in GoDaddy account? Am I Right? currently using this SPF in GoDaddy: v=spf1 a mx ptr include:secureserver.net ~al

**Comment by Synchro** [comment]
That looks about right (apart from the missing `l` off the end). Only you can tell if it works.

**Comment by bchipre** [comment]
Thanks @Synchro, that was a great help! Will try to figure out the best SPF that can be used and reply here.

**Comment by mp3downloader1** [comment]
Just to let you knnow that Godday's servers are blacklisted on alot of sites. Its pointless to use Godaddy to send emails. Receiving them its ok. Godaddy has been blacklisted from alot of company's for allowing their users to spam left and right. Godaddy will play stupid about this because they know exactly what is going on. They will make every single kind of excuse to hide the facts. So if you cant sent any emails via a Godaddy SMTP is because of them. All sites are routed to their own stmp servers. So even if you have smpt.xxx.com is really smtp.godaddyisapos.com
