### ISSUE TITLE
stalled while opening a SMTP session

### ISSUE THREAD

**Issue by vjardin** [PHPMailer/PHPMailer#1828]
I am facing a SMTP server that does not send any message on the TCP socket. So, this first get_lines() keep waiting and we never proceed with sending the payload. If we comment this line:

https://github.com/PHPMailer/PHPMailer/blob/2d1ab8e07c2dbc9c36bddf78df1271f84e400660/src/SMTP.php#L373

then it works fine.

Should we add a SMTP->dontwait_firstline = true ; // default is false ?
so we can support such behaviours ?

**Comment by Synchro** [comment]
This is a common request, but unfortunately not possible because it’s part of the SMTP spec, and is commonly used as an anti-spam measure called “greetdelay”. The idea is that well-behaved clients will wait for up to the 10 minutes that the spec permits, but poor-quality spam scripts will not. Have you tried waiting for more than 10 mins?

It’s odd that it does work if you don’t wait, and suggests the server may be poorly implemented or heavily loaded.

An effective workaround would be to run a local mail server that you can submit to quickly, and will then do the waiting for you.

**Comment by vjardin** [comment]
Unfortunately, running a local SMTP is not an option.

Yes, once the timeout expires, the email is sent, but it is not a viable solution. Should you be open, I can provide a patch / pull request that allows to skip the waiting for the 1st line. By default, it should be off, but it would allow to support such broken SMTP.

**Comment by Synchro** [comment]
The reason that PHPMailer sticks to the RFC is because [not doing so caused problems in the past](https://github.com/PHPMailer/PHPMailer/issues/104#issuecomment-24313920).

I'd recommend that you implement it as a subclass - that's exactly why all this stuff can be overridden, to deal with non-standard local exceptions, and you can do that without having to edit the library source or give up the ability to update easily. I'd also recommend that you have a word with the admins of the mail server you use, or use one that's not broken.
