### ISSUE TITLE
SMTP: mails are sent despite exceptions

### ISSUE THREAD

**Issue by mhchem** [PHPMailer/PHPMailer#1858]
I am not sure the SMTP logic is right. It caused spam for my recipients.

My script is trying to send a mass mail divided into 20 individual mails to 5 recipients each. On exceptions, it waits, retries later and gives up after a couple of attempts. My assumption was, that not much could go wrong with this approach, but switching to SMTP caused spam. The reason is that the send command will not abort sending if one or more recipients fail.

In my scenario, there is a very low rate limit for emails. So, when there are 2 slots free, 2 recipients will be okay, 3 will fail. In contrast to my local mail client, PHPMailer will send the mail to the 2 allowed recipients nevertheless and throw an exception afterwards. https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1878 My script will detect an exception and retry the mail later. Assuming that the rate limit raised to 3 free slots during the waiting time, then the first recipient will get the mail a second time, but the mail as a whole will still fail. So my script waits and retries later until, finally, 5 emails are allowed through. In the meantime, the first recipient got the same mail multiple times.

I understand that some people want to send an email even if there are some invalid addressed (#139). However, I still believe that my simple logic "if there is an exception, try again later" was not wrong. This is how mail() works, isn't it?

My preferred solution would be an option for SMTP that is also included in the examples. Like

```php
    //Whether to send the mail when some recipients are rejected by the SMTP server
    $mail->SMTPSendIfRejectedRecipients = true;
```

**Comment by Synchro** [comment]
`mail()` is unlikely to fail because of things like unknown recipients because it relays through localhost, and so it doesn't know at that point.

Overall, for bulk sending, I'd recommend never sending messages to multiple recipients; always send each message individually. For queuing, *always* relay through a local/nearby mail server; don't roll your own queue in PHP, because it will be much, much worse at it - for example the problem you're seeing now would be completely solved by using a mail server for what it's good at (e.g. throttling to cope with low rate limits) without you having to write any new code at all.

**Comment by mhchem** [comment]
This isn't about unknown recipients, but about rate limits of my webhosting provider (which is at a ridiculous 50 mail recipients per hour).

`mail()` does indeed fail when I run into the rate limit.

What do you mean by "For queuing, always relay through a local/nearby mail server"? This is exactly what I do. I don't know any mail servers that accepts unlimited mail, without a rate limit.

Yes, I worked around the limit by sending one mail per recipient. Nevertheless, I found PHPMailer's behaviour unexpected (sending the mail partially while throwing Exceptions) and wanted to contribute to improve PHPMailer and prevent others from running into the same issues as I did.

**Comment by Synchro** [comment]
If mail() or sendmail fails, it suggests that you're on shared hosting, which is pretty much a worst-case scenario.

Run your own mail server (i.e. one _you_ control, not your ISP), set its _outbound_ limit to 50 messages/hour (relaying through your ISP's mail server), then you can send *into* it as fast as you like, and it will deal with the difference via its queue. This is what mail servers are for - reinventing them in PHP is a lot of work.

I get what you're saying about the failure modes, and I'm inclined to agree that the current behaviour is odd - but your fastest way to work around it is to subclass PHPMailer and override the `smtpSend()` method, changing:

        // Only send the DATA command if we have viable recipients
        if ((count($this->all_recipients) > count($bad_rcpt)) and !$this->smtp->data($header . $body)) {
            throw new Exception($this->lang('data_not_accepted'), self::STOP_CRITICAL);
        }

to

        // Only send the DATA command if we have viable recipients
        if ((!count($this->all_recipients) or count($bad_rcpt)) and !$this->smtp->data($header . $body))             throw new Exception($this->lang('data_not_accepted'), self::STOP_CRITICAL);
        }

That will change the behaviour to fail without sending anything if you either have no recipients, or there are any errors in `RCPT TO` commands.

If your limit is recipients rather than messages, I'd really recommend sending one at a time. Beyond that, look for a better hosting provider.
