### ISSUE TITLE
Attach multiple files without an html form?

### ISSUE THREAD

**Issue by jamminjames** [PHPMailer/PHPMailer#1899]
I've seen the solution for attaching multiple files that was posted, but it involves an html form. How can this be done without that? 

I know what files I want to upload and send via email, and they are on the server. I don't need to pick files in a form.

Also, is there any way in PHPMailer of attaching a simple array of files?

**Comment by Synchro** [comment]
Not directly, because that's not what PHPMailer is for - traversing directories is not its responsibility. It does however provide you with the one function you *do* need to attach a single file: `addAttachment`. So iterate over your directory using whatever [PHP-native](https://www.php.net/manual/en/class.directoryiterator.php) or [external library function](https://packagist.org/packages/league/flysystem) you like, and call `addAttachment` for each file.

**Comment by jamminjames** [comment]
Excellent, thank you! I knew it had to be simple, but couldn't find anything on attaching multiple files when using PHPMailer, other than the uploading of files via html form. Is it discussed here somewhere that I missed?

**Comment by Synchro** [comment]
It doesn’t really need to be because it’s all the same thing. With a form submission it has to preprocess the uploads first, but ultimately it’s then just attaching a bunch of files from a folder. If you already have the files, you can skip the first part.

**Comment by jamminjames** [comment]
Even so, I think it would be, for relative newbies like me, a good thing to give an example of this as well. Thanks again!

**Comment by Synchro** [comment]
Well, now there is one, in this ticket, for others to find. There's no more to it than that.

**Comment by jamminjames** [comment]
Glad I could help!  ;)
