### ISSUE TITLE
RFC: add X header to output signing problems

### ISSUE THREAD

**Issue by XL-2000** [PHPMailer/PHPMailer#1918]
Since there are many issues reported due to ill configuration of signing, it might be helpful to add some pre-checks during the signing routine and to add a header "X" header indicating problems, in such a way that it is helpful for the developer but not exposing any security details.
Since these headers show up in spam testing reports, even when debug is not active on the server running PHPMailer, it will give an indication

**Comment by vasylmaksym** [comment]
test

**Comment by Synchro** [comment]
This sounds like it has much in common with what is provided in the optional `z` tag of DKIM (which shows the original header values included in the DKIM signature), which PHPMailer supports.

DKIM *signing* failures (as opposed to verification issues) currently fail silently (e.g. if the private key is inaccessible), and that is something that should be fixed in a future version, though it necessarily entails a BC break.

DKIM signing is extremely tricky given PHPMailer's haphazard internal representation of headers, and this is partly why I've been working on DKIM Validator as it will allow much more thorough testing (and thus bug detection) around DKIM.
