### ISSUE TITLE
PHPMailer not sending messages from android 

### ISSUE THREAD

**Issue by DonRod90s** [PHPMailer/PHPMailer#1921]
Hi, I have a question regarding an issue sending emails from a smartphone. Usually, when I send emails from the desktop it works fine however when I send it from the phone, it keeps sending forever without actually sending. Below my code:

```php
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;
require 'phpmailer/src/PHPMailer.php';
require 'phpmailer/src/SMTP.php';
require 'phpmailer/src/Exception.php';


$useExceptions = true;
$mail = new PHPMailer( $useExceptions );
$mail->IsHTML(true);
$mail->IsSMTP();
$mail->CharSet = 'UTF-8';
$mail->SMTPDebug = 0;
$mail->SMTPAuth = TRUE;
$mail->SMTPOptions = ['ssl'=> ['allow_self_signed' => true]];
$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
$mail->Port     = 587;  
$mail->Username = "mail@one.com";
$mail->Password = "*********";
$mail->Host     = "send.one.com";
$mail->Mailer   = "smtp";
$mail->From     = "mail@one.com";
$mail->FromName = ($_POST["userName"]);
$mail->AddReplyTo($_POST["userEmail"], $_POST["userName"]);
$mail->AddAddress("mail@one.com");
$mail->Subject = $_POST["subject"];
$mail->WordWrap   = 80;
$mail->MsgHTML = ($_POST["content"]) . ($_POST["content2"]);
$mail->Body = "<body style='border:1px solid #19282B; margin:0px; box-sizing:border-box; padding:10px 20px; '> <h4 style='color:#19282B; font-size:18px;'>Nombre del Aplicante:</h4> <p style='color:#19282B;font-size:17px;'>" . ($_POST["userName"]) . " </p><br><h4 style='color:#19282B; font-size:18px;'>Email del Aplicante:</h4> <p style='color:#19282B;font-size:17px;'>" . ($_POST["userEmail"]) . "</p><br><h4 style='color:#19282B; font-size:18px;'>Numero Telefonico del aplicante:</h4> <p style='color:#19282B;font-size:17px;'>" . ($_POST["userNumber"]) . "</p><br><h4 style='color:#19282B; font-size:18px;'>" . ($_POST["firstQuestion"]) . ":</h4> <p style='color:#19282B;font-size:17px;'> " . ($_POST["content"]) . "</p><br><h4 style='color:#19282B; font-size:18px;'>" . ($_POST["secondQuestion"]) . ":</h4> <p style='color:#19282B;font-size:17px;'>" . ($_POST["content2"]) . "</p> </body>";


if(is_array($_FILES)) {
$mail->AddAttachment($_FILES['attachmentFile']['tmp_name'],$_FILES['attachmentFile']['name']); 
}





if(!$mail->Send()) {
  echo "<p class='error'>Problem in Sending Mail.</p>";
} else {
  echo "<p class='success'>Contact Mail Sent.</p>";
} 
?>
```

**Comment by Synchro** [comment]
PHPMailer doesn't know or care what you're sending from, so I doubt that's the problem. You are doing some other things wrong though.

There is no such property as `MsgHTML`, though there is a *method* called `msgHTML()`, which is a convenience function that sets the `Body` property, and also generates a plain-text `AltBody` and applies some filtering to image and data URLs – so you shouldn't be calling it *as well as* setting the `Body` property afterwards.

You're passing data from `$_FILES` directly to `addAttachment()`; that's not safe. Look at the [send file upload example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/send_file_upload.phps) for how to do it correctly.

You have no debug output enabled, so you're getting no info about what's going on at the SMTP level, if anything at all; try setting `$mail->SMTPDebug = SMTP::DEBUG_CONNECTION;`.

While you are checking the return value from `send()`, it may be worth showing what's in `$mail->Errorinfo`. That said, you will never reach that point because you've enabled exceptions, but you have not wrapped your code in a try/catch block, so any exceptions thrown will cause an immediate exit.

Overall it looks like you have copied code from a very old example - are you running the latest version of PHPMailer?
