### ISSUE TITLE
Redirect Return Path to a single mailbox

### ISSUE THREAD

**Issue by felloz** [PHPMailer/PHPMailer#1931]
Hello Im using the attribute

`$mail->ReturnPath = "mailbox@domain.com"`

To recive all bounces in that mailbox it donsent matter who sent, but is not working, it keeps the sender. Any way to fix this? 

Im using PowerMTA as mail server.

Thank you!

**Comment by Synchro** [comment]
There is no such property as `ReturnPath` in PHPMailer, so this code will do nothing. This is because setting a Return Path header in a message is a job for *the receiving server*, not the sender (i.e. your script). You can however control it _indirectly_, as the receiving server creates the Return Path header from the SMTP envelope sender (the address used with the SMTP `MAIL FROM` command), and you can set that from PHPMailer by setting the `Sender` property instead:

    $mail->Sender = "mailbox@domain.com"

You may also want to look into [VERP addressing](http://cr.yp.to/proto/verp.txt) if you're interested in using return path as a bounce control mechanism.

**Comment by Power-MTA** [comment]
🙌🙌🙌 latest version powermta / pmta available with lifetime license key.
+ another tools available
Skype: salimrezabd04
Telegram: salimrezabd
Telegram: salimrezabd1

**Comment by crishbenopol** [comment]
latest version powermta with lifetime license key  available ( NB: powermta enterprise and powermta standard both available without/with snmp,api supported  ).
powermta 4.0r* almost all version/revison
powermta 4.5r* almost all version/revison
powermta 5.0r* almost all version/revison
powermta 5.5r* almost all version/revison
powermta 6.0r* almost released all version/revison
          📩
[Contact Here...](https://pook.uk/T1CLpGo)
or
<img width="641" height="666" alt="GithubQR" src="https://gist.github.com/user-attachments/assets/207df664-29c2-43f2-a323-13969284fd3d" />
