### ISSUE TITLE
q-coding in addCustomHeader with List-Unsubscribe link still an issue

### ISSUE THREAD

**Issue by aliashafi** [PHPMailer/PHPMailer#1953]
Please check these things before submitting your issue:

- [ ] *Read the error message* you're seeing - it often tells you what is wrong, and may contain useful links & instructions
- [x] Make sure you're using the latest version of PHPMailer
- [ ] Check that your problem is not dealt with in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting), especially if you're having problems connecting to Gmail or GoDaddy
- [ ] Include sufficient code to reproduce your problem
- [ ] If you're having an SMTP issue, include the debug output generated with `SMTPDebug = 2` set
- [ ] If you have a question about how to use PHPMailer (rather than reporting a bug in it), tag a question on Stack Overflow with `phpmailer`, but [**search first**](http://stackoverflow.com/questions/tagged/phpmailer)!

# Problem description
q coding for custom header link is still a problem in 6.1.4. I just downloaded the latest version of PHPMailer and am running into the same issue as this stack overflow post here: https://stackoverflow.com/questions/59211047/q-coding-in-addcustomheader-with-list-unsubscribe-link. 

# Code to reproduce
```
$mail->AddCustomHeader("List-Unsubscribe: <{$_ENV["web_url"]}/unsubscribe-email?email=$to>, <mailto:unsubscribe@irl.com?subject=unsubscribe>");
```

# Debug output
Output looks like this: 
```
List-Unsubscribe: =?us-ascii?Q?<https://dev-web-master.irl.com//unsubscribe-em?=
 =?us-ascii?Q?ail=3Femail=3Dalia.shafi.c@gmail.com>,_<mailto:?=
 =?us-ascii?Q?unsubscribe@irl.com=3Fsubject=3Dunsubscribe>?=

```
Is there a workaround to decode the qencoding? 

Thanks so much!

**Comment by Synchro** [comment]
The problem is that PHP's `mail()` function corrupts headers over 65 characters - so you have a choice of valid wrapping (which causes trouble in some mailers), or corrupted headers (which causes trouble in some mailers). Not a great choice I agree – but you can avoid it by using SMTP to localhost instead which does not corrupt the headers, and doesn't apply wrapping until you hit 998 chars. Just add a call to `isSMTP()` and it will normally work with your local mail server without any other changes.

**Comment by aliashafi** [comment]
Thank you @Synchro !
