### ISSUE TITLE
addStringAttachment and AddEmbeddedImage can be used at same time.

### ISSUE THREAD

**Issue by sikuder** [PHPMailer/PHPMailer#1991]
Hello creator!

I have my problem when i use phpmailer library, can we use "AddEmbeddedImage" and "addStringAttachment" at the same time? i have try that, but after i received email from my test before, i only get "attachments" and i dont know "AddEmbeddedImage" is used or not.

If this bug, let admin know, and fixing it.

Thank you, sorry for my bad english.~

**Comment by emmanuel-deloget** [comment]
Hello, there is no conceptual difference between any kind of attachment. So it should be possible to use any of `addAttachment()` , `addStringAttachment()`, `addEmbeddedImage()` and `addStringEmbeddedImage()` and get the same exact mail. 

Unfortunately this is not true in practice because of what I would consider a bug in `addStringAttachement()` which sets the cid to 0 (`$attachment[7]`) even if the `$disposition` is set to 'inline' (hence the PR#2053).

**Comment by Synchro** [comment]
That's unrelated to the issue reported here. While it's true that it should not set the CID to 0, I think the bug is allowing the disposition to be set at all. If you want attachments, use the `Attachment` methods, if you want inline, use the `EmbeddedImage` methods; that's the intention.
