### ISSUE TITLE
Bangla translation

### ISSUE THREAD

**Issue by kklepper** [PHPMailer/PHPMailer#2010]
With Microsoft translate, I made a Bangla translation. Also I have a local repository:
```
docker@boot2docker:/c/wp/ci/application/libraries/PHPMailer$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        language/phpmailer.lang-bn.php

nothing added to commit but untracked files present (use "git add" to track)
```
If you are interested in merging this file, what do I have to do?

**Comment by Maikuolan** [comment]
Hi @kklepper,

(Forewarning: I'm just another user, like you. I'm not a maintainer. So, my reply is not authoritative).

There doesn't seem to be anything specifically about translations included in the contributor guidelines for PHPMailer, and nothing official about that as far as I'm aware, but based on process and experiences of previous translations done for PHPMailer by other users (you can check the commit history on existing translations to determine who contributed them and to determine which specific pull requests brought those translations in, taking a look at those commits and pull requests as examples), I think that all you'll need to do is create a file for your new translations, `language/phpmailer.lang-bn.php` (`bn` being the *ISO 639-1* language code for Bangla/Bengali), commit it to a branch at your fork, then send a new pull request for that branch to the PHPMailer master branch for the new translations to be merged in. :-)

If nobody responds to your pull request after a while, you could try tagging Synchro to let him know about it so that he can take a look at it.

**Comment by Synchro** [comment]
I was hesitating on this PR because it seems a little gratuitous – anyone can pipe text through an online translator, and the results are often wildly inaccurate, so it doesn't add very much. If the author is a native speaker (I have no idea if they are, but I'm certainly not!), then they can obviously improve the text, but I've not got anything to go on here.

Adding translations like this is historically something that's been very popular amongst students in the past – they are on a mission (possibly a homework assignment) to have a PR *of any kind* accepted regardless of whether it's worthwhile or not.

A third matter is the role that these translations play in PHPMailer - these error messages are typically only ever shown to developers, so the technical reasons and detail behind the message (which are not translated) are usually far more useful and important that the text of the error messages themselves.

**Comment by Maikuolan** [comment]
Good points, and I completely agree. :-)

Although I also don't know the author, and so, can't speak for them, mentioning "Microsoft translate" does imply not being a native speaker IMO, so, assuming they don't otherwise clarify that point, probably not a native speaker.

**Comment by kklepper** [comment]
I needed this for my project and I hoped a native speaker would check it. If not, it is ok for me until I meet a native speaker some day.
