### ISSUE TITLE
Use TLS without SMTP

### ISSUE THREAD

**Issue by mridah** [PHPMailer/PHPMailer#2032]
Hi,

I am sending emails using the `mail()` PHP function. All the examples of security/TLS I've seen use SMTP.

Is there a way to use TLS without using SMTP ? While using the normal mail() function ? @Synchro @fbonzon

**Comment by NiklasBr** [comment]
Just to be clear, are you using [PHP's mail() function](https://www.php.net/manual/en/function.mail.php) or PHPMailer's mail()? This one:

https://github.com/PHPMailer/PHPMailer/blob/a12c95eb53f84ccaf145a4d892c9964c5916f653/src/SMTP.php#L828-L849

**Comment by mridah** [comment]
Hi @NiklasBr , I'm using PHPMailer's default mail function. I said `PHP mail()` since I read somewhere that mailer uses that by default.

This is my current code:

    $this->$mail = new PHPMailer();
    $this->$mail->setFrom('....');
    $this->$mail->addReplyTo('...');
    ...
    ...
    if(!$this->$mail->send()) {
          echo 'Message could not be sent.';
          echo 'Mailer Error: ' . $this->$mail->ErrorInfo;
    } else {
          echo 'Message has been sent';
    }

**Comment by NiklasBr** [comment]
`$this->$mail...` is an odd pattern, are you sure you didn't attempt to write `$this->mail...`?

**Comment by mridah** [comment]
@NiklasBr currently I'm using `$this->$mail` but I meant the same thing.

I didn't know that it works without the `$`

**Comment by Synchro** [comment]
To answer the original question, no you can't use TLS without using SMTP. TLS only applies to network connections, and calling a local sendmail binary via a shell (which is what PHP's `mail()` function does) does not involve a network connection. Note that this is not a security issue because the traffic between PHP and the local mail server is never visible to the outside world, so it doesn't matter that it's not encrypted.

That said, `mail()` has several problems, and since all it actually does it open a synchronous connection to localhost and talk SMTP over it, it's both faster and safer to use SMTP to localhost from PHPMailer, which is why all the PHPMailer examples go that way. Note that you can't use TLS for that either because you can't get a certificate issued for `localhost`, plus its pointless as the traffic never leaves the server and thus doesn't need encrypting.

**Comment by Synchro** [comment]
> I didn't know that it works without the $

It's not so much that it "works without the `$`", but that it means something different. `$this->mail` means "the `mail` property of the current object", whereas `$this->$mail` means "the property of the current object whose name is stored in the `$mail` variable". So if `$mail = 'mail'`, they mean the same thing, but it's more likely that this is a mistake on your part.

**Comment by mridah** [comment]
@Synchro thanks for info. Basically I don't want this red flag that the message isn't encrypted.

[like the one here](https://i.stack.imgur.com/sfDyu.jpg)

So, if I setup a local SMTP server on postfix, and use that for SMTP with TLS, that will work, right ?

**Comment by Synchro** [comment]
As I said, you can't encrypt the connection to localhost, but anything reporting that should be clever enough to see that, so I recommend you just give it a try. You need to ensure that your postfix config is set to use TLS for outbound messages.
