### ISSUE TITLE
Accepting = (equals) as valid Character in E-Mail Address

### ISSUE THREAD

**Issue by wurschmedia** [PHPMailer/PHPMailer#2035]
In Line 1726 of phpMailer.php you should accept = as valid E-Mail character since it is per definition.

I had issues with that, cause some bouncer scripts from E-Mail providers use it to set envelope headers with "=" in the address for coding return paths.

**Comment by Synchro** [comment]
There are quite a few characters that are valid in email addresses that are dangerous or ambiguous in shell commands or arguments that may need escaping, and that is what that function attempts to avoid. That function *only* applies when you're using `mail()` as your transport since it's the only mechanism that requires shell escaping. Using `mail()` is a bad idea for [several reasons](https://exploitbox.io/paper/Pwning-PHP-Mail-Function-For-Fun-And-RCE.html), but you're much better off simply avoiding it by using SMTP to localhost instead - it's faster, safer, and does not run into this limitation.
