### ISSUE TITLE
date_default_timezone_set() behavoir

### ISSUE THREAD

**Issue by Colinax** [PHPMailer/PHPMailer#2036]
# Problem description

PHPMailers still use date_default_timezone_set('Etc/UTC'); and gmdate for time creation.

The PHP doc has Etc/UTC marked as old and not secure see: https://www.php.net/manual/en/timezones.others.php

The handling of the current date and time is set with date_default_timezone_set('Europe/Paris'); (and so on) but this change only works with date() and not with gmdate()

Or are there special reasons why this old behaviour is still used?

**Comment by Synchro** [comment]
There is no use of `Etc/UTC` in PHPMailer source code. There is in examples where it is used as a default, but that's all. UTC is used because it's a generic default - the examples recommend setting it to your local time zone, but it's important that PHP's time zone is set to *something* as PHP throws warnings on all date functions otherwise. For example, several examples say:

> //SMTP needs accurate times, and the PHP time zone MUST be set
> //This should be done in your php.ini, but this is how to do it if you don't have access to that

The only place `gmdate()` is used is in debug output because most servers and databases are set to UTC and timestamps in debug output will align with them, and again it's a generic default. Setting it to something like `Europe/Paris` would be opinionated and wrong in almost all cases.

**Comment by Colinax** [comment]
Okay, thanks for explaining
