### ISSUE TITLE
SMTPDebug = 2 is not giving descriptive debugging information

### ISSUE THREAD

**Issue by PolishedStaple** [PHPMailer/PHPMailer#2049]
In my PHP code, which uses Version 5.2.8, I have some of the following lines:

$mail->IsSMTP();
$mail->SMTPDebug = 2;
$singleErrorMessage = $mail->ErrorInfo;

But lately about 15% of all outgoing emails give me this error:

SMTP connect() failed.

Since I have "2" set for my SMTPDebug, does anyone know why my error message is so vague?  How can I better figure out why so many emails are failing?  The one guess I have is that the various ISPs are rejecting them because the recipients have not interacted with the emails other than occasionally "opening" them.

Thank you.

**Comment by Synchro** [comment]
SMTP debug output only happens when there is an SMTP connection. Your code is not getting that far; it's failing to connect _at all_, so there is no SMTP conversation to display. This is usually because your hosting provider is blocking outbound SMTP, so check with them. The PHPMailer troubleshooting guide tells you how to diagnose these kinds of problems.

Separately, upgrade **NOW**. Your code contains multiple public vulnerabilities, some of which are extremely severe.

**Comment by PolishedStaple** [comment]
Okay, I will work on upgrading today.  I have a VPS instead of shared hosting, so I'm fairly certain they are not blocking outbound SMTP.  Besides, if they were doing this, wouldn't every single email get this error when trying to be sent?

Thank you.
