### ISSUE TITLE
Unable to add ReturnPath

### ISSUE THREAD

**Issue by dhruvadeep** [PHPMailer/PHPMailer#2058]
PHPMAILER is not supporting ReturnPath option when i was testing for bounce back email. When sent to a wrong email it should have send a bounce back to the user but is not.

Followed this code

```$mail->ReturnPath("contact@dhruvadeep.dev");```

**Comment by Synchro** [comment]
Thats because it's not the sender's job to set a return path, and doing so is invalid and an RFC contravention, which is why PHPMailer doesn't do it, and you shouldn't try to. A return-path header is added *by the receiver*, and the address it uses is copied from the SMTP envelope sender provided in the `MAIL FROM` command that was used when the message was received.

You can specify an envelope sender by setting the `Sender` property in PHPMailer, though you should be aware of its implications for DKIM and DMARC:

    $mail->Sender = 'contact@dhruvadeep.dev';

**Comment by ivangomes** [comment]
@dhruvadeep  did you find a workaround for this?

**Comment by ivangomes** [comment]
I see! 

I use PHPMailer to send emails (notifications) from my web app.

$mail->setFrom(no-reply@example.com, 'Example'); // My system default email
$mail->addReplyTo('email A'); // User email address
$mail->addAddress('email B'); // Recipient

The issue starts when  **addAddress**  sets the auto-reply. The reply goes to **setFrom** instead of **addReplyto**.

in this case, the person sending the notification (addReplyTo), will not receive the auto-reply.

**Comment by Synchro** [comment]
OK, return-path has nothing to do with replies, it's where bounces go when a message fails to be delivered.

While you're doing this correctly, the problem isn't at your end, but at the receiver. Unfortunately there are no standards relating to autoresponders, and it's very common for them to behave badly. You can test this in better-behaved email clients – if you send your message to Apple Mail, gmail. Outlook, Thunderbird, etc, and reply to it in there, all will send to the reply-to address.
