### ISSUE TITLE
Sender address rejected: **Domain not found**

### ISSUE THREAD

**Issue by shahid1579** [PHPMailer/PHPMailer#2086]
I also tried to send it on my Email Address but still same issue.Any One here to help please
Message could not be sent.Mailer Error: SMTP Error: The following recipients failed: shahidghafoor007@gmail.com: : Sender address rejected: **Domain not found**

**Comment by Synchro** [comment]
You may be familiar with this meme:

> It’s not DNS
There’s no way it’s DNS
It was DNS

You need to fix your DNS.

**Comment by shahid1579** [comment]
@Synchro  When i use simple email function it works but while using PHPMailer it is not

**Comment by shahid1579** [comment]
If the issue was with DNS then why simple mail worked

**Comment by Synchro** [comment]
When you use PHP's built-in mail() function, no DNS is involved, because it submits directly to a local mail server. The onward delivery from there may fail, but you'll never find out about it in PHP.

When PHP does a lookup for a well-known domain like `gmail.com` and it fails, it is very, very unlikely that the domain itself is down; far more likely that you have a DNS problem on your server. You can easily test this by doing a lookup from elsewhere.

**Comment by shahid1579** [comment]
Thanks :)
