### ISSUE TITLE
PHPMailer->isSMTP()

### ISSUE THREAD

**Issue by samdoj** [PHPMailer/PHPMailer#2094]
`isSMTP()` name should probably be changed to `useSMTP()` .  `isX()` usually implies the function would return a boolean related to the named property and not be a side effect function.  Also, this function should be called automatically SMTPAuth is set to true.  I think this could easily be done with a magic __SET function. I'll take the ticket if you want me to contribute that.

**Comment by Synchro** [comment]
I like the isX convention too, but PHPMailer predates its existence, so this is mostly change for change's sake, and represents a BC break for no significant gain.

Your other idea isn't bad (as it's more likely to make things work as expected), but also I'm a bit wary of magic with invisible side effects. It would mean that all code examples (of which there are thousands, most of which I have no control over) don't make use of the feature, and you'd then have to find out what version people were using before you could guess at why their code doesn't work. Since I'm pretty much the only person answering PHPMailer questions on Stack Overflow, I don't want to contribute to my own workload!

Fundamentally PHPMailer is about legacy support; it's been around for 19 years, and Wordpress depends on it; It's taken Wordpress 3 years to get as far as upgrading to the current major version! There are other very capable email classes such as SwiftMailer (from Symfony) and Laminas_Mail that have a much more modern take than PHPMailer does, though they are fairly well-attached to their respective frameworks.
