### ISSUE TITLE
Adding Multiple Attachments to an Email: PHPMailer, Gmail

### ISSUE THREAD

**Issue by 5chu17sRyan** [PHPMailer/PHPMailer#2098]
I have only been able to attach one pdf to an email at a time. Could someone please help me to figure out how to add multiple attachments to email using PHPMailer? I initially tried just using multiple add attachment statements following each other like the following.

```php
$file1Name = $_FILES['myfile1']['name'];
$file1Path = $_FILES['myfile1']['tmp_name'];

$file2Name = $_FILES['myfile2']['name'];
$file2Path = $_FILES['myfile2']['tmp_name'];

$file3Name = $_FILES['myfile3']['name'];
$file3Path = $_FILES['myfile3']['tmp_name'];

$mail = new PHPMailer;
$mail->IsSMTP();

$mail->Host = 'smtp.gmail.com'; 
$mail->Port = '587';        
$mail->SMTPAuth = true;       
$mail->Username = 'email@gmail.com';     
$mail->Password = 'password';     
$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;     
//  . . .
$mail->Body = $mail_body;

$mail->addAttachment($file1Path, $file1Name);
$mail->addAttachment($file2Path, $file2Name);
$mail->addAttachment($file3Path, $file3Name);  

$mail->Send();
```

This didn’t work. After looking online I found that you can generally only add multiple attachments to an email when the attachments are received from a form input that allows for multiple submissions at a time https://phppot.com/php/send-email-with-multiple-attachments-using-php/. The files are stored together as an array and are attached by looping through the array. It is important to me to not retrieve the multiple files from one form input, so I do not like this option. I thought it might help if I stored the file information in arrays myself, but this also didn’t work.

```php
$fileNameArray = array($file1Name, $file2Name, $file3Name);
$filePathArray = array($file1Path, $file2Path, file3Path);
//  . . .
for($i = 0; $i < 3; $i++) {
	$mail->addAttachment($fileDataArray[$i], $fileNameArray[$i]);
}

$mail->Send();
```

Next, I tried a ‘dirty’ solution where I attempted to send multiple emails, each in reply to the previous one, that contained a single attachment. This also didn’t work. After the first email, no other attachments were included (still only one attachment was allowed). 

```php
$fileNameArray = array($file1Name, $file2Name, $file3Name);
$filePathArray = array($file1Path, $file2Path, file3Path);

for($i = 0; $i < 3; $i++) {
	$mail = new PHPMailer;
	$mail->IsSMTP();

	$mail->Host = 'smtp.gmail.com'; 
	$mail->Port = '587';        
	$mail->SMTPAuth = true;       
	$mail->Username = 'email@gmail.com';     
	$mail->Password = 'password';     
	$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;     
	//  . . .
	$mail->Body = $mail_body;

	$mail->addAttachment($filePathArray[$i], $fileNameArray[$i]);			
}
```

I’ve also looked through some fixes that involve editing the PHPMailer code. Both fixes have to do with the content-ID. I either couldn’t find the code that was being referenced for the fix or it seemed like, in the time since the fix was posted, PHPMailer was updated and the fix was implemented. 

* https://sourceforge.net/p/phpmailer/discussion/130418/thread/42bf5695/
* https://developer-paradize.blogspot.com/2015/02/how-to-fix-multiple-attachments-problem.html

I’m kind of lost at what to do at this point, if anyone knows how to add multiple attachments to an email using PHPMailer could you please help me? Your help is much appreciated, thank you.

**Comment by 5chu17sRyan** [comment]
Sorry that some of the code didn't turn out correctly in the post. I hope you can still get the gist.

**Comment by Synchro** [comment]
The threads you pointed at are years old!

The article about unique IDs is long obsolete, and I don't know that it was ever a problem; inline attachments with duplicate `cid` values will *still* be ignored, but that's expected behaviour, and only applies to inline attachments created using `addEmbeddedImage()` and `addStringEmbeddedImage()`.

The key problem here is that you're just not handling uploads properly. How you should handle uploads is covered [in the PHP docs](https://www.php.net/manual/en/features.file-upload.post-method.php), and all that occurs before PHPMailer has any involvement.

First of all, you need to understand how `file` inputs work. These determine what shows up in the `$_FILES` superglobal that PHP populates for you. You can either have multiple `file`-type inputs that select a single file each, or you can have [a single one that allows you to select multiple files](https://www.php.net/manual/en/features.file-upload.multiple.php). PHPMailer doesn't care either way, but *you* have to.

Next you need to make sure you use [`move_uploaded_file`](https://www.php.net/manual/en/function.move-uploaded-file.php) or at least [`is_uploaded_file`](https://www.php.net/manual/en/function.is-uploaded-file) in order to validate what's in the `$_FILES` superglobal, otherwise it's not safe.

Thirdly, you need to check whether the calls to `addAttachment()` are successful – at present you're just assuming they work and have no error checking at all.

So, I recommend you take a look at the [single](https://github.com/PHPMailer/PHPMailer/blob/master/examples/send_file_upload.phps) and [multiple](https://github.com/PHPMailer/PHPMailer/blob/master/examples/send_multiple_file_upload.phps) file upload examples, both of which do all of the above, and there are no known problems with adding multiple attachments.

**Comment by 5chu17sRyan** [comment]
Thank you for your help!  Sorry I couldn't find these examples on my own. I guess I didn't know what I needed to be looking for. 

If I post in the future regardless of whether it is here or on some other forum, would you recommend that I always include my error checking code? I purposefully removed it because I thought it would be extraneous information and get in the way of people trying to diagnose my problem.

Thanks again.

**Comment by Synchro** [comment]
OK - GitHub should have sent you an email with my response.

It's fairly important to show all your code if possible. If you're unsure where the problem is you may be removing the thing that you're doing wrong and we won't be able to tell. As I said though, I don't know of any issues with multiple attachments; they are checked in the test suite and work fine there. So I suspect the problems lie in your other code or system config (e.g. file permissions & ownership).

**Comment by 5chu17sRyan** [comment]
Is there any way to not use `<input name="userfile[]" type="file" multiple="multiple">` on the form? For what I'm working on, it would be better if the files were submitted separately.

`
<input type="file" name="myfile1"/>
<input type="file" name="myfile2"/>
<input type="file" name="myfile3"/>
`

This is so I can identify the files as "myfile1", "myfile2", and "myfile3"

Thank you again.

I wouldn't have known to use move_uploaded_file(), so that was particularly helpful.

**Comment by Synchro** [comment]
Sure, use multiple `file` inputs with different names, just as you have done. The only difference is how they are arranged in the `$_FILES` superglobal array when they arrive.
