### ISSUE TITLE
When gmail Daily user sending quota exceeded this time how to stop

### ISSUE THREAD

**Issue by atleds** [PHPMailer/PHPMailer#2113]
https://github.com/PHPMailer/PHPMailer/blob/e7acd3d92fa02728c51bf64b90615bffc84815f0/examples/smtp_check.phps#L50
When gmail id pass is ok but not send link this
2020-08-15 17:53:32 SERVER -> CLIENT: 550 5.4.5 Daily user sending quota exceeded. s5sm12197523qke.120 - gsmtp
How to i stop gmail?

**Comment by XL-2000** [comment]
How gmail handles quota is outside control of PHPMailer. Since gmail accepts the connection for sending, there is no more PHPMailer can verify. Also, this gmail message will only occur AFTER the email is taken in by gmail, so you can not control this beforehand. Only afterwards you could try to parse the response and search for therse occurences and prevent it a second time from happening (with this remark: how are you going to know when the quotum is OK again).

So this issue is not a PHPMailer thing to handle or solve

**Comment by Synchro** [comment]
This is indeed a limitation of gmail, however, you can detect this problem by looking at the error status after sending fails, for example:

```php
if (!$mail->send()) {
    $errors = $mail->getSMTPInstance()->getError();
    if ($errors['smtp_code'] === '5.4.5') {
        echo 'Quota exceeded';
    }
}
```

That `5.4.5` code is much like the 429 response code in HTTP. What you do with that information is up to you; it's a higher-level concern than PHPMailer can help with.

That said, you could maintain a counter of how many messages you have sent in the last 24h and throttle your deliveries via some kind of queueing system. Alternatively, relay through a local mail server (always a good idea anyway) and it will automatically queue this rejected message and try to send it again later without you having to do anything at all. Real mail servers are much better at this than anything you would want to write in PHP.
