### ISSUE TITLE
sending with PHP mail() doesn't check for an existing sendmail_from

### ISSUE THREAD

**Issue by NeotericSimian** [PHPMailer/PHPMailer#2170]
The code starts with if (!empty($this->Sender)...

but it should first check if there is a value set for sendmail_from otherwise it fails for a virtual user. Perhaps start with this:
        if (empty($this->Sender)) {
           $this->Sender = ini_get('sendmail_from');
        }
and then continue checking validity.

**Comment by Synchro** [comment]
I don't think this is needed. If `Sender` is not set, no `-f` param is created, and because no param is provided to `mail()`, it should fall back to using whatever is in `ini_get('sendmail_from')` without PHPMailer having to use it manually, i.e. exactly as would happen if you just called `mail()` yourself without using PHPMailer at all.
