### ISSUE TITLE
Spurious space in To header field

### ISSUE THREAD

**Issue by Hk1020** [PHPMailer/PHPMailer#2201]
# Problem description

I send mail to many recipients at once which creates a very long **To** header. The **To** header contains personal names so it looks something like
```
"Joe User" <joe.user@mailer.com>, "Another User" <another@ddress.com>
```

At around 900 characters there is a space in the email field so it reads similar to
```
"Joe User" <joe.user@mailer.com>, "Another User" <another@dd ress.com>
```

This causes the mail to be rejected by certain mailers which are more strict about rfc conformance. So some users get the mail while others don't.

In case it matters I am using `mail()` and phpmailer 6.1.8.

**Comment by Synchro** [comment]
It shouldn't be adding spaces, but it should be adding line folding on very long lines, and unfolding those will result in spaces being added. It's not possible to unfold those without adding spaces *unless* there are spaces available within the line, which in your case it sounds like there are.

Could you also check by using SMTP to localhost instead of `mail()` please?

**Comment by Hk1020** [comment]
I set up SMTP to localhost but I didn't actually try to send mail to the long list of recipients. I don't have a test list and I don't want to bother all the people with test mails at this point.

However, I tried to debug this locally with this piece of code
```
			// for debugging:
			$mail->preSend();
			$smessage = $mail->getSentMIMEMessage();
			echo $smessage;
````

In `$message` the `To` header does not contain the spurious space (neither with `mail()` nor with SMTP) but the personal names aren't quoted. Instead of
```` 
To: "Joe User" <joe.user@mailer.com>, "Another User" <another@ddress.com>
```` 
it reads
```
To: Joe User <joe.user@mailer.com>, Another User <another@ddress.com>
```
So this is not what I receive in my mail program. If I look there at the raw mail headers everything is quoted and there is this extra space.

**Comment by Synchro** [comment]
There have been problems before with `mail()` folding at much shorter line lengths than is necessary, on top of any folding that PHPMailer is doing already, so it may be `mail()` that's doing it, which is why I suggested trying SMTP to localhost. The important thing is to look at the raw headers in the received message, not just relying on how it looks in your mail client.

To test locally with SMTP without sending, [fake mail servers](https://github.com/PHPMailer/PHPMailer/tree/master/examples#about-testing-email-sending) work really well.

**Comment by Hk1020** [comment]
Yes I was looking at the raw headers.
