### ISSUE TITLE
Another FD_SETSIZE issue on PHP7.4 with PHPMailer 6.2.0

### ISSUE THREAD

**Issue by seehma** [PHPMailer/PHPMailer#2213]
Hi,
Iam sorry to post that here (again), but i have no idea where else i can get help. I found some issues here with previous PHPMailer and PHP versions. I also dont think that PHPMailer is the problem at all, but i hope i can get help here... 
My hosting provider is switching to PHP 7.4 (from 7.3) and my Application is working fine, except sending emails. 

On PHP 7.3 i have no problems with the same application (for now i can switch between PHP 7.3 and PHP7.4), i can send all Emails without any problems with PHPMailer. On PHP 7.4 the script which sends the mail hangs about 30minutes and then i sometimes get an error like this:
`Warning:  stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 1371.
 --enable-fd-setsize=2048 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date. in <b>/weirddirectory/PHPMailer/src/SMTP.php on line 1125`
When i pull out all the code of this script which is nested besides other files in my application sending is also fine on PHP 7.4.
I dont think that this problem is raised by PHPMailer, but i dont know whats the problem actually is.
Does anybody here know, that something has changed from PHP 7.3 to PHP 7.4 that could cause this problem?
What exactly is FD_SETSIZE and why does it have todo something with opening sockets?
Is there any advise i can give my hosting provider which could solve the problem, in fact raising fd_setsize is not an option. I got the feedback that he is hosting with redhat and this limit is actually fixed on that value and PHP takes it no mather which setting is used in php settings.

I found another problem on the web with wordpress, here was the solution to switch from PHPMailer to another Mailing Plugin, also on PHP 7.4 with a previously working application [https://wordpress.org/support/topic/plugin-cant-connect-to-smtp-after-install-wp-5-5/page/2/](url).

It would be great if anybody could give me some advice what todo, even if i have to change something in my application. I dont want to Change the Mailing Plugin because it works just fine :-).

Best Regards
M.

**Comment by Synchro** [comment]
"FD" stands for file descriptors, and is a limit on the number of file handles that PHP can open at the same time; being unixy, pretty much everything counts as a file, sockets included, and you just don't have enough of them available.
This value is set when PHP is compiled, so it will be that your PHP 7.3 and 7.4 are compiled with different values. RedHat is especially poor because it is super-conservative (by design), and only ever ships stock configs with minimal options; I would only host on RH if you're in some corporate environment where it's mandated.
I don't know what build you're using, and building your own can be annoyingly difficult, so you could try using a different build, for example the ones from [Ondřej Surý](https://launchpad.net/~ondrej/+archive/ubuntu/php?field.series_filter=focal), which are often better than the stock packages, however, those are only for Debian/Ubuntu, not RH or its derivatives – there are presumably equivalents for RH.
You saying you have no control over this suggests you're on shared hosting, which is a worst-case scenario; your PHP instance will be shared with many other users, and is very likely to be massively oversubscribed and under-resourced as it's also running everyone else's scripts. Either switch to a hosting provider that does a better job of shared hosting, or get your own server where you have full control. You can get your own complete VM for as little as $3/month, so it's not exactly expensive.
