### ISSUE TITLE
 Cannot declare class PHPMailer\PHPMailer\PHPMailer, because the name is already in use

### ISSUE THREAD

**Issue by FHeidger** [PHPMailer/PHPMailer#2221]
Hey,

I use your code in some of my wordpress-plugins. These plugins should work individually and together.
I included the files with require_once:
```html
require_once(plugin_dir_path( __FILE__ ) . 'PHPMailer-master/src/PHPMailer.php');
require_once(plugin_dir_path( __FILE__ ) . 'PHPMailer-master/src/SMTP.php');
require_once(plugin_dir_path( __FILE__ ) . 'PHPMailer-master/src/Exception.php');
```
By trying to activate the second plugin in the same site, I get the following error:
**Fatal error: Cannot declare class PHPMailer\PHPMailer\PHPMailer, because the name is already in use in /home/www/NEWSITE/wp-content/plugins/test-plugin-2/PHPMailer-master/src/PHPMailer.php on line 32**

How can I fix this problem? Actually with require_once this problem should be bypassed...
Thanks in advance.

**Comment by Synchro** [comment]
This will be because some other code is loading the same library from a different path; `require_once` only looks at paths, not class names. You should not need to bundle your own copy of PHPMailer because WordPress already includes it, and it's possible to get hold of an instance of it using [WordPress' `phpmailer_init` hook](https://developer.wordpress.org/reference/hooks/phpmailer_init/), like this:

```php
add_action( 'phpmailer_init', 'mailer_config', 10, 1);
function mailer_config(PHPMailer $mailer){
  $mailer->IsSMTP();
  $mailer->Host = "mail.telemar.it"; // your SMTP server
  $mailer->Port = 25;
  $mailer->SMTPDebug = 2; // write 0 if you don't want to see client/server communication in page
  $mailer->CharSet  = "utf-8";
}
```
