### ISSUE TITLE
Check if login works

### ISSUE THREAD

**Issue by uvulpos** [PHPMailer/PHPMailer#2222]
Hey there, 
I want to validate my login data if PHPMailer was successfully connected to SMTP server or not. Is there a way to do this? Maybe with `smtpConnect()`? If yes, could you please make a simple example? Maybe you should add this feature to your README 

~ Tim

**Comment by Synchro** [comment]
You could try using [the example that does exactly this](https://github.com/PHPMailer/PHPMailer/blob/master/examples/smtp_check.phps).

**Comment by uvulpos** [comment]
Sorry I haven't seen this example and I read the README, I read the PHPDocumentor and searched on Google. This should be more visible :)

**Comment by Synchro** [comment]
The readme points you at the examples folder, and the examples folder has its own readme that describes what each example does. Searching for "phpmailer smtp check" finds the example I pointed you at in the first few results. I don't know how much more obvious you want to make it. Adding more links to the readme is pointless because it will just get lost amongst all the other things in there, and what you're asking for specifically is not that common.
