### ISSUE TITLE
Move from phpdocumentor to Doctum

### ISSUE THREAD

**Issue by williamdes** [PHPMailer/PHPMailer#2230]
Hi,

Would you be open to move from phpdocumentor to [Doctum](https://github.com/code-lts/doctum#readme) ?

The current API docs seem deeply screwed: https://phpmailer.github.io/PHPMailer/index.html

Laravel uses [Doctum](https://github.com/code-lts/doctum#readme): https://laravel.com/api/5.8/

And by the way [Doctum](https://github.com/code-lts/doctum#readme) is the replacement for the abandoned Sami

**Comment by Synchro** [comment]
I've no particular attachment to phpDocumentor, but I don't think I'd describe the current generated docs as "deeply screwed", it's just how phpDocumentor generates them; they are still entirely usable.

I'd be happy to accept a PR if you can do something better.

**Comment by williamdes** [comment]
Hi, thank you for the response ;)
I might open a PR soon then

Well I can not use the documentation from my chrome :/
![image](https://user-images.githubusercontent.com/7784660/103315318-81fcb600-4a25-11eb-9c55-8c5fe317f73a.png)

**Comment by williamdes** [comment]
Edit: I found out how to use it 
http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.SMTP.html
OMG, this is not very intuitive (IMO)

**Comment by Synchro** [comment]
That's just how PHPDocumentor displays namespaces. If you don't like how it looks, I'd recommend you report it to them as it's nothing to do with this project. As far as I can see, it's not much different from the Laravel docs you pointed at, it's just that there's only one namespace and it doesn't have that hierarchical sidebar (possibly because there is no hierarchy to display). One complaint I do have about the generated docs is that items are shown in source order, not sorted alphabetically; there's probably a config option for that.
