### ISSUE TITLE
SMTP ERROR: Failed to connect to server: Conexión rehusada (111) in Phplist

### ISSUE THREAD

**Issue by kibalam** [PHPMailer/PHPMailer#2295]
Hello try send emails with phplist by 

`<?php 
define('PHPMAILERHOST', 'smtp.server.com:587');
$phpmailer_smtpuser = 'USER';
$phpmailer_smtppassword = 'PASSWORD';
define("PHPMAILER_SECURE",'tls');`

and add the smtpOptions 

SMTPOptions = array( 'ssl' => array(
                                    'verify_peer' => false,
                                    'verify_peer_name' => false,
                                    'allow_self_signed' => true));

the result is this. 

`2021-03-22 23:39:19 Connection: opening to smtp1.s.server.com:587, timeout=5, options=array ( 'ssl' => array ( 'verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true, ),)
2021-03-22 23:39:20 Connection failed. Error #2: stream_socket_client(): unable to connect to smtp1.s.server.com:587 (Conexión rehusada) [/home/xxxx/public_html/xxxx/lists/admin/PHPMailer6/src/SMTP.php line 375]
2021-03-22 23:39:20 SMTP ERROR: Failed to connect to server: Conexión rehusada (111)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting`

I don't  know whats is the problem, help me please. 

best regards 
Kibalam

**Comment by Synchro** [comment]
Looks like your hosting provider is blocking outbound SMTP. What happened when you tried the tests in the troubleshooting guide?

**Comment by DRRSchmidt** [comment]
I have the exact same problem. My provider is NOT blocking outbound SMTP, I have tried 4 different ports, I have tried without the Options, I verified that the external mail server is accessible and working, tried versions 6.1.0, 6.2.0 & 6.3.0 and I examined the code. Here is a stack trace: [13-Apr-2021 14:24:37 America/Denver] PHP Fatal error:  Uncaught exception 'PHPMailer\PHPMailer\Exception' with message 'SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting' in /home/****/php/PHPMailer/src/PHPMailer.php:1947
Stack trace:
#0 /home/****/php/PHPMailer/src/PHPMailer.php(1635): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Tue, 13 A...', 'Hi! How are you...')
#1 /home/****/php/PHPMailer/src/PHPMailer.php(1468): PHPMailer\PHPMailer\PHPMailer->postSend()
#2 /home/jobseek/public_html/smpt2go.php(41): PHPMailer\PHPMailer\PHPMailer->send()
#3 {main}
  thrown in /home/jobseek/php/PHPMailer/src/PHPMailer.php on line 1947

**Comment by Synchro** [comment]
So what happened when *you* tried the tests in the troubleshooting guide? What does *your* debug output show?

**Comment by acanqs** [comment]
I have similar(?) problem, but when running on PHP 5.6 (on some institutional hosting and I have no choice to set something different). The problem is when I instantiate \PHPMailer\PHPMailer\PHPMailer() - it takes around 1,3MB of memory and when I instantiate another object responsible for processing/preparing data to be send + script self "weight" - I end-up with "SMTP connect() failed" after standard 5 minutes. (Some tests and measures shows that exeeding 2MB of memory leads to the problem, but this limit can be hosting specific).
Interesting part is that - and it proves that there is no problem with smtp connection as is - when I run just simple script, with fixed "data" to be send (using PHPMailer of course) - everything goes well.
The second interesting part is that at my 'localhost' where I've got PHP of the 7th branch - instantiation of PHPMailer takes less than 100kB of memory (tested with the same scripts as those on the hosting).
I'll appreciate any hints on how to debug/squeeze/do what ever with the PHPMailer on a PHP 5.6 branch to limit memory usage.

Regards,
AC

**Comment by Synchro** [comment]
That's very weird, but interesting! I don't think it has anything to do with this ticket though, so I suggest you open a separate one.

**Comment by acanqs** [comment]
Yeah, I'll gain more data and will open a new ticket. I was influenced by stack trace provided by DRRSchmidt, in my case it looks very similar (method smtpConnect returned false, and the 'smtp_connect_failed' exception was thrown).

**Comment by Synchro** [comment]
Same ultimate failure message, but entirely different causes, as the stack traces and messages show. There are many ways that SMTP connections can fail; we have three examples just in this ticket! Detail counts!
