### ISSUE TITLE
Invalid address: (Sender) when the email address is greater than 78 characters

### ISSUE THREAD

**Issue by jlevitas16** [PHPMailer/PHPMailer#2316]
I am using version 6.4.0. (FYI, version 5.x worked fine - I recently upgraded to 6.2.0 - problem existed there - then updated to 6.4.0 and the problem persists)

Because I use VERP for processing bouncebacks, sometimes, the Sender email address is very long. In this case:
$mail->Sender = "wizbounce_9999_aedmunds=brandywineworkshop.com_2021-04-1614#30#24@wizathon.com";
The sender email address is 78 characters long. Anything less that 78 characters is fine. Anything greater than 78 characters produces this error:
Fatal error: Uncaught PHPMailer\PHPMailer\Exception: Invalid address: (Sender): wizbounce_9999_aedmunds=brandywineworkshop.com_2021-04-1614#30#24@wizathon.com in /var/www/clients/client1/web3/web/vendor/phpmailer/phpmailer/src/PHPMailer.php:1546 Stack trace: #0 /var/www/clients/client1/web3/web/vendor/phpmailer/phpmailer/src/PHPMailer.php(1464): PHPMailer\PHPMailer\PHPMailer->preSend() #1 /var/www/clients/client1/web3/web/testemail.php(99): PHPMailer\PHPMailer\PHPMailer->send() #2 /var/www/clients/client1/web3/web/testemail.php(10): send_Out() #3 {main} thrown in /var/www/clients/client1/web3/web/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 1546

**Comment by Synchro** [comment]
It's saying it's not a valid address because it is not a valid address according to [RFC5321](https://tools.ietf.org/html/rfc5321#section-4.5.3.1.1):

> The maximum total length of a user name or other local-part is 64 octets.

The fact that the old version allowed it was a bug which has been fixed. That said, 78 chars is still invalid, but that must be a bug in PHP itself as PHPMailer uses PHP's `filter_var` validator by default. While PHPMailer could be adjusted to allow it (or you could inject your own validator, which PHPMailer allows you to do already), doing so is a bad idea as while _you_ might want to break RFCs, the rest of the internet's mail infrastructure might have other ideas.

I use VERP addressing too, but without quite so much baggage!

The error you're showing also suggests that you have enabled exceptions, but have not provided a try/catch structure to deal with them.
