### ISSUE TITLE
SMTP connect() fail from crontab

### ISSUE THREAD

**Issue by Tioloco** [PHPMailer/PHPMailer#2354]
I have a php script that runs nightly via cron.

I can run the script from a browser and it functions perfectly, but when run from cron, it throws SMTP connect() fail.

require '../vendor/phpmailer/phpmailer/PHPMailerAutoload.php';
$mail = new PHPMailer; 
// $mail->SMTPDebug = 4;                              
$mail->SMTPDebug = SMTP::DEBUG_SERVER;         
$mail->isSMTP();                                
$mail->Host = 'localhost';            
$mail->SMTPAuth = true;                            
$mail->Username = '****@***';      
$mail->Password = '**********';              
$mail->SMTPSecure = 'tls';                    
$mail->Port = 587;                                 
$mail->setFrom('****@****', '**** Support');
$mail->isHTML(true);    
$body.="<p>Cron: util.test.cron.php is running</p>";
$mail->Subject="CRON Test!";
$mail->Body=$body;
$mail->addAddress('****@gmail.com', '*****');
$mail->send();
$mail->ClearAddresses();

I'm pretty tapped out on ideas to try, so any help would be appreciated.

**Comment by Synchro** [comment]
The first thing I spot there is that you're running an old version of PHPMailer, so update.

The usual difference when running from cron is that it's running as a different user that might not have permission/ownership for either the files that it runs, or the services/ports that it's using. You may also find that security frameworks like SELinux or AppArmor may prevent it from running – check your logs for that.

Other things I can spot here:

* You won't be able to use SMTPSecure when connecting to localhost because you'll get a certificate mismatch.
* Similarly, you probably don't need authentication when sending through localhost.
* You don't need `clearAddresses` if you're only sending one message per run. You also don't need `isHTML` for a simple text message like that.

**Comment by aleksandrmelnikov** [comment]
To piggyback on the solid previous response, I've also found my firewall blocking email going out.

Specifically, csf would block users or groups that were not whitelisted to send email.
