### ISSUE TITLE
New regex in isPermittedPath function doesn't allow S3 bucket URLs

### ISSUE THREAD

**Issue by manoj382** [PHPMailer/PHPMailer#2355]
https://github.com/PHPMailer/PHPMailer/blob/453159e95bab83bad683ba7835265ef8f4f4ada7/src/PHPMailer.php#L1817

I have some emails that go out from Wordpress through Gravity Forms and since the latest version of PHPMailer the files from my S3 bucket are no longer getting attached to the email. 

The log file shows this error:
`PHPMailer class returned an error message: Could not access file: s3://xxxxx`

I first contacted the Gravity Forms plugin developer, but later determined the plugin itself is fine and it's the regular expression being used in PHPMailer. 

Old regex, which I've confirmed works in attaching the S3 file if I revert the function to the previous version:
`#^[a-z]+://#i`

New regex, which does not:
`#^[a-z][a-z\d+.-]*://#i`

I'll be honest this is a bit out of my realm, but I think that is the issue. Any insight or suggestions would be greatly appreciated.

**Comment by Synchro** [comment]
This is due to a bug fix that also closed a major security hole. PHPMailer _deliberately_ avoids being a client for HTTP or other protocols for file attachments because it is far too risky. The solution is to take on responsibility for fetching remote files yourself. Instead of :

    $mail->addAttachment('s3://file.txt', 'file.txt');

Do this:

    $mail->addStringAttachment(file_get_contents('s3://file.txt'), 'file.txt');

This way it's _your_ code fetching the file, not PHPMailer's. That it worked previously was a bug.
