### ISSUE TITLE
Suggestions for potential improvements for `PHPMailer::setLanguage()`

### ISSUE THREAD

**Issue by jrfnl** [PHPMailer/PHPMailer#2418]
While writing tests for the logic involved in localizing the error messages, I came across a number of oddities which _may_ benefit from some tweaks to improve things.

**_Note: I'd be happy to make the changes I'm suggesting here. Just wanted to allow for discussion before sending in a PR._**

### Observation 1: Language code is case-sensitive
```php
// This works:
$mail->setLanguage('nl');

// This doesn't:
$mail->setLanguage('NL');
```

In a number of other places in the library, the code is very deliberately case-tolerant.

#### Proposal

It would only be a small tweak to make the `setLanguage()` method case-tolerant for the `$langCode` passed and may improve usability.

### Observation 2: ISO 639-1 multi-level: no fall back to "parent" language when available
```php
// This works:
$mail->setLanguage('nl');

// This doesn't:
$mail->setLanguage('nl_NL'); // "PHP" way of writing the code
$mail->setLanguage('nl-NL'); // Iso way of writing the code
```

For a few languages, there are multiple translation files available for variants of the language. For most languages this is not the case.

#### Proposal

When the `$langCode` is passed as "multi-level" and no translation is found for the specified variant, the localization currently falls back to English, while when a translation _is_ available in the "parent" language, it may be more appropriate to fall back to that translation.

So, when `nl_NL` would be passed, `nl` would be used when `nl_NL` can't be found and `nl` **is** available. The fall back to English would then only happen when neither `nl_NL` nor `nl` is available.

### Observation 3: ISO 639-1 multi-level: underscore versus dash

While for this library, underscore separators for multi-level language files are expected, the documentation talks about ISO 639-1 language codes, which, when multi-level, are expected to use a dash as separator.

#### Proposal

It would only be a small change to support both for the `$langCode` input, but again, may improve usability a little.

### Observation 4: Available language file `sr_latn` can never be used

There is a language file available for `sr_latn` (Serbian, latin script). However, this language code would never pass the regex validation of the `$langCode`, so this file is effectively useless.

#### Proposal

Either remove the translation file or adjust the regex to allow for loading it.

**Comment by Synchro** [comment]
The pattern for language file names is based on the pattern used for [POSIX locale names](https://docs.oracle.com/cd/E23824_01/html/E26033/glmbx.html) (for example `en_US.UTF-8`), which use a combination of ISO-639 for language code, and ISO-3166 for country code (the 2-character flavours of each). By convention, 639 codes are lower case and 3166 codes are upper case, so you end up with mixed case in locales, and this convention is referenced in [RFC5646](https://datatracker.ietf.org/doc/html/rfc5646#section-2.1.1). The only major difference between POSIX locales and that RFC is the use of underscores. In practice I've only ever seen locales expressed using underscores, so I'd prefer to keep them that way, plus changing that is a BC break.

You're quite right about the `sr_latn` case though. This is also unusual because `latn` is not a country code but a "variant" name. I found [a useful mention of that exact case](https://www.gnu.org/software/gettext/manual/html_node/Locale-Names.html), suggesting its full name should be `sr_RS@latin` to convey the language, country, and variant. The regex would need to be updated to allow that pattern though, and I think there is a Chinese language file that is also a variant. We could go ahead and adopt that convention, and we already have a mapping for renamed languages to avoid BC issues.

**Comment by jrfnl** [comment]
@Synchro Thanks for your response.

> By convention, 639 codes are lower case and 3166 codes are upper case, so you end up with mixed case in locales

Eh.. except that that convention is not adhered to in PHPMailer as, while the regex allows for lowercase only for the first two chars and both lowercase as well as uppercase for the second two chars, no translation is done for the file system and the language file filenames are all in lowercase, which means that whether or not something like `nl_NL` is supported would depend on whether the OS PHPMailer is being run on is case-sensitive for the file system (Mac, Linux) or not (Windows).

It also doesn't address my question about a code like `nl_NL` currently fall back to English instead of falling back to `nl`.

So what about:
* Don't support dashes, stick with only supporting underscores as separators.
* Allow for the complete language code to be in mixed case and doing a `strtolower()` before using it in the filename, with the filenames all being lowercase (as they already are).
* Adding logic to allow for the fall back from more specific language code `nl_NL` to the two letter language code `nl` and only falling back to English if neither exists.

Does that sound reasonable ?


> suggesting its full name should be `sr_RS@latin` to convey the language, country, and variant. 

As a language code that may work, however, we'd then need additional logic for the translation to file name as I don't think using `@` signs in file names is a good idea. Got some niggling feeling that that may cause issues depending on the OS/file system used.

**Comment by Synchro** [comment]
It really helps if I look at the thing I'm talking about, and not get it mixed up with something else!

Yes, that all sounds reasonable.

**Comment by jrfnl** [comment]
@Synchro No worries. Happens to the best of us ;-)

Looking into upgrading the code now.

While doing so, I also noticed that the return value of the method appears inconsistent:
* When a `$langCode` was matched against the regex, but the file couldn't be loaded, it is `false`.
* In all other cases, it will return `true`.

This means that when a language code was passed, but didn't match the regex, the function would return `true`, even though the requested language was not loaded and the method fell back to the English language strings.

This does match the docblock: _"Returns false if it cannot load the language file."_, but feels counter intuitive from an end-user perspective.

We also still need to figure something about for `sr_latn`.
Looking at this page from the POSIX specs: https://docs.oracle.com/cd/E23824_01/html/E26033/glset.html, it looks like it should be `sr_RS.UTF-8@latin` rather than `sr_RS@latin`, which would make things even more awkward.

Any ideas ? I'm starting to think that something like `sr.latin` might work and allowing for variants like `sr_rs.latin`. How does that sound ?

On the Posix locale name site I also saw a pattern using

**Comment by Synchro** [comment]
I agree that it should return false in all cases where it has failed to load a language file, doesn't make much sense otherwise.

We don't need the `UTF-8` part in the language code since we are always using UTF-8 for them; their charset doesn't have anything to do with the charset used in a message. TBH I don't think we need to do anything too clever for the languages; they are typically set once by developers and never looked at again. So long as they have some kind of vaguely sensible naming scheme we should be fine. They are actually somewhat redundant anyway as the messages are mostly only of interest to developers to start with; you don't want to be displaying detailed mail server errors to end users.

**Comment by jrfnl** [comment]
> So long as they have some kind of vaguely sensible naming scheme we should be fine. 

Which would be... ?

>  I'm starting to think that something like `sr.latin` might work and allowing for variants like `sr_rs.latin`

Or did you mean that this was okay ?

**Comment by Synchro** [comment]
Well, the scheme we have now is quite workable. We only have 3 languages out of 52 that even have variants, and only one of those is a country variant (`pt_br`). A change from `sr_latn` to `sr_rs.latin` doesn't really add anything useful, and it's a BC break (though we could use the renaming map) for anyone using it. BTW the choice of that suffix was not arbitrary – it came from [the Unicode standard](https://unicode-org.github.io/cldr-staging/charts/37/summary/sr_Latn.html) via [this commit](https://github.com/PHPMailer/PHPMailer/commit/a9a634274ee10990042dbcefb23c610085d49400).

**Comment by jrfnl** [comment]
@Synchro Sorry to keep bugging you about this, but it is still not clear to me what to do about it now.

1. IIRC two of the three are actually country variants - `zh_cn` is "Chinese, China", in contrast to, for instance `zh_tw` which would be "Chinese, Taiwan". I realize that the script used in that case will also be different (simplified vs traditional), but that has its own annotation if people want to be precise.
2. Renaming `sr_latn` would not constitute a BC-break as, as things stand, the file **_cannot_** and won't ever be loaded via `setLanguage().

Reading back this thread I can only conclude that there are a number of different standards on how to annotate language variants and that no clear choice has been made which one to adhere to support both country code and scripts.

If you want to support `sr_latn` as-is, it would mean making the regex "country" part more lenient òr allowing for a script variation between the language code and the country code, like so: `lang(_script)?(_country)?`.

Either way is fine with me, but I do need to know which.

**Comment by Synchro** [comment]
`lang(_script)?(_country)? would be a usable pattern, and it is compatible with what we already have. It would mean you can't tell whether a single suffix is a country or a script, but I don't really think it matters that much. Having fallbacks would be a nice improvement, but that can be done within the existing naming scheme, so it's only the regex and loading that needs to change.

Good point about 2! Suggests nobody is using it... This repo is a popular target for Hackfest PRs!
