### ISSUE TITLE
Content-ID header gets mangled

### ISSUE THREAD

**Issue by sebastianhelbig** [PHPMailer/PHPMailer#2437]
```
$contentId = '16258590485080.7800325544861049@content.messagingengine.com';
$mail->addStringEmbeddedImage(…, $contentId, …);
```
In mail body this is referenced with `<img src="cid:16258590485080.7800325544861049@content.messagingengine.com">` which is working fine.

Now when sending via PHPMailer the header gets set as 
`Content-ID: <=?us-ascii?Q?16258590485080.7800325544861049@content.messagi?=
 =?us-ascii?Q?ngengine.com?=>`
and the inline image won't be displayed.

The header should be
`Content-Id: <16258590485080.7800325544861049@content.messagingengine.com>`

**Comment by Synchro** [comment]
That's not mangled, it's just [RFC2047](https://datatracker.ietf.org/doc/html/rfc2047) encoded, and it is entirely correct. The best way to avoid this is not to send via mail() as the reason we have to use this encoding is that mail() sometimes forcibly wraps text incorrectly at a line length shorter than it should (which is proper, unrecoverable corruption), rather than just encoding that a faulty client doesn't handle.

**Comment by sebastianhelbig** [comment]
Obviously something is broken if mail clients won't display the inlined images anymore with this header.

**Comment by Synchro** [comment]
Right, so do what I suggested, or alternatively use shorter `cid` values which won't cause wrapping.

**Comment by sebastianhelbig** [comment]
It seems you have a strong opinion about this.

Imho RFC2047 does not apply to Content-ID headers as already only ascii chars are allowed there. The thing with `mail()` is obviously a bug in `mail()` and should be fixed there. It doesn't help to mangle the header here and no mail client will be able to use it, as no one is doing conversions in Content-ID header. This way information will be lost for the receiver.

But nevertheless, I am just using sendmail now as you proposed. So thank you. 👍

**Comment by Synchro** [comment]
I quite agree that it should be fixed in PHP, but meanwhile if this is not done, your header lines would have random line breaks inserted into them, which is essentially unfixable. The advantage that RFC2047 has is that it allows using line folding in a way that preserves header contents exactly.

FWIW PHPMailer copies Apple Mail's behaviour, in fact that's where the idea came from. I would recommend using SMTP to localhost instead of sendmail as it's faster, safer, and easier to debug.

**Comment by Synchro** [comment]
Just FYI, it's nothing to do with non-ASCII characters, but line length. You will notice that the RFC2047 encoding encodes the text as ASCII. The advantage of this approach is that it's then possible to fold a line at an arbitrary length without introducing spaces when it is unfolded. There is no other way of doing this that I'm aware of. If you have a specific rule that says "ignore all spaces in an unfolded line" (like the DKIM -Signature header does), then it's fine, but in the case of Content-ID which has no such provision, it just results in breakage.
