### ISSUE TITLE
setFrom() method does not replace Sender

### ISSUE THREAD

**Issue by arnisjuraga** [PHPMailer/PHPMailer#2458]
Please check these things before submitting your issue:

# Problem description
When I need to replace "From" address, I can re-set it with `->setFrom( $address, $name )` method.
But this does not replace "Sender" property  value:

# Code to reproduce

````php
var_dump( $mail->Sender );  //string(0) ""
$mail->setFrom('from@example.com', 'Mailer');
var_dump( $mail->From ); // string(16) "from@example.com"
var_dump( $mail->Sender ); // string(16) "from@example.com"

// now - set new From address:
$mail->setFrom('from@example1.com', 'Mailer1');
var_dump( $mail->From ); // string(17) "from@example1.com"

// Here - $mail->Sender is not replaced! 
var_dump ( $mail->Sender ); // string(16) "from@example.com"
```

This is a problem. Because some SMTP servers requires "Sender" value to match SMTP auth username or e-mail address. 
I need re-setting addresses in case smtp protocol.

**Comment by sanzeeb3** [comment]
Is that not how you make From and Sender different?

**Comment by Synchro** [comment]
`Sender` is only set via the `From` address if it is unset. If it already set, it will not be touched, because we can't tell if it's been set manually or automatically. If you need to set it to an explicit value, set it explicitly. Also, this seems like a real edge case – do you really want to authenticate as multiple different users within a single SMTP session?
