### ISSUE TITLE
Question: How to save HTML Version of Email

### ISSUE THREAD

**Issue by lehnerrobert** [PHPMailer/PHPMailer#2508]
Hi guys!
I want to save a replica of the sent email in a text file on my server to be able to 

- display emails with a "View online" link
- resend emails with the same content

Unfortunately, I cannot find a code snippet on the web, neither help in the wiki.

Would love to hear from you,
thank you very much!

**Comment by Synchro** [comment]
You need to be clear whether you want to display the message itself, or the content that you included in it; These are not the same things... For example, viewing the message itself would be like using gmail; displaying the content would be like "view online" in an email newsletter.

Either way, I suggest that you don't want to save the message itself, but save the component pieces you made it from so that you can reconstruct it. So in your example, I'd suggest you save the HTML of the message body; then you can display it directly for a "view online" view, or simply pass the same content to `Body` in PHPMailer to send it as a message.

**Comment by lehnerrobert** [comment]
@Synchro 
Thank you very much!
