### ISSUE TITLE
Problem with AddCC in PHPMailer

### ISSUE THREAD

**Issue by fmaccallini** [PHPMailer/PHPMailer#2509]
Hello everyone, I am trying to add an email with CC in PHPMailer with the following code:
$mail = new PHPMailer();
			$mail->IsSMTP();
			$mail->Host = 'xxx.com.ar';
			$mail->SMTPAuth = true;			
			$mail->Username = 'xxx@xxx.com.ar';
			$mail->Password = "xxxxx";
			$mail->SMTPSecure = 'ssl';
			$mail->Port = 465;
			$mail->From = 'xxx@xxx.com.ar';
			$mail->FromName = "xxxxx";
			$mail->CharSet = 'UTF-8';
			
			$mail->Subject = $Asunto;
			$mail->MsgHTML($cuerpo);			
			$mail->AddAddress($to, "");
			if($Replyto!=""){
				$mail->AddReplyTo($Replyto);
			}
			if($CC!=""){				
				$mail->AddCC($CC);
			}			
			if($Archivos!=""){
				$mail->AddAttachment($Archivos);
			}
			if(!$mail->Send()) {

If I use $mail-> AddCC ('name@mail.com'); it works fine but when putting $mail-> AddCC ($CC); It doesn't work for me, how can I solve the problem?
Thank you so much

**Comment by Synchro** [comment]
You're not doing anything wrong, but you need to double check what is actually in `$CC`, since you've not shown it here. You should also check the return value from `addCC` to be sure that the address you're giving it is considered valid.

Your code looks like it has been copied from a very old example, so make sure you're using the latest version of PHPMailer.
