### ISSUE TITLE
Mail not sent if address is incorrect

### ISSUE THREAD

**Issue by Evitahost** [PHPMailer/PHPMailer#2554]
If there is a typo in email address, phpmailer is throwing error and quitting the process altogether. I can see QUIT in debug.

I am using phpmailer for bulk email. Email addresses come from db.

How can I force it to send the email even if email is incorrect? Or atleast where can I write php script to delete this email row from MySQL.

**Comment by Synchro** [comment]
You can't force it to send if an address is incorrect because it's up to the mail server, which you don't control. You can however trap errors and continue, and if you enable keepalive (see the mailing list example), you should remain connected and be able to send further messages.

A second issue is that you should not be sending to addresses that have not completed a double-opt-in process (except as part of that process), and a double-opt-in process provides a guarantee that the email address exists, so for the most part you won't have that problem.
