### ISSUE TITLE
 exploitable PHPMailer script on the site that's being abused

### ISSUE THREAD

**Issue by danjocreative** [PHPMailer/PHPMailer#2587]
Hi, my apologies if this is not the way about this, I am new to this and I am stuck with an issue coming form a client site that is on a shared hosting platform.

The site uses PHPMailer 5.5 and we have been flagged as abusive due to spam emails being sent from the site, we have been told that the script for PHPMailer has been exploited and has had exits added to stop this running, this has had a knock on affect as our client cannot see orders or customers are not being notified of orders through woocommerce,

Is there a fix for this or what can I do to look at this going forwarD.

thanks in advance
Marty

**Comment by Synchro** [comment]
By itself, PHPMailer does nothing at all; the exploit will be in the code which is using it. It's quite easy to write a emailing scripts that are inadvertent spam gateways, which I'd guess is what's happened to you. You will need to track down what is asking PHPMailer to send. Make sure you're using latest versions of WooCommerce, WordPress, plugins etc.

**Comment by danjocreative** [comment]
Hi Synchro, how can I update PHPMailer to the latest version? as I this would be the only thing that is not running at the latest versions. Is there a way I can track down what is asking PHP Mailer to send?

thanks
Marty

**Comment by Synchro** [comment]
For upgrading, start [here](https://github.com/PHPMailer/PHPMailer/blob/master/UPGRADING.md). Search your code for scripts that create PHPMailer instances, for example with `grep -R 'new PHPMailer' /path/to/wordpress`, then inspect the surrounding code to see how it handles user-supplied data, for example, anything that lets you send a message where both the to address and the message body or subject can be set by the user is a spam gateway. Bear in mind it may happen via the database rather than being injected directly.
