### ISSUE TITLE
AddReplyTo causes issues with SpamAssassin 

### ISSUE THREAD

**Issue by mrteeitup** [PHPMailer/PHPMailer#2625]
I am new to the forum but not new to PHP Mailer, I've used it for many years. I do have an issue however with AddReplyTo().
When this function is used with an email address that is not on the sending server, spamAssassin assigns a 2.5 penalty to the email spam rating.

I'm wondering if anyone knows of a solution to this problem. I have my own custom mail server with golf customers who communicate with golf league members. phpMailer works very well but I am looking for a solution for this problem and I am hoping that someone else has some suggestion.

Here's the code I am using in case there might be a problem with how I use the AddReplyTo() function:

```
try {
$mail->Host 		= "localhost";	        
$mail->SMTPDebug  = false;		
$mail->SMTPAuth   = true;			
$mail->Port       	= 25;			
$mail->Username   = $server_box;		
$mail->Password   	= $box_password;	
$mail->AddReplyTo($senderEmail, "$senderName"); 
$mail->AddAddress("$to_address", "$to_name"); 	
$mail->SetFrom($server_box, "$senderName"); 	
$mail->Subject = $subject;
$mail->MsgHTML($HTML);
$mail->SMTPAutoTLS = false; 	// needed this to stop a SMTP connection error
$mail->AddCustomHeader("List-Unsubscribe: <mailto:".HELPDESK_EMAIL."?subject=Unsubscribe>, <".$unsubUrl.">");
$mail->Send();
 } 


catch (phpmailerException $e){ 

$phpmailer_err_mess = $e->errorMessage(); // Pretty html error messages from PHPMailer
// doing a bunch of things here with the $phpmailer_err_mess
 }
```

**Comment by Synchro** [comment]
Unfortunately this is entirely outside the control of PHPMailer, and it would apply equally to any other mail client that created messages with such reply-to addresses. You could request that spamassassin changes the points value of this action, however, I would assume that their values are based on assessment of what's seen in actual spam, so I doubt you'll have much success, and even if you did, it would take years to propagate through the spamassassin user base.

One alternative would be to include a `mailto` link in the body of the message pointing at the sender address. This is obviously not quite as convenient as being able to hit reply, but it would avoid incurring the points.

I'd probably be tempted to live with it, because 2.5 point is below the default 5 threshold that spamassassin requires to assign a "spam" verdict, though it obviously gives you less wiggle-room for other issues that spam assassin's scoring may cause.

**Comment by mrteeitup** [comment]
Thank you for that answer Marcus, it is spot on! I thought that might be the case, but it never hurts to ask the question. I have been just living with it for the reason you described, but it just bugs me and it does take away half of the safety margin. Thanks again,Joe Joe ***@***.***    Sent from Mail for Windows 10 From: Marcus BointonSent: Monday, February 7, 2022 12:12 PMTo: PHPMailer/PHPMailerCc: Joe Thomas; AuthorSubject: Re: [PHPMailer/PHPMailer] AddReplyTo causes issues with SpamAssassin (Issue #2625) Unfortunately this is entirely outside the control of PHPMailer, and it would apply equally to any other mail client that created messages with such reply-to addresses. You could request that spamassassin changes the points value of this action, however, I would assume that their values are based on assessment of what's seen in actual spam, so I doubt you'll have much success, and even if you did, it would take years to propagate through the spamassassin user base.One alternative would be to include a mailto link in the body of the message pointing at the sender address. This is obviously not quite as convenient as being able to hit reply, but it would avoid incurring the points.I'd probably be tempted to live with it, because 2.5 point is below the default 5 threshold that spamassassin requires to assign a "spam" verdict, though it obviously gives you less wiggle-room for other issues that spam assassin's scoring may cause.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
