### ISSUE TITLE
PHPMailer has problems sending FPDF-generated PDFs when images are included: "Could not instantiate mail function"

### ISSUE THREAD

**Issue by bernd-9er** [PHPMailer/PHPMailer#2651]
We are using PHPMailer to send PDFs, which are generated with the fpdf-library (v1.84). There is one jpeg added by the library.

PHPMailer reports the following problem: **Could not instantiate mail function.** after the addAttachment command.

We used the following FPDF function to add a jpeg file to the PDF:
_$pdf->Image('file.jpg',$PosX, $PosY, '40', '0');_ 

This resulted in a correct PDF file, but PHPMailer would not send it as attachment. 

Workaround: When using
_$pdf->Image('file.jpg',$PosX, $PosY, '40', '0','jpg');_  
instead, everything worked fine.

**Comment by Synchro** [comment]
I'm not clear how this is a PHPMailer problem? You've not shown your code, but `addAttachment` doesn't call `mail()`, so there's something else going on here. Perhaps you have some custom error handler that sends error messages by email?

**Comment by bernd-9er** [comment]
This the code (excerpt):
			$MyMail->addAttachment($PathServerFile, $ServerFile); 
if (!$MyMail->send())
				{
					{
						echo $MyMail->ErrorInfo ;
					}
				}

This results in "Could not instantiate mail function".

**Comment by XL-2000** [comment]
Not much code to go o here...
Did you excplicitly try to use SMTP? like calling $MyMail->mailer->isSMTP();

**Comment by XL-2000** [comment]
Apart from always preferring SMTP over mail(), please note that mail() is notoriously bad in sending (large) attachments.
Please check your PHP error log, because it might (and could or even should) have an error like "Cannot send message: Too big", so the failure of "mail()" is actually caused by the message being too big.
This also explains why using an explicit small attachment works

**Comment by bernd-9er** [comment]
First thing I checked the PHP log file, but there was no error. I confess that Idid not use the SMTP(), but the mail() function, but it worked with the same file size when declaring the file format of the included image file in PDF. 

Couldn't it be that PHPMailer had some problems encoding the PDF file?

**Comment by Synchro** [comment]
I think  that's unlikely because it really doesn't care what's in the file; it just does a blind transform into base64, as it should. It is more likely that you've done something like delete the file between calls to `addAttachment` and `send`. It's also possible it can run out of memory if the file is big, but that would be reported as such. The usual reason for the "could not instantiate" error is due to not having a local mail server installed, but you clearly do, however anything that makes `mail()` return false will have the same effect. Any error relating to the submission will be recorded in your local mail server logs, but you won't be able to see that if you're on shared hosting. It could also be that your local mail server has a size limit that only the messages containing images are hitting.

This is another reason to use SMTP to localhost – the only feedback from `mail()` is the true/false return value, whereas SMTP can give you far more detailed feedback.
