### ISSUE TITLE
What is the security filtering structure for user input?

### ISSUE THREAD

**Issue by ZhangChengLin** [PHPMailer/PHPMailer#2701]
https://github.com/PHPMailer/PHPMailer/blob/bf99c202a92daa6d847bc346d554a4727fd802a5/src/PHPMailer.php#L1611

Why not use '$this-secureHeader($this-Subject)' everywhere

The scenario is that when the email header and content are written by external clients, how to ensure that the calls in each place are safe.
Including 'bcc', 'cc', etc. are all content that may be entered by the client, and they are not safely filtered from the beginning, is there a place for repeated security filtering?

https://github.com/PHPMailer/PHPMailer/blob/bf99c202a92daa6d847bc346d554a4727fd802a5/src/PHPMailer.php#L1927-L1931

https://github.com/PHPMailer/PHPMailer/blob/bf99c202a92daa6d847bc346d554a4727fd802a5/src/PHPMailer.php#L1758-L1762

**Comment by Synchro** [comment]
`secureHeader` only strips newlines. It's not needed on any address input because those already have protection against that. Generally speaking, PHPMailer is not responsible for input filtering as that's a higher level app concern (i.e. PHPMailer never obtains input itself, by any route), though it is concerned with validity. That said, it's actually valid for an email address to contain line breaks!

In those examples, all of those inputs are filtered before they are used. `cc` and `bcc` are arrays, so stripping newlines would not apply anyway. `From` is filtered by `addrFormat()`.

Do you have any specific places you think this should be applied?
