### ISSUE TITLE
Recipient addresses modified after the send() function call

### ISSUE THREAD

**Issue by bsiedlecki3474jll** [PHPMailer/PHPMailer#2736]
Hello,

I found no success in debugging my application in multiple ways, so I decided to share my problem here.
I am using a mailing list defined in my system and it is being retrieved while user decides to send a group email.
In some cases a random point is being added to the recipient address and the email is not being delivered.
Example: **someemail@example.domain.com** is being changed to **someemail@example.dom.ain.com**
It also appears to be changed in the email prefix, not only in domain.

I have upgraded the version to the latest (6.6.3 right now) and still nothing changed.

I've double-checked all the addresses in DB and all were correct. I've also printed out all the emails just before the send() function call just to see if there is any way that it could be modified just before and all the addresses were correct.

There might be some issues with email filtering system that my company uses, but I want to see if there is any possibility that it is an issue on the library's side.

Thanks for the help!

**Comment by Synchro** [comment]
If you're sending to quite a lot of addresses, it's likely your addresses are wrapping onto more than one line. Because addresses contain dots (in local or domain parts), and a wrapped line can mean that a dot appears as the first character on a line, it has the potential to make the server think that it has reached the end of the message, because a dot as the first char on a line is used to indicate the end of a message. To combat this, a system called "dot-stuffing" is used, where a dot at the start of a line is doubled, but the extra dot is then stripped by the receiving server. Despite the fact that this is a very old part of the SMTP spec, some servers don't handle it properly (I've seen it with MS Exchange). You should be able to see if it's happening by setting `SMTPDebug = 2` and inspecting the beginning of each line, and whether it corresponds with the locations of extra dots in your messages. You can also check it by sending to a different server, such as gmail.
