### ISSUE TITLE
[SMTP] MessageID gets overwritten

### ISSUE THREAD

**Issue by patriotaki** [PHPMailer/PHPMailer#2859]
Hi,

When I send emails using phpmailer and sendinblue SMTP, the message id (header) is always replaced by SendinBlue

I have tried getting the last message id that is autogenerated by PHPMailer `getLastMessageID()` and compared it with the actual message id in the header on the gmail (account that receives the email sent by phpmailer) and they are different.

I also tried generating my own custom message id header but that is also replaced by SendinBlue.

Instead it gets added in another header with title "origin message id" on both cases.

Is there any way to force my own custom message id header?

**Comment by Synchro** [comment]
This is not good behaviour by sendinblue, as it's very likely to break DKIM signing. While you can set your own message ID, if they are replacing it in transit, there's not much you can do. Id recommend asking their support.

**Comment by patriotaki** [comment]
@Synchro 
Thanks for the reply, I doubt that their support will know how to answer. I guess this is a tactic to market indirectly promote their service on free plans.

Have you noticed anything similar on other services? I wonder if they all use the "origin message id" header to add the message id generated by phpmailer

**Comment by XL-2000** [comment]
What are you using sendinblue for exactly?

I am not familiar with sendinblue, but in general; the Message-ID is set by the e-mail sending application/server. If I understand and assume correctly, you are using PHPMailer to send an email to sendinblue, and you use sendinblue to actually send the emails to the actual (final) recipient. So more or less relaying / re-sending the original PHPMailer sent email. If this assumption is true, sendinblue is the "actual" sending application, so might very well set its own Message-ID. It is actually sending a new email, which happens to be very similar to the original one...

The Message-ID is there for debugging purposes on the sending application. So, a Message-ID from PHPMailer, sent from sendinblue would (from a solution perspective) not have great value, since it will not correspond to anything you can debug on the sendinblue side, whereas a sendinblue Message-ID would.

So maybe describe your solution a bit more and what your actual problem is with the new Message-ID?
