### ISSUE TITLE
SMTP connect() failed when sending to 

### ISSUE THREAD

**Issue by Bulli77** [PHPMailer/PHPMailer#2881]
I have a problem. I added the following lines to the config.php and config_extend file:

**define('PHPMAILERHOST','smtp.nameserver.com:587');
define('PHPMAILER_SMTPUSER','<name user>');
define('PHPMAILER_SMTPPASS','<pass>');
define('PHPMAILERPORT', 587);
define('PHPMAILER_SECURE', 'tls');
define('POP_BEFORE_SMTP', false);**

**define('PHPMAILERTESTHOST','testsmtp.nameserver.com');
define('PHPMAILERBLASTHOST','nameserver.com');
define('PHPMAILERBLASTPORT',25);

define('SMTP_TIMEOUT',5);
define('POPBEFORESMTP_DEBUG',false);**

But I still see SMTP errors in the event log. Can you please help me troubleshoot this issue?
SMTP connect() failed when sending to [Please refer to https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting for assistance.

**Comment by Synchro** [comment]
PHPMailer doesn't read global constants, so I have no idea what your code is doing. You also asked for troubleshooting advice while including a link that refers you to the troubleshooting guide which provides exactly that, so I suggest you go read that, and next time please read the issue template instead of just ignoring and deleting it.
