### ISSUE TITLE
Allow preSend() without recipients

### ISSUE THREAD

**Issue by mschering** [PHPMailer/PHPMailer#2948]
Hi,

I have a small feature request. In my application I store mail templates in MIME format. For that purpose I don't want any recipients inside. 

At the moment it's not possible to create this because of the validation at line 1568. Perhaps you could set a property "allowNoRecipients" or something like that.

Best regards,
Merijn

**Comment by mschering** [comment]
I am using it for both sending and those template. So when I want to save the template I call preSend() and then get the MIME with getSentMIMEMessage(). Works fine but only if a recipient is set.

**Comment by Synchro** [comment]
Yes, I understand that, I'm saying that it would work better if you didn't do it that way. Why do you need to save the fully formatted message when it's impractical to use that as a template (because encodings will really getting the way), and it's much more difficult to send it later (because PHPMailer doesn't make it easy to send an existing RFC822 message)?

**Comment by mschering** [comment]
You're right. I do it that way for legacy reasons. The MIME is decoded when loading the template editor which works fine but I understand it can be done more efficiently. We need to refactor that later but for now I can't do that.

**Comment by XL-2000** [comment]
So, if it is not the intended use of the PHPMailer software and  if it is temporary, and you are refactoring this later on; why not temporarily  make those changes in your local version of PHPMailer until you are using it the proper way? In essence, make your own fork of the code

**Comment by mschering** [comment]
Yes if it’s not an option you’d like to support I’ll go that route.

thanks.
