### ISSUE TITLE
PHP Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by peti123x** [PHPMailer/PHPMailer#2959]
# Problem description
Using the latest PHP8.2 image and the latest version of phpmailer (6.8.1), I'm getting a deprecation warning pointing to https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1574 (the `trim()` function gets a null value).

# Code to reproduce
Not sure what in the system is actually making the deprecation warning emit, but nevertheless the fact that the warning appears means the trimmed value can be `null`.

# Debug output

**Comment by Synchro** [comment]
This is a little mysterious because all of `From`, `Sender`, and `ConfirmReadingTo` are initialised to empty strings, and nowhere are any of them set to `null`. However, they are public properties that can be set to `null` by calling code, which I assume is what's happening for you. I'm not too concerned about that, but I'll accept a PR if you want to fix it.

**Comment by Synchro** [comment]
This is fixed in the main branch and will be in the next release
