### ISSUE TITLE
Unsubscriber URL never getting called By Gmail

### ISSUE THREAD

**Issue by iamved777** [PHPMailer/PHPMailer#2989]
Hi!
I have added custom header like this in my email

```
$mail->addCustomHeader(
            'List-Unsubscribe',
            "<mailto:unsubscribe@cineferte.fr>,<https://example.com/unsubscribe.php?email=" . $email. ">"
        );
        $mail->addCustomHeader(
            'List-Unsubscribe-Post',
            'List-Unsubscribe=One-Click'
        );
```

Its link showing in gmail as attached image, I can see complete link in view original message but whenever I click Unsubscribe, its showing unsubscribed but its URL is never getting called and I am not getting any POST or GET request for the same in given URL. 

![Screenshot_1369](https://github.com/PHPMailer/PHPMailer/assets/139719122/8dc86d2c-b685-4daa-ade7-a7c787a5c904)
![Screenshot_1370](https://github.com/PHPMailer/PHPMailer/assets/139719122/a4dc2800-8ed1-44bc-b486-f3e50a019358)

Let me know if I have done anything wrong or missing something. 

Thanks!

**Comment by Synchro** [comment]
Those headers look ok. You say "its showing unsubscribed" – what exactly happens when you click the link? If you copy the URL out of the message and open it in a browser, do you get a hit on your script? If you do, then it may be that google is filtering the request; they are prone to doing things like that.

I'm not sure if it's for redaction purposes, but the parameter you're providing is literally `email=token`, rather than an actual token, though that should not prevent it from hitting your script – you just won't be able to tell who the click applies to.
