### ISSUE TITLE
SMTP Error: The following recipients failed:

### ISSUE THREAD

**Issue by nestsman** [PHPMailer/PHPMailer#349]
Sometimes I have outgoing emails that don't go out due to the following error:

"SMTP Error: The following recipients failed: address@examplel.com"

Someone on a forum suggested removing "$mail->IsSMTP();  " from my code.  Suddenly those messages successfully went out when I retried them.  Why is $mail->IsSMTP();  in the example code if it works best to comment it out or remove it?

Thank you.

**Comment by Synchro** [comment]
Calling `isSMTP` makes PHPMailer send directly via SMTP. If you don't call it, it submits to your local mail server instead using the php `mail()` function. If you don't have a local mail server (e.g. because you're running Windows), then SMTP is the only choice. It's quite possible for you to request SMTP and then fail to set other required params and have it fail. On the other hand, if you send via SMTP to a bad address it will probably fail immediately, but submitting via mail will succeed, but fail later, which could be what's happening in your case.

**Comment by nestsman** [comment]
Is there any way to get a better reason as to why a recipient fails?  Is it due to their mailbox being full, a typo in the email address or some other reason?

Thanks!

**Comment by mrdemc** [comment]
the receiving mailserver may send a reply to the replyaddress with the notification why it fails. Then you can see within this reply why the mailserver is denying your e-mail.
However, this mailserver might never get your e-mail if for instance your dns lookup is not working correctly.

**Comment by yoma0012** [comment]
I am only able to send emails with PHPMailer to emails on my server other emails including gmail gives the "Administrative prohibition" as SMTP Error.

**Comment by NiklasBr** [comment]
@yoma0012 That error message can mean that the server owner has blocket you, perhaps a blacklist because your server might have sent too much spam at one point. Check if you are on one, or ask a recipient if they can give you more info.
