### ISSUE TITLE
validateAddress() 'auto' pattern should pick 'html5'

### ISSUE THREAD

**Issue by dregad** [PHPMailer/PHPMailer#354]
Considering that with *html5* we now have a more simple (and de-facto standard) regex for email validation than the fully RFC5322-compliant one, I believe it would make sense for the 'auto' type to use that instead  *pcre8*.

**Comment by Synchro** [comment]
Well, I know because I wrote that spec, but I don't think it's a good idea as PHPMailer gets used in lots of non-HTML5 contexts, and it's not really its job to be restrictive. If you want it to be, it can, but it should not do it by default. Also that spec needs an update for the possibilties offered by the SMTPUTF8 extension that google now supports.

**Comment by dregad** [comment]
OK fair enough, thanks for the feedback.
