### ISSUE TITLE
AddBCC problems

### ISSUE THREAD

**Issue by brecht27** [PHPMailer/PHPMailer#356]
If i add the AddBCC or AddCC option the mail is not sending but i'm receiving an error 'Could not instantiate...' If i remove those option it will worked perfect.

**Comment by Synchro** [comment]
Make sure you're using latest PHPMailer, post your code, and the full error.

**Comment by brecht27** [comment]
I have used the latest version. The error message is: Message could not be sent.
Mailer Error: Could not instantiate mail function.

My code:

require_once('../../phpmailer/class.phpmailer.php'); //where your phpmailer folder is
$mail = new PHPMailer();                    
$mail->From = "boekhouding@contentu.be";
$mail->FromName = "Boekhouding - ContentU Group";
$mail->AddAddress($f_email);
$mail->AddReplyTo("boekhouding@contentu.be", "Boekhouding - ContentU Group");
$mail->AddBCC("boekhouding@contentu.be");
$mail->AddAttachment($file);
$mail->isHTML(true);

$mail->Subject = $subject;                  
$mail->Body = $body;

**Comment by Synchro** [comment]
You may be using the latest version, but you've based your code on an an obsolete example.

That's not your complete code; please post the rest of it.

Did you even try searching for that error message? [This answer](http://stackoverflow.com/a/26235275/333340) is what you should look at first, rather than repeating myself here.

**Comment by brecht27** [comment]
Without the AddBCC option the mail is send perfect.
If it is not working i will try with the SMTP option. Is that the reason why?
The complete code:

require_once('../../phpmailer/class.phpmailer.php'); //where your phpmailer folder is
$mail = new PHPMailer();                    
$mail->From = "boekhouding@contentu.be";
$mail->FromName = "Boekhouding - ContentU Group";
$mail->AddAddress($f_email);
$mail->AddReplyTo("boekhouding@contentu.be", "Boekhouding - ContentU Group");               
$mail->AddBCC("boekhouding@contentu.be");
$mail->AddAttachment($file);
$mail->isHTML(true); 
      
// attach pdf that was saved in a folder
$mail->Subject = $subject;                  
$mail->Body = $body;
if(!$mail->Send())
{
   echo "Message could not be sent. <p>";
   echo "Mailer Error: " . $mail->ErrorInfo;
}
else
{
   echo 'Mail send';    
} //`the end`
//============================================================+
// END OF FILE
//============================================================+

**Comment by Synchro** [comment]
I wonder if your mail server doesn't like your BCC being the same as To and From. You need to check your mail server logs - it should say why it's failing. Otherwise you can use SMTP to localhost (which may be faster anyway), which will let you get more detailed debugging info, though you'll need to update your code to look like one of the bundled examples.

**Comment by zenas101** [comment]
am having a new problem with the ADDBCC if you send to more than one email using the bcc it only delivers to the last email in the bcc and the rest with not send
 for example:
 bcc [ example1@mail.com,example2@mail.com,example3@mail.com,example4@mail.com ]

only example4@mail.com will be delivered but the rest will not be sent can some one help me?

**Comment by Synchro** [comment]
Please don't hijack unrelated tickets, open a new one. I need to see your code, you need to look at your SMTP transcript and in your mail server logs.
