### ISSUE TITLE
PHP 5.6.0 SMTP connect error

### ISSUE THREAD

**Issue by OleksZ** [PHPMailer/PHPMailer#359]
I'm getting an error while trying to send a message over SMTP with PHP 5.6.0
Everything works great with 5.3.* version (works well on Apache and IIS as well).

While sending message using 5.3.* php the logs (level 4) are:

Connection: opening to ssl://mail.*********:465, t=300, opt=array ()
Connection: opened
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "220 mail.**********, ESMTP EXIM 4.84"
and so on (e.g. everything works)

But if I switch php version to 5.6.0 the output for the same operation will be:
Connection: opening to ssl://mail.********:465, t=300, opt=array ()
SMTP ERROR: Failed to connect to server: (0)
SMTP connect() failed.

Everything is the same excapt of PHP version. I suppose PHPMailer refuses to work with PHP 5.6.*

**Comment by Synchro** [comment]
PHPMailer works just fine with PHP 5.6 - it's in the automated testing config. You're probably running into the fact that PHP 5.6 now verifies SSL certificates by default, and if you connect to a server that doesn't verify, the connection will fail. Diagnose your situation using openssl. if this is what's happening, you can provide additional params to the SMTP connection to tell it not to verify certificates, though of course that means your connection is no longer secure.

You should avoid using ssl on port 465 - it's been deprecated since 1998! Use TLS (`SMTPSecure = 'tls'`) on port 587.

**Comment by OleksZ** [comment]
Thank you!

Just a question - you say "PHP 5.6 now verifies SSL certificates by default" - does that mean that all self-signed certificates will be invalid?

**Comment by Synchro** [comment]
Yes.

**Comment by dcrdev** [comment]
I'd seen that mentioned on the php website - I've got my root CA bundle referenced directly in my php configuration to make sure. I'm pretty sure it's something else as I can open a socket connection to ssl destinations in php i.e. through fopen.
