### ISSUE TITLE
Debug for plain mail() usage

### ISSUE THREAD

**Issue by derchrisuk** [PHPMailer/PHPMailer#396]
I checked the docs available, but not able to find any info.
Basically, I have a PHPMailer setup, where the user can change the Protocol and its options using a Admin backend.
From what I can see from the current codeset, and what I could see during testing, debug is only working for SMTP connections.
Even when the mail goes through PHPMailer, but not using SMTP but local mail(), no debug is visible.
I know that the doc says SMTP debug, but is there a way to get the same kind of debug when using mail()?

**Comment by Synchro** [comment]
No, because ultimately `mail()` is just a single function call, and we can't see what happens inside it from PHP. You can however see what's happening by looking at the logs of your local mail server. You may find that you get better performance by using SMTP to localhost than using `mail()` anyway, and you can obtain more debug info that way too.
