### ISSUE TITLE
PCRE regex validation problem for pcre8 mode

### ISSUE THREAD

**Issue by pkorsukov** [PHPMailer/PHPMailer#425]
On my production environment PHPMailer suddenly stopped sending the messages. 
The error in PHPMailer:
preg_match(): Compilation failed: internal error: previously-checked referenced subpattern not found at offset 728
which comes from validateAddress function after case 'pcre8'.

After the research I found that it can be related to PCRE library update. The environment is Debian+Apache+PHP5+PCRE 8.36.

There was no solution for me, so I force $patternselect = 'pcre'; and now it is working.
It would be great to take a look why pcre8 regex is not compatible with the recent version of PCRE.
Thanks!

**Comment by Synchro** [comment]
Can you post an example of an address that triggers this? There is a fix in PCRE 8.37 for a bug in 8.36 that generates this error, so it may be that.

**Comment by pkorsukov** [comment]
In my case it was for all e-mail addresses of our new users. Something like
user@test-domain.com throws exception

**Comment by bizley-code** [comment]
For me it was typical email address: test@test1.com

**Comment by Synchro** [comment]
I'm having no trouble with these addresses with PCRE 8.36 in PHP 5.6.9 and the 'pcre8' pattern, so it seems there must be an environmental factor involved. It sounds like it might be similar to the problems that arose before PCRE 8.03. It's tempting to dump those custom patterns altogether and just use the PHP filter_var one since it's almost identical.

**Comment by pkorsukov** [comment]
For me the validation is not important at all, so I would prefer to have a component which always works without any version-specific functions. Especially when it comes to mail function which popular across the community.
Please consider removing the pcre8 mode as soon as it have no impact on security but impacting the stability.

**Comment by Synchro** [comment]
I've just given this a try. Reverting to the `php` or `pcre` validators results in more failures than I thought - neither accepts quoted names, IPv6 literals or comments in addresses, all of which are valid and not entirely uncommon. I don't think it's reasonable to change this behaviour so much in order to deal with an edge case that can be worked around so easily. Bear in mind that all the version-specific stuff that's already there is to deal with scenarios where PHP simply doesn't have an appropriate function and is necessary to provide a consistent interface across so many PHP versions. Just to be clear, all you need to do is this:

```php
class myMailer extends PHPMailer {
    public static function validateAddress($address, $patternselect = 'php')
    {
        return parent::validateAddress($address, $patternselect);
    }
}
```

Subclassing is a good habit anyway as it provides isolation between a specific implementation and your app code - I do this nearly everywhere I use PHPMailer.

If you want to take this further, you could report this to the author of the `pcre8` pattern [here](http://squiloople.com/2009/12/20/email-address-validation/).

**Comment by Synchro** [comment]
It appears that this is a PHP bug affecting PHP version 5.5.25 and 5.6.9 when run as an apache handler (i.e. mod_php), see #429, which is actually a duplicate of this issue.
