### ISSUE TITLE
Undefined variable $offset in PHPMailer::base64EncodeWrapMB

### ISSUE THREAD

**Issue by speicus** [PHPMailer/PHPMailer#426]
class.phpmailer.php, base64EncodeWrapMB(), line 2589.
$offset is undefined, should probably be initialized on line 2587:

```
$offset = $avgLength = floor($length * $ratio * .75);
```

Caught it with PHP_CodeSniffer, which we use as a part of our build process.

**Comment by Synchro** [comment]
I use PHPCS too, but it's not flagging this. I don't think it's a problem because the last term of a for loop is not evaluated until the end of the loop, by which time `$offset` is defined; if the loop runs 0 times, `$offset` is never needed. I agree that it looks a bit odd, but I think PHPCS may be technically wrong here. Curiously, if I define `$offset` before the loop as you suggest, it gets flagged as an unused variable because it is being overwritten (in the loop) before it's used.

**Comment by speicus** [comment]
We use PHPCS with VariableAnalysis plugin, that's what flagged this line with a warning.

I see you point, though this really seems like a micro optimization which comes at the cost of readability and may cause an error if, say, at some point in the future somebody decides to replace `for` with `while` or makes some other modification to the loop body. The original function (http://www.php.net/manual/en/function.mb-encode-mimeheader.php#60283) didn't have it.

I agree though, presently this is not an error.
