### ISSUE TITLE
Do not send X-Priority Header by default

### ISSUE THREAD

**Issue by ModulaShop** [PHPMailer/PHPMailer#449]
SpamAssasin has a Rule that punishes Messages that contain X-Priority Headers.
Obviously deliverability will be better when the Header is only sent when it`s explicit set by the user.

Quick fix: 
Line 41:     
```
public $Priority = null;
```
Line 1830:         
```
if(!is_null($this->Priority)) {
      $result .= $this->headerLine('X-Priority', $this->Priority);
}
```

**Comment by Synchro** [comment]
Thanks

**Comment by Jkay21** [comment]
Hello y'all?
We have been using the jorani leave management system for quite some time working perfectly fine in sending E-mails alert to the staff but 2 weeks ago it stopped sending mails i have been checking since last but i can't find the issue with the smtp configuration.
Any help would be appreciated.
thank you.

**Comment by Jkay21** [comment]
well.
thank you
