### ISSUE TITLE
Attachments from external sites.

### ISSUE THREAD

**Issue by goosehub** [PHPMailer/PHPMailer#451]
I want to use PHPMailer on one site to pull images from a separate site of mine. After some testing, it seems PHPMailer can't do this. Not sure if this is a bug, or a feature request, or if I'm just doing something wrong. Here's basically what I'm trying.

$mail->addAttachment('http://www.menucool.com/slider/prod/image-slider-2.jpg');

Rest of the email and attachments works correctly. Is there a good reason for this behavior?

**Comment by Synchro** [comment]
It can do it, you're just using the wrong function. Look at [`addStringAttachment`](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.html#method_addStringAttachment), which you'd use like this:

    $mail->addStringAttachment(file_get_contents('http://www.menucool.com/slider/prod/image-slider-2.jpg'));

It's done this way because there are too many variables for PHPMailer to take on this responsibility itself, so it handles either local files or strings - anything else is up to you.
