### ISSUE TITLE
"Oauth" class name is too common

### ISSUE THREAD

**Issue by mugabe** [PHPMailer/PHPMailer#488]
New OAuth class may conflict with other oauth classes. kohana/oauth for example.
As I see it's wrapper for League\OAuth2\Client\Provider\Google and it is for internal usage only. So I think it should be renamed to something like "PHPMailer_OauthGoogle".

By the way php 5.0 compatibility is broken. So I think it's good point to start using namespaces.

**Comment by Synchro** [comment]
Fair point. Since it's internal only, I can rename it without breaking things.

As far as I'm aware PHP 5.0 compat is not broken except if you use the XOAUTH2 class, which is a new feature and thus not subject to BC. This was quite deliberate and is mentioned in the readme. Just because the auth class can use a namespace doesn't mean that the others can (because that would be a BC break), and mixing namespace and no-namespace code can be messy.

**Comment by Synchro** [comment]
Fixed in 5.2.13
