### ISSUE TITLE
Using inline string attachments that are not images

### ISSUE THREAD

**Issue by princeofnaxos** [PHPMailer/PHPMailer#491]
If I receive email from e.g. Apple, their content is displayed as inline disposition with encoding 'quoted-printable'. The content is HTML.

How do I get this done with PHPMailer, so that my content is displayed in Thunderbird, and not is sent as an attachment?

In the source of the email, I see this:

[begin]
------=_Part_6146319_2109142555.1440747648159
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: QUOTED-PRINTABLE
Content-Disposition: inline
[end]

Note that there is no "filename" property, a thing which I don't seem to be able to do in PHPMailer when using AddStringAttachment():

[begin]
--b2_f5f8e28f1272cc1d73dd78c5de119158
Content-Type: text/html; name="theContent"
Content-Transfer-Encoding: QUOTED-PRINTABLE
Content-ID: <1>
Content-Disposition: inline; filename=theContent
[end]

Where lies the secret in this?

Regards,
Edwin

**Comment by Synchro** [comment]
Are you using the latest version? There was a change relating to this just recently.

**Comment by princeofnaxos** [comment]
Downloaded 5.2.12, but I stilll don't get it to display the inline string attachment. The source of the email shows this:

[begin]
--b2_aec5f1489a7498d5d4118e08eaa6df0d
Content-Type: text/html;  charset=UTF-8
Content-Transfer-Encoding: QUOTED-PRINTABLE
Content-ID: <0>
Content-Disposition: inline

<p>TEST</p>
[end]

The message has 1 attachment, which is an image that is also sent. So, the inline string attachment is no longer interpreted as a downloadable attachment, but it is also not displayed.

I compared emails from LinkedIn and Apple with mine and cannot see any differences between the attachment headers (except "Content-ID", which is not present at LinkedIn and Apple).

Does it have to do with $mailout->MsgHTML(" "); that creates a body with a space as content? I don't know how to send an email without body, since PHPMailer throws an error in that case.

**Comment by Synchro** [comment]
I don't think I've ever seen anyone doing inline HTML! Is there any reason you can't use a normal single body with embedded images? What does your intended MIME structure look like? A big multipart/related?

You should definitely not be calling msgHTML - that's intended to be a convenience function to help build single-body messages with embedded image references. Just set the Body property with your message body.

PHPMailer doesn't have any ability to construct arbitrary MIME structures, just a few presets. You might be better off with a library that does, such as Zend_Mail.

**Comment by princeofnaxos** [comment]
The reason I try this is that I want my mails to behave like the ones from LinkedIn and Apple. They send emails with a centered message body that stays intact when one replies to the message. The message is in an inline attachment. 
With a single message body I don't seem to be able to achieve this. At least in Thunderbird, all CSS is ignored in the reply message body.

**Comment by Synchro** [comment]
Ah, well that's different - you're not trying to do anything unusual. Whether it's centered has nothing to do with transfer encoding or disposition. Thunderbird (and many other clients, particularly gmail, yahoo and outlook) have some pretty bad CSS support, but the ways around that are nothing to do with disposition or transfer encoding. The emails I've found from Apple and Linkedin are nothing special - they use a completely standard multipart/alternative structure with single HTML and plain text body parts. In this context, an inline disposition makes no difference at all since that's how the bodies are typically treated anyway. You can easily experiment with the headers - save the message as a `.eml` file and edit its raw text, altering headers as you want, then reopen it in your mail client. You might want to look at [this run-down of email client CSS capabilities](http://www.email-standards.org).
