### ISSUE TITLE
Feature request:  addAttachment - attach from URL

### ISSUE THREAD

**Issue by markvirtue** [PHPMailer/PHPMailer#492]
If you change line 2254 (v5.2.12) from...

        if (!@is_file($path)) {

...to...

	if (!@is_file($path) && !url_exists($path)) {

...then files can be attached by URL (e.g. "http://server.com/filename").  Nothing else needs changing - it just works (assuming that "allow_url_fopen" is set to TRUE).

It DOES impact line 2437 of the same file...

      if (!is_readable($path)) {

....because if $path is a remote URL, is_readable() will return false, even though it may well be readable.

Any chance this can be incorporated into a future release?

Thanks,

Mark.

**Comment by Synchro** [comment]
No. `addAttachment` is specifically to use with local files precisely because it can apply more checks to the process. If you want to load data from remote URLs (with all the potential problems that implies), simply do this:

    $mail->addStringAttachment(file_get_contents($url), $filename);

That way the process of obtaining the data is entirely within your control, and not something that PHPMailer needs to be concerned with.

**Comment by markvirtue** [comment]
Fair enough.  Thanks for the speedy response.
