### ISSUE TITLE
Sending multiple emails to same Email Address

### ISSUE THREAD

**Issue by dhawal24** [PHPMailer/PHPMailer#493]
Hello,
I am using the below code of PHP Mailer... but the addresses are receiving same emails multiple times..

CODE: 

                        $mail = new PHPMailer();
			$mail->IsSMTP(); 
			$mail->SMTPDebug  = 0; 
			$mail->SMTPAuth   = true; 
			$mail->SMTPSecure = "tls";  
			$mail->Host = "XXXXXXXX"; 
			$mail->Port = XXXXXXXX; 
			$mail->Username   = "XXXXXXXX"; 
			$mail->Password   = "XXXXXXXX";        
			$mail->From = "XXXXXXXX";
			$mail->FromName = "XXXXXXXX";
			$mail->Subject = "XXXXXXXX";
			$mail->MsgHTML($Msg);

			$mail->AddAddress("XXXXXXXX", "XXXXXXXX");
			$mail->AddBCC("XXXXXXXX", "XXXXXXXX");
			$mail->AddBCC("XXXXXXXX", "XXXXXXXX");
			$mail->AddBCC("XXXXXXXX", "XXXXXXXX");
			$mail->AddBCC("XXXXXXXX", "XXXXXXXX");

			$mail->send();
			$mail->ClearAllRecipients();

What is the issue... help let me know..??? is there any problem in above code..

**Comment by Synchro** [comment]
You've based your code on an old example, so make sure you're running the latest version. The most likely explanation is that your script is being run more than once. This is quite a common problem that's often caused by browser plugins. It's easy to tell - just add some logging in here, or look at your web server logs.
