### ISSUE TITLE
TLS 1.2 Compatibility

### ISSUE THREAD

**Issue by imusorka** [PHPMailer/PHPMailer#542]
We seem to have an issue that relates to our server not supporting anything but TLS 1.2 anymore.

The following error is displayed when our shopping cart (osCommerce 2.3.4 BS) is trying to send mail. Note: PHPMailer did work before older SSL/TLS was disabled. Our server is running PHP 5.6.14.

```
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure in /includes/classes/class.smtp.php on line 344
```

The following seems to be the offending code.

```
        /**
         * Initiate a TLS (encrypted) session.
         * @access public
         * @Return boolean
         */
        public function startTLS()
        {
            if (!$this->sendCommand('STARTTLS', 'STARTTLS', 220)) {
                return false;
            }
            // Begin encrypted connection
            if (!stream_socket_enable_crypto(
                $this->smtp_conn,
                true,
                STREAM_CRYPTO_METHOD_TLS_CLIENT
            )) {
                return false;
            }
            return true;
        }
```

This is what our host sees in the exim error log.

```
2015-10-25 16:49:24 SMTP connection from [000.000.000.000]:45539 (TCP/IP connection count = 1)
2015-10-25 16:49:25 TLS error on connection from (domain.com) [000.000.000.000]:45539 (SSL_accept): error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
2015-10-25 16:49:25 TLS client disconnected cleanly (rejected our certificate?)
2015-10-25 16:49:25 SMTP connection from (domain.com) [000.000.000.000]:45539 closed by QUIT
2015-10-25 16:49:55 SMTP connection from [000.000.000.000]:60572 (TCP/IP connection count = 1)
2015-10-25 16:49:57 1ZqTAr-0007Ju-5b <= info@domain.com H=([000.000.000.000]) [178.168.80.21]:60572 P=esmtpsa X=TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128 CV=no A=dovecot_plain:info domain.com S=676 id=xxx@domain.com T="Test" for info@domain.com
2015-10-25 16:49:57 cwd=/var/spool/exim 3 args: /usr/sbin/exim -Mc 1ZqTAr-0007Ju-5b
2015-10-25 16:49:57 SMTP connection from ([000.000.000.000]) [000.000.000.000]:60572 closed by QUIT
2015-10-25 16:49:57 1ZqTAr-0007Ju-5b => info <info@domain.com> R=virtual_user T=virtual_userdelivery
2015-10-25 16:49:57 1ZqTAr-0007Ju-5b Completed
```

Could someone please shed light on how to solve this? Thank you in advance.

**Comment by Synchro** [comment]
This is down to your PHP config. The critical part in there is this message:

    no shared cipher

This means that the mail server is not accepting any of the ciphers that your SSL client has and vice versa. You need to alter/update your client to use better ciphers, or modify your server to add some ciphers that your client supports. Going TLSv1.2-only is not appropriate for a public mail server. It is a sensible approach for web servers that are serving a known client type (for example iOS apps using ATS in iOS 9), but that's very different from a public-facing service where you have no control over client configs, especially when you're talking about mail clients that generally get updated much more slowly than web browsers.


None of this is anything to do with PHPMailer - it's just caught in the crossfire.

**Comment by imusorka** [comment]
Thank you for responding.

This is a dedicated server running osCommerce. We had to go TLSv1.2-only due to PCI compliance requirements. Could you please clarify what is meant by "need to alter/update your client to use better ciphers"?

**Comment by Synchro** [comment]
Your server running TLSv1.2 has certain ciphers available. Similarly, PHP on your client will have an OpenSSL library with a bunch of ciphers (run `phpinfo()` and info functions like [`openssl_get_cipher_methods`](http://php.net/manual/en/function.openssl-get-cipher-methods.php) to find out more). Your problem is that they have none in common. FWIW, [PCI 3.1](https://www.pcisecuritystandards.org/documents/Migrating_from_SSL_Early_TLS_Information%20Supplement_v1.pdf) only mandates TLSv1.1, not 1.2. You may be able to enable additional ciphers in your client php.ini, or add others to your server without necessarily needing to change TLS version. It may be that you need to upgrade the SSL library on your client in order to achieve overlap.

**Comment by imusorka** [comment]
After days of trying to get this to work we have received the following from our host. Please advise.

"It looks like phpmailer is currently hard coded to use DES. This is a bad idea since it's an outdated, weak cryptographic algorithm. Changing it to use a more modern cipher like AES should work."

**Comment by Synchro** [comment]
That DES is poor is well known, but PHPMailer doesn't specify a cipher **at all**. The only thing PHPMailer specifies is `STREAM_CRYPTO_METHOD_TLS_CLIENT` in the call to `stream_socket_enable_crypto()`. [The docs on that](http://php.net/stream_socket_enable_crypto) show that this simply means it won't use SSLv3, which is an important security choice, but beyond that which cipher it uses is up to your PHP config, not PHPMailer.

**Comment by imusorka** [comment]
Unbelievable! That error was being generated simply because of Exim using a self-signed certificate on our server. Thank you for patiently assisting us throughout the process.

**Comment by Synchro** [comment]
The problem you had before didn't get as far as checking certificates - it was falling down on cipher lists, which happens before that.

First of all I suggest checking your mail server's SSL config using [testssl.sh](https://testssl.sh) from your client, which will give you a load of info about what your server will accept:

    testssl.sh --starttls smtp mail.example.com:25

Then compare the cipher list with what your phpinfo output says and check they have ciphers in common (also look up the openssl version you're using).

**Comment by imusorka** [comment]
It *was* the PHPMailer script after all. All we had to do was change the
command to the following.

STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT

Thanks.

**Comment by Synchro** [comment]
It's PHP itself that broke that constant in 5.6.7. Prior to that version that constant included TLS 1.2, but it no longer does, which is extremely annoying!

We can't change to `STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT` because that will break every site that doesn't have 1.2, which is a lot more than those that don't have 1.0, and we can't reasonably use `STREAM_CRYPTO_METHOD_SSLv23_CLIENT` because that's insecure in < 5.6, though it's the recommended value in 5.6.7+ because it doens't do what it looks like it does!

I suggest we do what [this comment says](http://php.net/manual/en/function.stream-socket-enable-crypto.php#119122].

**Comment by Synchro** [comment]
Ahem. [Which we are already doing](https://github.com/PHPMailer/PHPMailer/blob/master/class.smtp.php#L343)! So I don't know why it's not working for you.

**Comment by Synchro** [comment]
If you need to nail it specifically to that version, I suggest you subclass the SMTP class and reinject it as per the docs.

**Comment by imusorka** [comment]
Our version of PHPMailer was missing the following.

//PHP 5.6.7 dropped inclusion of TLS 1.1 and 1.2 in
STREAM_CRYPTO_METHOD_TLS_CLIENT
//so add them back in manually if we can
if (defined('STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT')) {
$crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT;
$crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT;
}

**Comment by MircoBabin** [comment]
_In my case PHPMailer 5.2.14 in combination with PHP 5.6.21 is used. And because of legacy, history and time constraints these versions can't be updated._

For anyone having received an email "[UPDATE][ACTION REQUIRED] - Update your TLS connections to 1.2 for SES using SMTP to maintain AWS endpoint connectivity" modify the file `class.smtp.php` function `startTLS()` to:

```php
    /**
     * Initiate a TLS (encrypted) session.
     * @access public
     * @return boolean
     */
    public function startTLS()
    {
        if (!$this->sendCommand('STARTTLS', 'STARTTLS', 220)) {
            return false;
        }
        
        //Allow the best TLS version(s) we can
        $crypto_method = STREAM_CRYPTO_METHOD_TLS_CLIENT;

        //PHP 5.6.7 dropped inclusion of TLS 1.1 and 1.2 in STREAM_CRYPTO_METHOD_TLS_CLIENT
        //so add them back in manually if we can
        if (defined('STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT')) {
            $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT;
            $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT;
        }
        
        // Begin encrypted connection
        if (!stream_socket_enable_crypto(
            $this->smtp_conn,
            true,
            $crypto_method
        )) {
            return false;
        }
        return true;
    }
```

**Comment by Synchro** [comment]
> _In my case PHPMailer 5.2.14 in combination with PHP 5.6.21 is used. And because of legacy, history and time constraints these versions can't be updated._

This doesn't make sense – you say you can't update the code, and then suggest updating the code! If you can do what you suggest, then you can update the whole library by the same mechanism, saving you the trouble of depending on a manually-edited version.

**Comment by MircoBabin** [comment]
@Synchro - I'm already owning an "manually-edited" version, because edits were made by the previous programmer. Unfortunately this is a pre-Git project, so which edits exactly were made and why, I don't know. Of course I could find out by comparing the official 5.2.14 sources with the modified sources, but that would just take time for something that is already working and has no justification for upgrading. 

Just updating the startTls function is the safest and fastest choice for me.

I do agree my situation is problematic and the best way forward would be to move to version 6, as version 5.2 is not supported anymore. But as I noted: legacy, history and time constraints are in the way.

**Comment by SvetoslavStefanov** [comment]
> _As noted by @Synchro: if you have the choice to upgrade PHPMailer, please upgrade and use an official version!_
> 
> _In my case PHPMailer 5.2.14 in combination with PHP 5.6.21 is used. And because of legacy, history and time constraints these versions can't be updated. I'm already owning a manually-edited version of PHPMailer and upgrading to an official newer version is out of scope._
> 
> For anyone having received an email "[UPDATE][ACTION REQUIRED] - Update your TLS connections to 1.2 for SES using SMTP to maintain AWS endpoint connectivity" modify the file `class.smtp.php` function `startTLS()` to:
> 
> ```
>     /**
>      * Initiate a TLS (encrypted) session.
>      * @access public
>      * @return boolean
>      */
>     public function startTLS()
>     {
>         if (!$this->sendCommand('STARTTLS', 'STARTTLS', 220)) {
>             return false;
>         }
>         
>         //Allow the best TLS version(s) we can
>         $crypto_method = STREAM_CRYPTO_METHOD_TLS_CLIENT;
> 
>         //PHP 5.6.7 dropped inclusion of TLS 1.1 and 1.2 in STREAM_CRYPTO_METHOD_TLS_CLIENT
>         //so add them back in manually if we can
>         if (defined('STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT')) {
>             $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT;
>             $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT;
>         }
>         
>         // Begin encrypted connection
>         if (!stream_socket_enable_crypto(
>             $this->smtp_conn,
>             true,
>             $crypto_method
>         )) {
>             return false;
>         }
>         return true;
>     }
> ```

I'm in the same boat as you. This did the trick, thank you!
