### ISSUE TITLE
Security Flaw!

### ISSUE THREAD

**Issue by jbolanosmd** [PHPMailer/PHPMailer#551]
I have numberous PHPMailer servers that are spoofing my email address.  Thousands of emails are being returned to me as undeliverable.

They are doing the following
Nancy Smith <jbolanos@nimbus-t.com>
Michael brooks <jbolanos@nimbus-t.com>

Etc.

Please contact me with a solution!  I need to use my email and I am having to delete thousands of these.
Can you make sure that these servers are not allowed to send emails without the authentication that they are coming from their servers and not mine?

**Comment by Synchro** [comment]
This is nothing to do with PHPMailer - it's just the tool they're using - they could use Outlook to do the same thing. It sounds like what you're seeing is [backscatter](https://en.wikipedia.org/wiki/Backscatter_(email)), and is commonly caused by bad anti-virus software sending bounces. The appropriate way to prevent email forgeries is to implement SPF and DMARC so that other servers (including yours) can recognise forged messages. It looks like you have implemented SPF correctly, so make sure that none of your allowed servers are compromised - check the IP addresses that say they sent the original messages.

Implementing DKIM and DMARC might help you see where the forgeries are coming from.
