### ISSUE TITLE
Adding addresses in the "To: " field without actually sending to those addresses?

### ISSUE THREAD

**Issue by kkotowick** [PHPMailer/PHPMailer#552]
I'm working on a list server of sorts, and I would like to use PHPMailer. I'm trying to figure out a way to have the recipient see multiple addresses in the To: field, without PHP actually sending to those addresses. For example:

- the email list "webmasters@company.com" should forward to "john@company.com" and "mary@company.com"

- an email is sent from an individual to "jack@agency.org" and "webmasters@company.com"

- the list server receives the email to "webmasters@company.com", and wants to forward it appropriately

- when John and Mary get the forwarded email in their inboxes, the "To: " field should show that it was sent to "jack@agency.org" and "webmasters@company.com"

So my question is, how can I get PHPMailer to actually send an email to ONLY "john@company.com" and "mary@company.com" but NOT to "jack@agency.org", while still showing "jack@agency.org" in the "To: " field in the email that John and Mary get?

Can this be done with this software? If not, any suggestions on an alternative?

**Comment by Synchro** [comment]
What you need in order to achieve this is to be able to set the To header addresses (within the message) separately from the envelope-to addresses (used at the SMTP level). PHPMailer won't do this out of the box because it uses a single array for both jobs, but you could probably subclass it to override that behaviour. I'd be wary of doing this as you may run into issues with spam filters, which tend to take a dim view of anything not looking like it acts, i.e. headers not matching the envelope.
