### ISSUE TITLE
PHPMailer inserts equal sign every 75th character

### ISSUE THREAD

**Issue by pkbarbiedoll** [PHPMailer/PHPMailer#563]
Using PHPMailer 5.2.14, emails are sent in text/html.  The outgoing text is littered with equal signs every 75th character.  

Before: 

    <p>This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp;</p>

After:

    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><font face="arial"><base href="http://example.com/">=
    <p>This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This i=
    s a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.=
    &nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; Th=
    is is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a t=
    est.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp;=
    ; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is=
     a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&amp;=
    nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; Thi=
    s is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a te=
    st.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp;=
     This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is =
    a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&amp;n=
    bsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This=
     is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a tes=
    t.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; =
    This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a=
     test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&amp;nb=
    sp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This =
    is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test=
    .&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; T=
    his is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a =
    test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&amp;nbs=
    p; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This i=
    s a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.=
    &nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; Th=
    is is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a t=
    est.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp;=
    ; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is=
     a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&amp;=
    nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; Thi=
    s is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a te=
    st.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp;=
     This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is =
    a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&amp;n=
    bsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This=
     is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a tes=
    t.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; =
    This is a test.&nbsp; This is a test.&nbsp; This is a test.&nbsp; This is a=
     test.&nbsp;</p></font>

What needs to happen to eliminate these stray equal signs?

**Comment by pkbarbiedoll** [comment]
The equal signs appear when viewing in Outlook.    When I send the same text/html to a gmail account, the equal signs are not present.

**Comment by pkbarbiedoll** [comment]
I tried using this workaround, but it did not remove the extra equal signs: 
		
	$email = new PHPMailer();
	$email->From      = 'from@example.com';
	$email->FromName  = 'FromUser';
	$email->AddAddress( 'to@example.com );
	$email->Subject   = 'This is a test';
	$email->LE = PHP_EOL;
	$email->Send();

**Comment by mrcatania** [comment]
I have the exact same problem, both with Hotmail recipients and with Outlook so it's obviously something to do with Microsoft's display.

**Comment by Synchro** [comment]
The equals characters are part of [RFC2045 quoted-printable encoding](http://tools.ietf.org/html/rfc2045#section-6.7), which uses trailing `=` chars to denote soft line breaks. This encoding should be reversed by the receiving MUA (in this case hotmail) before display. As far as I'm aware, PHPMailer is pretty clean on the encoding - in any recent PHP version it uses the built-in [`quoted_printable_encode`](http://php.net/quoted_printable_encode) function. Changing the value of `LE` is not an appropriate solution as it will make your messages deliberately break RFC compliance, likely to cause more problems than it solves.

The most useful thing to diagnose this further would be to see the source of a received message. It may be that outlook/hotmail is corrupting things, but since this is not a problem I've seen before, it may be specific to your setup.

**Comment by michield** [comment]
This issue is also being reported by phpList users, https://mantis.phplist.org/view.php?id=17919

phpList uses [phpMailer version 5.2.14](https://github.com/phpList/phplist3/commit/1e332aa5882e9e7daa0e631b5e1b3c3cb149b88f)

**Comment by Synchro** [comment]
OK, I still need to see a received message that shows this problem. I'm expecting something like a missing transfer-encoding header, but I can't guess from this end.

**Comment by michield** [comment]
Yes, I [asked for some examples](https://mantis.phplist.org/view.php?id=17919#c57197) as well.  I haven't managed to replicate it yet.

**Comment by mrcatania** [comment]
Thank you so much for your help, @Synchro.  That link to the encoding document helped me track down a way to keep the lines under 75 characters each; the issue was totally on our end. This was resolved by starting each HTML tag with \r\n and making that change solved both the soft-return and the 3D encoding problem.

Here's the example that wasn't working but has subsequently been solved in case it helps someone else.  We're running: PHP Version 5.3.15

Received: (qmail 13995 invoked by uid 48); 30 Nov 2015 19:33:52 -0500
To: them@hotmail.com
Subject: Test Mail To Get Headers
Date: Mon, 30 Nov 2015 19:33:52 -0500
From: "Us.com" <noreply@us.com>
Reply-To: "Us.com" <noreply@us.com>
Message-ID: <3a0a7c1384cdb9653d114b91db70de5a@www.us.com>
X-Mailer: PHPMailer 5.2.13 (https://github.com/PHPMailer/PHPMailer)
List-Unsubscribe: <mailto:noreply@us.com?subject=Unsubscribe>, <http://www.us.com/cancel.php>
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="b1_3a0a7c1384cdb9653d114b91db70de5a"
Return-Path: noreply@us.com
X-OriginalArrivalTime: 01 Dec 2015 00:33:52.0822 (UTC) FILETIME=[F45A0560:01D12BCF]

This is a multi-part message in MIME format.

--b1_3a0a7c1384cdb9653d114b91db70de5a
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Tiny TextHeader   Main body Button Text ByeThanks, and have a lovely day. F=
ollow us on Facebook (or Twitter) xxxxxxxxxxxx.com: 1189 Thomasville Rd Ave=
nue xxxxxxxxxxx, Florida xxxxx   Don't need these emails anymore? Unsubscri=
be.

--b1_3a0a7c1384cdb9653d114b91db70de5a
Content-Type: text/html; charset=us-ascii
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html style=3D"font-family: 'Arial Narrow', 'Helvetica', Hel=
vetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; =
padding: 0;"><head><meta name=3D"viewport" content=3D"width=3Ddevice-width"=

...etc

**Comment by Synchro** [comment]
I'm glad you found a workaround, but you really shouldn't need to change your content at all - the point of a transfer encoding is that it's transparent - you should get out exactly what you put in. You should only need to alter your content if you're using a transfer encoding that can't cope with your content, such as the default `7bit`, though PHPMailer will spot that and switch to quoted-printable automatically if it needs to.

You should really upgrade from PHP 5.3. It's been out of support for over a year, and 5.3.15 was released over 3 years ago - you are vulnerable to attacks!

**Comment by theonlydavewilliams** [comment]
This also had me puzzled for weeks. I managed to solve this problem by setting $email->Encoding = "base64".
