### ISSUE TITLE
Could not execute: /usr/sbin/sendmail -t -i

### ISSUE THREAD

**Issue by TJProgrammer** [PHPMailer/PHPMailer#593]
Hello. I tried send an email from our server but I got this error: `Could not execute: /usr/sbin/sendmail -t -i`

This is my email file. I call twice the function send.

``` php
<?php
/*
 * Email Class
 * Send emails.
*/
class Email {
    private $mail;

    public function __construct(){
        require "vendor/phpmailer/phpmailer/PHPMailerAutoload.php";
        $this->mail = new PHPMailer;
        $this->mail->isSendmail();
    }

    public function send($to_email, $to_name, $subject, $message){
        $this->mail->clearAddresses();
        $this->mail->setFrom("gestao@xxxx.pt", "Name");
        $this->mail->addAddress($to_email, $to_name);
        $this->mail->addReplyTo("xxxx@xxxxx.pt", "Name");
        $this->mail->Subject = $subject;
        $this->mail->Body = $message;
        return $this->mail->send();
    }

    public function getError(){
        return $this->mail->ErrorInfo;
    }
}
```

P.S.: I'm sorry for my English.

**Comment by Synchro** [comment]
Does `/usr/sbin/sendmail` exist, and can you execute it normally, outside PHP?

**Comment by TJProgrammer** [comment]
And how to do this through cPanel?

**Comment by Synchro** [comment]
You'd need to ask the cPanel devs about that.

**Comment by sujit223** [comment]
Hi Team,

I have been getting just the same error since long.
I will also mention the exact scenario below what exactly caused the error in my case.

I am using SENDMAIL function but not SMTP, SMTP works flawlessly. the issue is with SENDMAIL.

![capture1](https://cloud.githubusercontent.com/assets/11830376/15954814/15771558-2ef9-11e6-9b5f-18b476c81d19.PNG)

### If the SetFrom contains email address and email name it works fine.

![capture](https://cloud.githubusercontent.com/assets/11830376/15954848/7de95a60-2ef9-11e6-916f-bbe991d91458.PNG)

An in the next Failing Scenario

![capture3](https://cloud.githubusercontent.com/assets/11830376/15954866/a9409016-2ef9-11e6-85c9-13860d6524d0.PNG)

### If the SetFrom contains email address as email name then thats a problem.

![capture4](https://cloud.githubusercontent.com/assets/11830376/15954879/c84bf02c-2ef9-11e6-9dcd-d7d7b158d54e.PNG)

I dont understand why the send email function not accepting email address as email name. its not the right way to send email address as email name. But if we make a dynamic system we can't force the user to not to do that.

Please let me know if this is an issue of some kind or my idea needs improvement of using phpmailer.

Thanks in Advance.

**Comment by Synchro** [comment]
Thanks for the report - What a very odd problem! I don't think we have many using the Sendmail mailer. Can you extract the sendmail command line it generates and see if there's anything odd about that? It sounds like something is getting used as an address when it shouldn't.
