### ISSUE TITLE
Multipart messages have only parts

### ISSUE THREAD

**Issue by szepeviktor** [PHPMailer/PHPMailer#615]
I think a multipart message has no direct body only child parts. Child parts do have body.
Please consider avoiding `Content-Transfer-Encoding` in `multipart/*` parts of the message.
https://github.com/PHPMailer/PHPMailer/blob/9211ba67288c5cdd4980786085c3f026b1aef2b2/class.phpmailer.php#L2050-L2053
Thank you.

munpack warned me "munpack: warning: ignoring invalid content encoding on multipart", Horde doesn't include it.

**Comment by szepeviktor** [comment]
> If an entity is
   of type "multipart" the Content-Transfer-Encoding is not permitted to
   have any value other than "7bit", "8bit" or "binary"

https://github.com/PHPMailer/PHPMailer/blob/9211ba67288c5cdd4980786085c3f026b1aef2b2/class.phpmailer.php#L2056

**Comment by Synchro** [comment]
Yes, that's why it says exactly this in the comment on line 2049. It willl only ever get to line 2056 if it's not a multipart message, as checked at line 2050.

**Comment by szepeviktor** [comment]
@Synchro 
```php
            if ($ismultipart) {
                if ($this->Encoding == '8bit') {
                    $result .= $this->headerLine('Content-Transfer-Encoding', '8bit');
                }
                // The only remaining alternatives are quoted-printable and base64, which are both 7bit compatible
            } else {
                $result .= $this->headerLine('Content-Transfer-Encoding', $this->Encoding);
            }
```
Here you stat that quoted-printable and base64 equals 7bit but the standard does not allow these two.
Please consider again forbidding these in multiparts' encoding. Thank you.

**Comment by szepeviktor** [comment]
See in munpack also:
https://github.com/league/mpack/blob/master/decode.c#L116-L122

**Comment by Synchro** [comment]
You're misunderstanding both the code and that comment. Like it says, multipart elements will only ever have 8bit, binary or 7bit transfer encodings. Binary isn't really a viable type, and 7bit doesn't need to be declared as it's assumed by default. The comment you referred to is talking about child elements within the multipart, because you can't have a 7bit multipart containing 8bit child elements, but because quoted-printable and base64 encodings are 7-bit safe, we only need to concern ourselves with CTE for the multpart if the user has requested 8bit CTE. I don't know how to make this clearer; **There is no path through this code that will result in a multipart element having quoted-printable or base-64 CTEs**; it will either be unset or 8bit.

**Comment by szepeviktor** [comment]
Thank you.
That error was only in 5.2.6.
5.2.14 proves to be CTE-less in multipart.
