### ISSUE TITLE
Feeling stupid :(  - Can't figure out how to populate the emails.

### ISSUE THREAD

**Issue by michaelsomerville** [PHPMailer/PHPMailer#623]
```
<!doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <title></title>
</head>
<body>
<div style="width: 640px; font-family: Arial, Helvetica, sans-serif; font-size: 11px;">
 
 <p>Please confirm your email</p>
 <p><?php echo $linkto; ?></p>
 
</div>
 <p>Remove you email from our list here : <a>Opt-out</a></p>
 <img src="<?php echo $openlink; ?>" alt=""/>
</body>
</html>
```

I am trying to push the mysql data into the email, circled around this for hours and can't get. Thoughts?

**Comment by ooxi** [comment]
The PHPMailer bugtracker is for tracking bugs, not general help requests. Please use a more suitable platform like stackoverflow.

---

That being said, you have to figure out three parts in order to get your problem solved

 * Rendering the mail content to HTML while preserving references (`$openlink`) in a database
 * Sending the rendered HTML with e.g. PHPMailer to your clients
 * Taking actions on requests by your clients (a php script which knows which client had the link `$openlink` and act accordingly)
