### ISSUE TITLE
Using PHPMailer+OAuth2 without Composer

### ISSUE THREAD

**Issue by RenanLazarotto** [PHPMailer/PHPMailer#632]
Hello there.
I've been searching for this for days and nothing that I try works. I'm trying to use PHPMailer+OAuth2 (to use Gmail) but I can't get it to work. I can go as far as editing the "get_oauth_token.php" file, but then I get this error: 
`Fatal error: Class 'League\OAuth2\Client\Provider\AbstractProvider' not found in ../get_oauth_token.php on line 36`
Which happens because I don't have the OAuth2 lib installed and can't install it since my host doesn't allow it. Is there anything that I can do?

**Comment by Synchro** [comment]
Set up composer on your local machine, install all the packages PHPMailer wants with it, then upload the whole vendor folder to your server.

**Comment by gmariani** [comment]
Is it so difficult just to tell people the list of like 10 lines or require vs answering all the questions on how to avoid composer?

**Comment by Synchro** [comment]
What? That you need this package is already documented in the readme and OAuth tutorials. It's impossible to give a list of exactly what packages are required because depending on what service you want to use, and what else you're doing in your particular app, it could expand to an unknown number of dependencies (possibly hundreds), and that could also change over time. The whole point of using composer is that you just don't have to care, because it deals with it all for you. If you'd like to provide a manual dependency resolution service that will expand to precisely the set of `include` lines you need, be my guest, but you'd be wasting your time.

**Comment by gmariani** [comment]
Nope, i take back what i said. I did eventually stumble upon a thread where you mentioned your examples. I had downloaded the Zip and didn't see them there and only saw the one example on the main page. I didn't navigate through the repository to find it. So I apologize there for not digging in further, I has assumed to find some mention on the main page is all.

But to address your comment, PHPMailer has 5 files, and has 3 requires for OAuth2. So I'm seeing a maximum of 8 requires here in order to use PHPMailer without composer. Am I missing something here? I get WHAT composer does, but just to use PHPMailer it seems like it's over-complicating things. You would know better than I, but I'm not seeing the 'need' for it.

**Comment by Synchro** [comment]
Um, no. It would require _a lot_ more than 8 `require` statements. To set up a new project all you need to do is:

    composer require phpmailer/phpmailer
    composer require league/oauth2-google

then

    require 'vendor/autoload.php';

in your script, and that is literally it. There is no more you need to do to start using all the relevant classes. You may not even need to require the autoloader because your framework probably already does it for you.

Those two composer packages install around **70** classes, and you don't know exactly how they depend on each other, what folders they live in – _but you don't need to_. It could take hours of manual trawling to figure it out - and it could be all different tomorrow when one of them updates, and for a slightly different dependency like `hayageek/oauth2-yahoo`, it could be an entirely different set of requires. 

Somehow you're suggesting that doing all that (and documenting it, and keeping it up to date) is simpler than using composer?

**Comment by gmariani** [comment]
You're assuming I'm using a framework.
Maybe you're coming from building large projects with hundreds of dependencies. But all the projects I've worked on, I've never had to require 70+ different libraries. I'll give that that may be a matter of taste, but the way 'modern' php developers (web developers in general) include libraries upon libraries upon libraries are causing a problem and then building a solution (composer) to fix their mess. It reminds me of the NPM apocalypse of 2016 where one library broke the builds of millions of programs. Personally, I prefer control over my dependencies, I can't blindly trust 3rd programmers that easily. So whenever possible, I try to just include what is necessary. For me, enabling PHPMailer 6 took about 6 lines of code, which is much simpler than installing, configuring and modifying my program to use Composer. Yes OAuth would be a pita the first time, but after that it's not a big deal. I also don't update the libraries every build, that's just asking for bugs to be introduced. But when I do need to update the libraries, it's a minor hassle at that point. Again. I get that it's a matter of taste. Just kind of getting fed up with other developers forcing their style just to use their library.

**Comment by Synchro** [comment]
I'm not assuming you're using a framework, but many are. It's not 70 different libraries, it's 70 different classes stemming from a dependency on just 2 top-level libraries (phpmailer and the gmail oauth package), and hence up to 70 different 'require' statements if you want to do it manually. Any non-trivial application will quickly descend into dependency disaster if you don't have a coherent way of managing the dependencies, which is what package managers do. As soon as you even contemplate registering an SPL autoloader for a single class, you're already in a situation where you're probably better off with a well-tested solution like composer (which doesn't necessarily imply using any external/3rd party packages at all).

Yes, the requires you need for PHPMailer alone do not amount to much - but as soon as your app needs more than a single library, it will explode. PHPMailer is not an app, it's a library that does two things, and it's entirely intended to be used with other libraries and frameworks with as little friction as possible, and for PHP, that means using composer.

The NPM problem was that they stupidly allowed dependent packages to be deleted, and was compounded by the fact that NPM is stuffed with a zillion tiny libraries because JS has so little baked in; PHP doesn't have that problem because so much is built in, and composer just does a better job of it anyway.

**Comment by zey33** [comment]
For use with Google mail, download the packages on the server then require these dependencies:

use PHPMailer\PHPMailer\OAuth;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;	

require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/PHPMailer-master/src/OAuthTokenProvider.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/PHPMailer-master/src/OAuth.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/PHPMailer-master/src/Exception.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/PHPMailer-master/src/PHPMailer.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/PHPMailer-master/src/SMTP.php');

use League\OAuth2\Client\Provider\Google;

require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Tool/GuardedPropertyTrait.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Tool/ArrayAccessorTrait.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Tool/QueryBuilderTrait.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Tool/ArrayAccessorTrait.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Tool/BearerAuthorizationTrait.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Tool/MacAuthorizationTrait.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Tool/ProviderRedirectTrait.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Tool/RequestFactory.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Tool/RequiredParameterTrait.php');

require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Grant/Exception/InvalidGrantException.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Grant/AbstractGrant.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Grant/AuthorizationCode.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Grant/ClientCredentials.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Grant/GrantFactory.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Grant/Password.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Grant/RefreshToken.php');

require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-client-master/src/ClientExceptionInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-client-master/src/NetworkExceptionInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-client-master/src/RequestExceptionInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-client-master/src/ClientInterface.php');

require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-message-master/src/UriInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-message-master/src/UploadedFileInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-message-master/src/StreamInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-message-master/src/MessageInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-message-master/src/ResponseInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-message-master/src/RequestInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-message-master/src/ServerRequestInterface.php');

require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-factory-master/src/UriFactoryInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-factory-master/src/UploadedFileFactoryInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-factory-master/src/StreamFactoryInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-factory-master/src/ServerRequestFactoryInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-factory-master/src/ResponseFactoryInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/http-factory-master/src/RequestFactoryInterface.php');

require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/psr7-master/src/Stream.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/psr7-master/src/Uri.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/psr7-master/src/Utils.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/psr7-master/src/Header.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/psr7-master/src/Message.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/psr7-master/src/MessageTrait.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/psr7-master/src/HttpFactory.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/psr7-master/src/Request.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/psr7-master/src/Response.php');

require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/promises-master/src/TaskQueueInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/promises-master/src/TaskQueue.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/promises-master/src/Utils.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/promises-master/src/PromisorInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/promises-master/src/PromiseInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/promises-master/src/Promise.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/promises-master/src/Is.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/promises-master/src/FulfilledPromise.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/promises-master/src/RejectedPromise.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/promises-master/src/RejectionException.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/promises-master/src/Create.php');

require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/PrepareBodyMiddleware.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/RequestOptions.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/RedirectMiddleware.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Middleware.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Handler/CurlFactoryInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Handler/CurlFactory.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Handler/CurlHandler.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Handler/EasyHandle.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Handler/HeaderProcessor.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Handler/MockHandler.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Handler/StreamHandler.php');	
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Handler/CurlMultiHandler.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Handler/Proxy.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Utils.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/HandlerStack.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/ClientTrait.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/ClientInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/guzzle-master/src/Client.php');

require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/OptionProvider/OptionProviderInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/OptionProvider/PostAuthOptionProvider.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/OptionProvider/HttpBasicAuthOptionProvider.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Provider/Exception/IdentityProviderException.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Token/AccessTokenInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Token/ResourceOwnerAccessTokenInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Token/AccessToken.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Provider/AbstractProvider.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Provider/GenericProvider.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Provider/ResourceOwnerInterface.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-client-master/src/Provider/GenericResourceOwner.php');

require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-google-main/src/Exception/HostedDomainException.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-google-main/src/Provider/Google.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/YOUR_PATH_TO/oauth2-google-main/src/Provider/GoogleUser.php');

**Comment by Synchro** [comment]
That is an excellent example of why using composer is a great idea!

**Comment by infinityhost** [comment]
have the same question , don't wont to use this composer "sh" word.

**Comment by Synchro** [comment]
Your refusal to understand what it's doing isn't my problem.
