### ISSUE TITLE
phpMailer slow / hanging

### ISSUE THREAD

**Issue by devsie** [PHPMailer/PHPMailer#647]
I've searched several sites, but not found any (recent) answers to this problem.  Unfortunately, any page of my site using phpMailer is taking around 10seconds to load.  The email sends, but the delay is too long.

I've used the SMTPDebug, but don't understand half of it.  Also, there's no timestamps (or few) to see where it hangs.  Please can someone advise where i can start looking to sort this out?

I have the debug code if it's of help.

My setup is:
```
require_once($_SERVER['DOCUMENT_ROOT']."/PHPMailer/PHPMailerAutoload.php");

$mail = new PHPMailer;

$mail->IsSMTP();					// set mailer to use SMTP

$mail->SMTPDebug = 4;

$mail->SMTPAuth = true;			// turn on SMTP authentication
$mail->Host = "mail.theserver.com";  // specify main and backup server

$mail->Username = "email@theserver.com";  // SMTP username

$mail->Password = "the_password"; // SMTP password
$mail->SMTPSecure = 'tls';
$mail->Port = 587;
```
Many thanks

**Comment by Synchro** [comment]
You're unlikely to find any recent answers because it hasn't changed since about 1982. SMTP is a slow, chatty protocol and it's unsuited to sending on an interactive basis, e.g. during web page processing. If you want it to return faster, hand it off to another process such as a local mail server, or queue it in a DB or memcache etc and send from a cron job.

**Comment by devsie** [comment]
Thanks for the reply.  So phpMailer is unsuitable for "sending on an interactive basis"?  I'll search for info on the options you mentioned.  I've been looking into an API with elastic mail.

(I hadn't noticed this problem when I used a (much) older version of phpMailer).
