### ISSUE TITLE
Deprecated $ReturnPath option can be necesary

### ISSUE THREAD

**Issue by AldoOmar** [PHPMailer/PHPMailer#657]
I think this is an issue that deserves some attention, as I found lot of people in the internet looking for an answer to this.

I noticed the $ReturnPath option is deprecated... But there is a reason to use an empty Return-Path header: I have automatic mail answers with phpMailer, when one of these messages reaches a mailbox that also has an automatic responder it starts a loop of emails what causes problems in the SMTP server.

When I used mail() function, the -F option was available to force an empty Return-Path header and stop the chain of mails. That is what is used to answer to an invalid email destination address from a catch-all inbox. As my server blocked the use of the mail() function for security, IsMail() is not an option.

I know that one can use the $Sender to set the Return-Path header to a different email than the From, what is ok, but, as it produces an error if this is not a valid mailbox, I would need an inbox for $Sender that is only a scrap holder.

Thanks and Regards.

**Comment by Synchro** [comment]
This isn't PHPMailer's problem as it has nothing to do with inbound email - you need to fix your autoresponder to detect loops. Sending out messages that look like bounces but are not is a bad idea too. I can't think of any legitimate reason to put an invalid address in `Sender` anyway - you can always set your mail server to blackhole it rather than having a real address.

>That is what is used to answer to an invalid email destination address from a catch-all inbox. 

Got an RFC reference for that? How can a catch-all reject some addresses? It's either a catch-all or it's not. Anything that's an actual bounce should have its return path set to `<>`, but an auto-response is not a bounce, it's a reply.

Officially, the way around this is that autoresponders are not supposed to respond to messages marked as `Precedence: bulk`, but unfortunately it doesn't stop a zillion naïve implementations from doing just that.

**Comment by AldoOmar** [comment]
Thanks for your answer.

I use this inbox to catch all reply to my emails, then I daily process the answers and use them to mark the real rejected mail addresses as failed in the database. When I detect an email that is not a rejection, i assume it was sent in error, and answer to it with an invalid destination message just for courtesy (yes, may be a reply that looks like a bounce).

I can stop reply's and just delete those mails (and that's what I probably will do), but I would prefer to inform the sender that it was not an inbox available to send messages.

No idea if there is an RFC that voids a Return-Path: <> header.

Regards.

**Comment by direktorn** [comment]
I know this is closed but rfc3834 states that an MTA MOST NOT generate an response to messages containing an NULL/Invalid return-path. 

This is just one way of ensuring that mail loops are not created and I don't see the benefint of PHPMailer removing that functionality but I understand that RFC's are just ... comments..

**Comment by Synchro** [comment]
Trying to fix undefined behaviour (i.e. autoresponders) by breaking something that's working exactly as it should seems like a bad idea. RFC5321 says:

> When the delivery SMTP server makes the "final delivery" of a
   message, it inserts a return-path line at the beginning of the mail
   data.  This use of return-path is required; mail systems MUST support
   it.

and also

> A message-originating SMTP system SHOULD NOT send a message that
   already contains a Return-path header field.

A null return path is defined in the same RFC as `<>`, which is reserved for bounces, so I assume you're talking about leaving it completely blank?

RFC3834 is not in any way suggesting that you should ever *send* messages that use that structure, just that it should be considered malformed and ignored on receipt. This is pretty much Postel's law: *"Be conservative in what you send, be liberal in what you accept"*.

Including a completely empty return path might stop loops, but it will also break normal bounce handling, which is a problem worse than mail loops, and will probably get you blocked from delivering to Yahoo, who are extremely picky about things like that. Autoresponders are extremely annoying, but their undefined and mostly random behaviour means that breaking other stuff isn't a good idea because it may not work anyway. It's a big can of worms that should stay closed! IME, most autoresponder loops are dealt with via heuristics, which are difficult to define, but don't break anything.

One comment in the original posting: a corresponding inbound mailbox does not need to exist for a sender address to be used as a return path, though it does have to be valid. I send millions of messages daily using this approach - all my return paths are VERP addresses that do not exist as mailboxes, but are valid addresses handled by a script.
