### ISSUE TITLE
Sign-in attempt prevented (G-Mail)

### ISSUE THREAD

**Issue by danielson317** [PHPMailer/PHPMailer#676]
I used phpmailer to send an e-mail and google sent me an e-mail with the text:

We strongly recommend that you use a secure app, like Gmail, to access your account. All apps made by Google meet these security standards. Using a less secure app, on the other hand, could leave your account vulnerable.

I found a work-around here: http://stackoverflow.com/questions/33630263/email-attempt-failed-when-signin-through-php-in-gmail

But I would much prefer if the app was just considered secure. Am I missing a setting in the app or is there really a security vulnerability?

**Comment by Synchro** [comment]
It's really not a vulnerability. OAuth2 is an authorisation protocol that is being widely (ab)used as an authentication protocol. Essentially instead of saying "I can prove who I am" it says "That site over there can prove who I am", and the means by which "that site" knows who you are is exactly the login mechanism that google describes as "less secure", so it's really no different

I suspect their painting of OAuth as a more secure approach is a means of getting more people to sign into sites using google (and similarly for other "social logins" such as Facebook and twitter), but it's actually (though they will swear otherwise) a means of getting more information about users on sites they would not otherwise have access to. For example, you visit a new site and sign up for it using a google login, and later on you start seeing ads relating to similar sites when you're in gmail...

You'll find that using OAuth as a developer is extremely unpleasant. Unfortunately there is no way around that.

PHPMailer has limited support for XOAUTH2 (currently only for gmail), but it is being improved substantially in the next major release. You can read more about it in [the wiki](https://github.com/PHPMailer/PHPMailer/wiki).

**Comment by danielson317** [comment]
Thanks for the explanation. I didn't realize google was forcing OAuth on everyone. I guess it's kind of like an intermediate ssl cert. Either way I now have no problem selecting the "allow less secure apps" setting.
