### ISSUE TITLE
PHPMailer

### ISSUE THREAD

**Issue by WM2016** [PHPMailer/PHPMailer#678]
I am trying to set up an email functionality on wamp server, l have configured everything as explained here but l am getting this error

> # Mailer Error: Message body empty

> Mailer Error: Extension missing: openssl

**Comment by Synchro** [comment]
I'll take a wild guess and say that your message body is empty and you're missing the openssl extension.

**Comment by WM2016** [comment]
Thank you Marcus, yes l had noticed that. It's now working correctly, added
openssl extension in php.ini file and changed the variable for message body.
l appreciate quick response.

**Comment by WM2016** [comment]
Hi Synchro
Can you please help me with the following. I want to insert a link into the body of the email. How can l concatenate the url +user email+confirmation key like below:
$mail->Body ='Thank for registering with Club LG breakfast and after school club, please click on the link to verify your email. 
 Link: http://localhost/afterschoolclubadminstration./activate.php?email='.urlencode($email).'&key=$confirmKey;';

This is what l have tried but it's not working
Thanks

**Comment by Synchro** [comment]
You really don't know what's wrong? This is very, very basic PHP, please [read the PHP manual](http://php.net/manual/en/language.types.string.php), it's very good!

Your problem is that variables are not interpolated in single-quoted strings, so use double quotes:

```php
$mail->Body ='Thank for registering with Club LG breakfast and after school club, please click on the link to verify your email. 
Link: http://localhost/afterschoolclubadminstration./activate.php?email='.urlencode($email)."&key=$confirmKey;";
```

When reporting a problem, it's **really important** to say precisely what the problem is, not just "it's not working". Open source developers usually do this for free, so make it easy for them to help you.
