### ISSUE TITLE
getLastReply never seems to return anything.

### ISSUE THREAD

**Issue by danielson317** [PHPMailer/PHPMailer#679]
I am using the example code from: /examples/smtp_check.php

Several times in the code is the statement:  `$smtp->getLastReply()`

However the function always seems to return an empty string. 

I instead started printing `$smtp->getError()['error']` which seems to do what I was expecting.

What does getLastReply do and what am I doing wrong that I'm not getting any good debug data from it?

**Comment by Synchro** [comment]
`getLastReply` should return whatever the most recent raw response from the server was - so if you just sent an `EHLO`, you might expect a `220` response string in there. It's not specifically for errors - I'd expect `getError()` to return nothing if there has not been an error. It may be that errors cause the last response to be cleared.

**Comment by danielson317** [comment]
I see. Thanks for the quick reply.

The example code only calls getLastReply when their is an error. if an error clears that value it may not be the right function to call in that example. Not sure it's a bug per say but I found the get error code much more helpful in that example.

**Comment by Synchro** [comment]
You're quite right - in that example it only ever looks at responses when there has been an error, so `getError` will always have something interesting in. `last_reply` is usually empty because most those errors occur before any response has been received, or because of non-protocol related issues where there is nothing to put in `last_reply`. Thanks for reporting.
