### ISSUE TITLE
addStringAttachment basename call issue with dates

### ISSUE THREAD

**Issue by albertoantunes** [PHPMailer/PHPMailer#685]
I am working on a functionality to send mail with an attached excel spreadsheet, in which the attachment filename must follow the rule: Report-M/Y where M stands for month abbreviation and Y for 4 digits year. 

The problem is that by using the addStringAttachment function this is not possible, as the attachment file name gets stripped with the basename function call, so the filename becomes only "2016.xlsx" instead of "Report-Apr/2016.xlsx".

I undesrtand this is a trivial issue and that simply replacing the slash with underscore or other separator would work, but the format specified by the client in this case should be with the slashes.

Would be nice to have an option to input the filename directly. I don't know if that would raise security concerns though.

**Comment by Synchro** [comment]
The problem with this is that `/` can't be used in filenames on most platforms because it's a directory separator. The docs for the basename method says:

>On Windows, both slash (/) and backslash (\) are used as directory separator character. In other environments, it is the forward slash (/).

This path handling approach applies to nearly all file-related functions in PHP, so if you do manage to make it work, I'd expect it to be very fragile and cause problems elsewhere.

That said, this is easy to work around - just make a subclass and provide a different implementation of `addStringAttachment` that doesn't do the basename call. This is normal practice - not every library can be everything to everyone!

**Comment by albertoantunes** [comment]
Fair enough! Will try to educate the client but in last case will use your suggestion. Thanks!

**Comment by SDKiller** [comment]
@albertoantunes 

Just try to 'Save as' file with such a filename in Excel in his presence ;)
