### ISSUE TITLE
RFC 5322 Issue

### ISSUE THREAD

**Issue by BlerkSlerk** [PHPMailer/PHPMailer#699]
Hi,

We've recently migrated some PHP websites from PHP 5.3.X on Windows 2008 Server to PHP 7.0.5 on Windows 2012 Server R2, overall it's working perfectly but we're experiencing issues with RFC 5322 compliance on emails generated through PHPMailer. The problematic examples are Wordpress sites (running the latest version) and to overcome the issue we've activated a plugin that changes the way emails are sent from PHPMailer to SMTP. Once we do this they work fine however, we'd like to understand the true cause of the problem and make you aware of a potential issue.

We have spent some considerable time researching online but can't find anything meaningful. Is there anything you can suggest that we can look at?

I have attached the headers from a couple of bounce backs we received that may give you some insight into the issues. Any feedback would be greatly appreciated.

[BAD EMAIL EXAMPLE 2.txt](https://github.com/PHPMailer/PHPMailer/files/244750/BAD.EMAIL.EXAMPLE.2.txt)
[BAD MAIL EXAMPLE.txt](https://github.com/PHPMailer/PHPMailer/files/244751/BAD.MAIL.EXAMPLE.txt)

**Comment by Synchro** [comment]
The obvious problem with those is that the line break format is inconsistent. Try setting `$mail->LE = "\r\n";`

Can you tell me what the plugin is you mention?

**Comment by BlerkSlerk** [comment]
Sure, the Wordpress plugin is "wp-mail-smtp", it works fine when we use this and switch it to SMTP instead of PHPMailer. OK, where in the Wordpress sites do we make the change you mention? These are standard installs that we haven't touched.

**Comment by Synchro** [comment]
Actually I don't think it's that - I spotted something else. The return-path header may not be valid. In your messages it's set to this:

    Return-Path: contactform@swimleeds.org.uk

That address should be wrapped in `<>`, and it may be that the script is setting a custom header for the return path which is a fairly major RFC5322 contravention - The sender should not set a return-path; the receiver looks at the SMTP envelope sender and turns it into a return-path header which is prepended to the message. So - it shouldn't be there at all, and it's in the wrong format. I'd suspect something in your contact form plugin because PHPMailer doesn't set a return path itself any more (old versions did).

**Comment by Synchro** [comment]
OK, I read [the code](https://plugins.svn.wordpress.org/wp-mail-smtp/tags/0.9.6/wp_mail_smtp.php) for that plugin, and it does the right thing - and it is using PHPMailer to send via SMTP. This suggests that whatever you're using when you're *not* using that plugin is doing something wrong.

**Comment by BlerkSlerk** [comment]
Thank you. We have isolated the issue to mail() which for some reason is inserting duplicate headers into emails before sending them! We've created a very simply test script (see attached - https://github.com/PHPMailer/PHPMailer/files/245090/sample-code.zip) and below are the headers that this generates. As you can see there are 2 x "From:" headers. What on earth could be causing this?

Received: from SEPTEMBER ([127.0.0.1]) by september.weare79.co with Microsoft SMTPSVC(8.5.9600.16384);
	 Mon, 2 May 2016 13:54:55 +0100
Date: Mon, 02 May 2016 13:54:55 +0100
Subject: SendMail Test
To: bds@weare79.co
X-PHP-Originating-Script: 0:form-respond.php
From: Behrooz <bds@weare79.co>
From: bds@weare79.co
Return-Path: bds@weare79.co
Message-ID: <SEPTEMBERAUfKRfcjcM00000036@september.weare79.co>
X-OriginalArrivalTime: 02 May 2016 12:54:55.0548 (UTC) FILETIME=[D36757C0:01D1A471]

Name: Behrooz
Message: testing...

**Comment by Synchro** [comment]
This is because the mail function sets some headers itself. Notice that there is a Subject header even though you're not creating one.

BTW you are forging the from address in your script, which is a good way of getting your messages bounced because of SPF failures. Put your own address in From and the submitter's address in Reply-to.

You're doing no input validation and your script is vulnerable to header injection attacks.

You're better off sticking with PHPMailer to avoid this kind of hassle, it's what it's for.
