### ISSUE TITLE
Unable to get gmail SMTP to work on 2 servers. 

### ISSUE THREAD

**Issue by EddieE1** [PHPMailer/PHPMailer#705]
Following up from a message I have sent here:

https://sourceforge.net/p/phpmailer/discussion/81619/thread/d973e4d8/?limit=25#39fc

I am still yet to make things work for me and still get no errors or messaging on a server (i get plenty on my localhost)... After reading the docs I was still unable to get it working by doing the following:

- Updated contact_mail.php to suit the gmail example
- Ensure gmail allows less secure apps, it works on my outlook for mac
- Temporary disabled firewall on my dedicated server
- Ensured wordpress sites on same server work using plugin 'Configure SMTP' 
- Tried on another server (shared one this time)

What I didn't try was the Composer class section as this went a bit over my head. The annoying thing is I get no error messages or info on the server to tell me what is wrong... 

my final test contact_mail 

```php
<?php

date_default_timezone_set('Etc/UTC');

require 'phpmailer/PHPMailerAutoload.php';

//Create a new PHPMailer instance
$mail = new PHPMailer;

//Tell PHPMailer to use SMTP
$mail->isSMTP();

//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 2;

//Ask for HTML-friendly debug output
$mail->Debugoutput = 'html';

//Set the hostname of the mail server
$mail->Host = 'smtp.gmail.com';
// use
// $mail->Host = gethostbyname('smtp.gmail.com');
// if your network does not support SMTP over IPv6

//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;

//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';

//Whether to use SMTP authentication
$mail->SMTPAuth = true;

//Username to use for SMTP authentication - use full email address for gmail
$mail->Username = "ben@test.com"; // SMTP account username

$mail->Password   = "********";        // SMTP account password

//Set who the message is to be sent from
$mail->setFrom('from@example.com', 'First Last');

//Set an alternative reply-to address
$mail->addReplyTo('replyto@example.com', 'First Last');

//Set who the message is to be sent to
$mail->addAddress('ben@test.com', 'Ben Edward');

//Set the subject line
$mail->Subject = 'PHPMailer GMail SMTP test';

//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
$mail->msgHTML(file_get_contents('contents.php'), dirname(__FILE__));

//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';

//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
````

**Comment by Synchro** [comment]
Because you have `$mail->SMTPDebug = 2;` set, it should be generating large amounts of debug output. If you're not seeing that it means you're either not actually running this script, or the output is somehow being sent somewhere else. Are you running this from a command line or via a web browser?

In case you're running into initial connection problems, e.g. if your ISP blocks outbound SMTP, try setting `SMTPDebug = 3`.

Composer is only concerned with how you get hold of PHPMailer in the first place, and how you load it into your app. You can use the provided autoloader instead (as you are) or load the classes manually, but if it's running at all, you don't need to worry about that. If you do much PHP coding at all, you really should get to grips with composer as it makes using external libraries much, much easier.
