### ISSUE TITLE
Can't connect to Yandex SMTP

### ISSUE THREAD

**Issue by Qored** [PHPMailer/PHPMailer#708]
Hi,

Im using Yandex for domain
and tried to connect to SMTP through "Events Manager" wordpress plugin but I get an error!

I wonder if this configuration is ok to get things work or there's missing tricks?
![capture12](https://cloud.githubusercontent.com/assets/19226624/15079659/25644986-13ba-11e6-8f62-f55b50f019ba.JPG)

Tried also to set SMTP to: ssl://smtp.yandex.com:465
but didn't work as well..

Any help would be much appreciated,

Best regards,
Hisham

**Comment by Synchro** [comment]
It does look like its missing encryption options on that page.

**Comment by Synchro** [comment]
You could try setting SMTP host to `tls://smtp.yandex.com:587`, and set mail sending port to 587 too.

**Comment by Qored** [comment]
unfortunately didn't work..

**Comment by Synchro** [comment]
I suggest you raise a bug with the plugin author.

**Comment by gdarcan** [comment]
I was also struggling about that. Below is verified, working settings. But also you need to login to Yandex and accept eula or something thru https://mail.yandex.com before trying these settings.
-------------
	$mail->Host = 'smtp.yandex.com';
	$mail->Port = 465;
	$mail->SMTPAuth = true;
	$mail->SMTPSecure = 'ssl';
	$mail->SMTPOptions = array (
		'ssl' => array(
		'verify_peer' => false,
		'verify_peer_name' => false,
		'allow_self_signed' => true)
	);

**Comment by Synchro** [comment]
Never disable certificate verification just because it makes it “work”. The only time it is a valid approach is in some very specific circumstances, such as when an internal server is using a self-signed very - this is not the case with Yandex, so figure out *why* verification is failing and fix it properly, such as by configuring openssl or updating CA certificates.
