### ISSUE TITLE
Fatal error: Uncaught exception 'phpmailerAppException' with message 'Error Sending Registrant Email: : SMTP Error: The following recipients failed: recipientA@recipient.co: sorry, your envelope recipient domain must exist

### ISSUE THREAD

**Issue by DBStamps** [PHPMailer/PHPMailer#763]
It is true that the email address is an invalid domain, but I don't understand why the error was not trapped instead of breaking my PHP. As you can see below under Sending code, I do have a catch for phpmailerAppException. Everything in PHPMailer works fine until it encounters an email with a bad domain. Using the Debug=2 - it does show "SMTP ERROR: RCPT TO command failed: 553 sorry, your envelope recipient domain must exist (#5.7.1)" PHPMailer Version: 5.2.16 Thank you.

Code Calling PHPMailer:
require_once ($_SERVER['DOCUMENT_ROOT'].'/php/PHPMailer/code/PHPMailerAutoload.php');

$results_messages = array();

$mail = new PHPMailer(true);
$mail->CharSet = 'utf-8';
ini_set('default_charset', 'UTF-8');
$mail->isHTML(true);

class phpmailerAppException extends phpmailerException {}
$mail->isSMTP();
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
My sending code:
try {
	$mail->send();
	$file_msg.= 'Registrant Email Successful' . "<br />";
}
catch (phpmailerException $e) {
	throw new phpmailerAppException('Error Sending Registrant Email: ' . $to. ': '.$e->getMessage());
}
catch (phpmailerAppException $e) {
	$file_msg.= '<br />Error Message:' . "<br />" . $e->errorMessage();
}

**Comment by Synchro** [comment]
I think you've structured your try/catch incorrectly. In order to be caught, the throw must be inside a try block, which it is not in your code. You don't need the second catch at all because a phpMailerAppException is already a phpMailerException by inheritance, so the first catch will trap it. You need to catch the most specific exception types first.

Also, the error is being generated at these ever end, not in your code.
