### ISSUE TITLE
Gmail got suspended after using PHPMailer

### ISSUE THREAD

**Issue by kenchanejfq** [PHPMailer/PHPMailer#768]
I have set google allow less secure access login,
and then I tried once to send an email to myself.

I can receive the email sent from PHPMailer in gmail, but then I receive another email from google say my google account is suspended due to violate their policy. Anyone experienced the same issue?

```
            $mail = new PHPMailer;
    $mail->isSMTP();
    $mail->Host = "smtp.gmail.com";
    $mail->SMTPAuth = true;
    $mail->Username = "xxxxx@gmail.com";
    $mail->Password = "password";
    $mail->SMTPSecure = "ssl";
    $mail->Port = 465;

    //$mail->CharSet = "big5";    

    $mail->setFrom("xxxxx@gmail.com", "xxxxx");
    $mail->AddAddress("xxxxx@gmail.com");
    $mail->isHTML(true);

    $mail->Subject = "OK";
    $mail->Body = "OK";



    if(!$mail->Send()) {
        echo "Mailer Error: " . $mail->ErrorInfo;
        error_log("Mailer Error: " . $mail->ErrorInfo);
    }
    else {
        echo "Message sent!";
        error_log("Message sent!");
    }   `
```

**Comment by Synchro** [comment]
I don't think this is anything to do with PHPMailer. I'd check gmail's support docs. I'd recommend you base your code on the gmail example supplied with PHPMailer.

**Comment by DimitarBogdanov** [comment]
_**Before I start, I am like an year later but this is to help future users..**_
@Synchro You're not correct. It is with PHPMailer, because an third party **bot** logs into a google acc. This is an violation, but
@kenchanejfq Create a new GMAIL account and FILL the **Your current email address** with an alt-email (not an gmail account if possible), send a mail from it (using phpmailer) and for the next 5 mins check the alt-acc. Google will email you on the **alt** that you have violated the rules, but you'll see an button/link to report the suspend. Google checks it and your gmail will be unblocked. If you got unsuspended you won't be suspended for that again 😄

**Comment by Synchro** [comment]
It's really not. You can use any email library to abuse things - plenty of spammers use PHPMailer - but that doesn't mean that it's doing anything wrong from a technical point of view. You could achieve exactly the same thing with Outlook. It's a policy violation, not a technical one.
