### ISSUE TITLE
SSL 14090086 error

### ISSUE THREAD

**Issue by biax** [PHPMailer/PHPMailer#794]
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1.
OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Troubleshooting says: The correct fix for this is to replace the invalid, misconfigured or self-signed certificate with a good one.

My nginx cert works perfectly fine. Is this the cert we're talking about? or is there something else? Is there a guide for setting this cert up? It isn't CLEAR what cert we're talking about here. If it's nginx cert, im wondering if my php-fpm chroot is responsible for this.

Please clarify

**Comment by Synchro** [comment]
Is PHPMailer connecting to nginx? No, it's connecting to mail server which has its own cert - which could be the same one that nginx uses. Check your mail server's cert as the troubleshooting guide tells you to.

**Comment by biax** [comment]
I don't have a mail server. I thought the purpose of PHPMailer is to use an external mail server? Am i wrong?

**Comment by Synchro** [comment]
No, that's right but external only means not in PHP, so it can be local. Either way, the server you are using has problems. The guide will show you how to find what is wrong with your server.

**Comment by biax** [comment]
I'm fairly convinced now this has to do with my php-fpm chroot setup and bind mounts. However anyway, can the guides be more specific? To begin with which "guide" are you referring to? Mind directly linking me?

**Comment by Synchro** [comment]
It's linked from the readme, from every error message, from the project front page, from the project wiki, from hundreds of questions on SO and [here](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting), and it's the first hit if you search for "phpmailer troubleshooting" on google. It's not *too* hard to find.

I doubt very much it's anything to do with your chroot setup. The problem is at the mail server end, so it's nothing to do with what you're doing. It's most likely to be a misconfigured server with a name mismatch, or by transparent redirection by your ISP's firewall. You could try posting your debug output so that we can see exactly what it says, but the tests in the guide will allow you to see exactly what's up.

**Comment by biax** [comment]
I don't know why you're so convinced the issue is at the mail server end... I'm using yandex

also check this
`root@agosto ~http/x/www/_www # cat test_chroot.php 
<?php
        header('Content-Type: text/plain');
        ini_set('display_errors',1);
        error_reporting(E_ALL);

        echo "----- DNS + TLS  -----\n";
        file_get_contents('https://www.x.com') && print("OK");

        echo "\n\n----- Timezone database -----\n";
        echo "Date:  ".date('r');
?>`

`
</html>
root@agosto ~http/x/www/_www # curl https://www.x.com/test_chroot.php
----- DNS + TLS  -----
<br />
<b>Warning</b>:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in <b>/_www/test_chroot.php</b> on line <b>7</b><br />
<br />
<b>Warning</b>:  file_get_contents(): Failed to enable crypto in <b>/_www/test_chroot.php</b> on line <b>7</b><br />
<br />
<b>Warning</b>:  file_get_contents(https://www.x.com): failed to open stream: operation failed in <b>/_www/test_chroot.php</b> on line <b>7</b><br />


----- Timezone database -----
Date:  Mon, 08 Aug 2016 00:42:15 +0800#    
`
I did a testing earlier without chroot and i didnt get that openssl error msg. Unfortunately I didnt save the output and i dont wanna change the settings right now.

I'm gonna look deeper into my chroot issue. Thanks

**Comment by Synchro** [comment]
The only thing I can think of that might be caused by chroot is if PHP can't access a certificate authority certificates file, usually called cacert.pem. You will see what it is currently set to in phpinfo() output. You could place a copy inside your chroot; use the one from your system or download one from curl's site.

**Comment by biax** [comment]
You're right. Fixed by adding ini_cafile in php.ini to a cacert.
Thanks for your time.
