### ISSUE TITLE
Email Address Validation  RFC5322 vs RFC6530

### ISSUE THREAD

**Issue by tesmond** [PHPMailer/PHPMailer#803]
Email addresses with accented characters e.g. josé@example.com are in use today, but the validation appears to be against RFC5322 causing these to be rejected. Are there any plans to provide RFC6530 validation?

I am currently overriding valiation with transliteration to try and avoid false positives, but I am unsure if this is the best approach.

**Comment by Synchro** [comment]
There is mention of SMTPUTF8 in #88. The problem is that many systems do not yet support SMTPUTF8 (and may never do so), so it means you have to also support everything in [RFC6857](https://tools.ietf.org/html/rfc6857) as a fallback, which adds quite a lot of complication - for example it means you can't validate an email address until you connect to a mail server, because until you do that you can't tell whether the server supports SMTPUTF8 or not.

You can very easily override PHPMailer's validator by injecting your own (no need to even subclass), but that's not by itself enough to work with SMTPUTF8. Esentially all the encoding systems need to be rewritten to take that possibility into account. It's not a small job...

**Comment by tesmond** [comment]
Well my current solution is something like the following:

```
if (parent::validateAddress($address)) return true;
$address = iconv('ISO-8859-1', 'ASCII//TRANSLIT', $address);
return parent::validateAddress($address);
```

I was just concerned about somehow generating false positives. Of course we capture failed email addresses and log bounces, but as I couldn't find anything about this I was wondering if any work was planned or already done in this. Thanks for the info.

**Comment by Synchro** [comment]
I can see this approach running into issues with IDN, which is already supported in PHPMailer. For example, `user@àé.com` does not need SMTPUTF8, but `üser@ae.com` does. You should probably only apply transliteration to the local part.

**Comment by UA2018** [comment]
The Universal Acceptance Steering Group (UASG), supported by the Internet Corporation for Assigned Names and Numbers (ICANN), is a community-led, industry-wide initiative working on creating awareness and identifying and resolving problems associated with the universal acceptance of domain names. The purpose of these efforts is to help ensure a consistent and positive experience for Internet users globally.

You may find the following information useful in developing systems, internet applications that accept IDNs, EAI and New gTLDs.

Universal Acceptance Quick Guide:
https://uasg.tech/wp-content/uploads/documents/UASG005-en-digital.pdf

Good Practice Recommendations:
https://uasg.tech/wp-content/uploads/documents/UASG007-en-digital.pdf

Subscribe to the General Universal Mailing List https://mm.icann.org/mailman/listinfo/ua-discuss

You will find case studies and tools to test EAI on https://uasg.tech/.
