### ISSUE TITLE
SMTP mailing is slow with PHPMailer on PHP 5.6 

### ISSUE THREAD

**Issue by blokeish** [PHPMailer/PHPMailer#806]
SMTP emails send with PHPMailer in PHP 5.5 is at least 3 timer faster than on PHP 5.6. Unfortunately we have migrated to PHP 5.6 and want to continue using that. What in PHP 5.6 could be making it slower? On looking at the debug log it seems the authentication part is what's likely taking more time on PHP 5.6. I have tried with and without TLS option and   
```
$mail->SMTPOptions = array (
        'ssl' => array(
            'verify_peer'  => false,
            'verify_peer_name'  => false,
            'allow_self_signed' => true));
```
But with no effect

**Comment by Synchro** [comment]
Not specifiying `SMTPSecure` isn't enough to disable TLS - PHPMailer will do opportunistic TLS by itself if the server offers it, so see what happens if you set `$mail->SMTPAutoTLS = false;` as well as `$mail->SMTPSecure = false;`. That will confirm if it's TLS that's taking the time.

Aside from that, consider that remote SMTP isn't really appropriate use during processing a page submission because it can be extremely slow - you need to handle it asynchronously by passing it off to another process or a queue if you want to retain control of response times.

**Comment by blokeish** [comment]
Thanks Synchro. That does speed it up a bit but not as fast as it did on PHP 5.5

**Comment by Synchro** [comment]
OK, well can you post output with `SMTPDebug = 2` so we can see timings.

**Comment by sagarindia** [comment]
Dear Synchro, I have same issue. http://83.110.153.143:9009/login?reset  this my site url this page use for reset password. 
try here to use a wrong email address example;  abcd@xys.com
it load within second because that time PHP mail function not call
but when you enter a correct email id   as    sagarindia2088@gmail.com    it take time to load i start debugging for you.  Please check and give me ans.  
my PHP version is 5.6.15

**Comment by FlashWebTech** [comment]
By using 
<?php
$mail->Host = gethostedbyname('smtp.google.com');
?>
it will be dimely Fast or use disable SMSTPAuth using  SMTPAuth = false;

**Comment by Synchro** [comment]
That's pointless - gmail won't let you send without authentication. If you want to send fast, read the PHPMailer docs & wiki.

**Comment by FlashWebTech** [comment]
I am using this On my new Project and is sending in Milliseconds I will send the configurations here.

**Comment by FlashWebTech** [comment]
`$mail = new PHPMailer;
     //Tell PHPMailer to use SMTP
     //$mail->isSMTP();
     //Enable SMTP debugging
      // 0 = off (for production use)
     // 1 = client messages
    // 2 = client and server messages
    $mail->SMTPDebug = 2;
    //Set the hostname of the mail server                          
     $mail->Host = gethostbyname('smtp.gmail.com');
	// use
    // $mail->Host = gethostbyname('smtp.gmail.com');
    // if your network does not support SMTP over IPv6
    //Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
   $mail->Port = 587;
   //Set the encryption system to use - ssl (deprecated) or tls
   $mail->SMTPSecure = 'tls';
   //Whether to use SMTP authentication
    $mail->SMTPAuth = false;
	//Always On Without Close after Sent
	$mail->SMTPKeepAlive = true;
   //Username to use for SMTP authentication - use full email address for gmail   
    $mail->Username = 'yourgmail@gmail.com';
	//Password to use for SMTP authentication
    $mail->Password = 'PasswordofGmail');
	//Set who the message is to be sent from
    $mail->setFrom('no-reply@glashwebtech.com, ucwords('FlashWebTech Inc'));
    //Set an alternative reply-to address
    $mail->addReplyTo($semail, $snamex);
	//Add Unsubscribe Link
	$mail->AddCustomHeader('List-Unsubscribe', "<mailto:unsubscribe@flashwebtech.com?subject=Unsubscribe>,<http://flashwebtech.com/unsubscribe?email=john@doe.com>");
    //Set who the message is to be sent to
    $mail->addAddress('john@doe.com', 'John Doe');
    //Set the subject line
   $mail->Subject = 'Hello Test';
   //Read an HTML message body from an external file, convert referenced images to embedded,
   //convert HTML into a basic plain-text alternative body
   $mail->msgHTML('<b>FlashWebTech Inc Test Mail!');
   //Replace the plain text body with one created manually
   $mail->AltBody = 'Mail Service (c) '. date('Y');
   //Attach an image file
   $mail->addAttachment(ROOT.'/Media/images/logo.png');
   //send the message, check for errors
   if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
    } else {
echo 'Mail Sent!';
}`

**Comment by FlashWebTech** [comment]
But is working for me anyway.

**Comment by Synchro** [comment]
Well it's bad advice, and wrong, so I've deleted it.
