### ISSUE TITLE
Incorrect methods naming

### ISSUE THREAD

**Issue by nikonm** [PHPMailer/PHPMailer#810]
Why all methods which names are started with is....(isQmail, isSendmail, isMail, isSMTP, isHTML)  are returned void. Based on their sense it must return boolean value, and not set value

**Comment by Synchro** [comment]
Well I know what you mean about the names, but their names date from long before the `is*` convention and it would be a BC break to change them. There's no point in making them return a boolean since it would be `true` in every case. They are not functions to get values, they are declaring that something is true (or not), so `isHTML` for example says "this instance is now using HTML"; it's not asking "is this instance using HTML?".
