### ISSUE TITLE
request: small address parser

### ISSUE THREAD

**Issue by Skrol29** [PHPMailer/PHPMailer#82]
Sometime, a normalized email address can be given using a display name.
For example:  "John Bidule&lt;bidule@mydomain.com&gt;"

Since PHPMailer cannot yet handle such addresses, it would be quite useful if it provides a parser.

$mail->parseAddr($addr)
and for example may return array('j.bidule@mydomain.com', 'John Bidule')

**Comment by Synchro** [comment]
This has finally been done!

I wrote a parser based around the `imap_rfc822_parse_adrlist` function, with a fallback to a simpler parser loosely based on @neokio's and some others I found. It will parse a whole list of addresses, not just one. You use it like this:

```php
$a = 'Joe User <joe@example.com>, Jill User <jill@example.net>';
foreach ($this->parseAddresses($a) as $address) {
    $mail->addAddress($address['address'], $address['name']);
}
```
I wrote it as a standalone parser so that it can be used fro CC, BCC, ReplyTo etc as well.

**Comment by ooxi** [comment]
:+1:

**Comment by Cyberchicken** [comment]
Hello Synchro, from what I read your are the author of `PHPMailer::parseAddresses()`

I find it a very useful utility function and I'd like to discuss the following improvements:
I think that lines 886, 902 and 911 (version '5.2.13') should read 
`self::validateAddress() `
instead of 
`$this->validateAddress() `
because we are calling a static method here.
`PHPMailer::parseAddresses()` itself should be declared static, so that one can call it without the need of passing around an instantiated PHPMailer.

Thank you for your code and for your attention.

**Comment by Synchro** [comment]
Hey @Cyberchicken, thanks for the request - it should probably have been in a new issue, but it doesn't matter. You're quite right that it should have been done that way so I'm changing it, however, since it's a minor BC break, I've put it into the 5.4 branch and it will be released when that gets finalised. For the record, the example for 5.4 should do this:

```php
$a = 'Joe User <joe@example.com>, Jill User <jill@example.net>';
foreach (PHPMailer::parseAddresses($a) as $address) {
    $mail->addAddress($address['address'], $address['name']);
}
```

**Comment by Cyberchicken** [comment]
Sorry for the hijacking if that's what you mean. I'll have to learn github's ways.
Why BC break? Calling dinamically a static method raises a warning?

**Comment by Synchro** [comment]
Calling a static method dynamically is allowed, but the reverse is not, see [this article](http://www.lornajane.net/posts/2010/declaring-static-methods-in-php), and that's what's happening in this change because the original method was not declared static.

**Comment by Cyberchicken** [comment]
Oh gosh, it's obvious! My concentration today is awful, sorry.
Anyway. To circumvent the alteration of the contract maybe you could write a wrapper with a similar name, like parseAddresses_static that would be called by the legacy parseAddresses (dynamic). A bit ugly but functional.
