### ISSUE TITLE
Server timeout when recipient's inbox is full

### ISSUE THREAD

**Issue by Elessar64** [PHPMailer/PHPMailer#839]
Hi,

I'm facing a problem I did not anticipated, and I really don't know how to deal with it.

I use a mysql database to store around 120 email addresses, along with names and an unique ID number. Once a month I use a script to extract the addresses, and send a message to each of them with a file attached to it.

It worked perfectly for the last 3 years, but a few weeks ago I got a Timeout error from the php server. I looked into it, and it seems that some email addresses are linked to full inboxes. So the SMTP server try to send it twice a day for 7 days, then decide to give up.

My problem is, my script don't skip and go to the next email to send when that arrive, and after the 600 sec timeout delay I get the error alert.

Is there a way to force the script to understand the email was sent to a full inbox and must stop trying and go the the next one ? I thought the SMTP maybe send an alert/error, but the script does not seems to do anything.

Here are some parts of the code : 
`for ($i = 0; $i < (count ($num)); $i++){$report = envoyer_mail($mail[$i], $num[$i], $nom[$i]);    
}`
And the sending part of envoyer_mail() function : 
`if(!($mail->Send())) {                                             
$error = $mail->ErrorInfo;
return $nom.' ('.$error.')';                                                    
        exit;   
    }`

**Comment by Synchro** [comment]
This just sounds like you need a local mail server to deal with your queuing and retries, and a bounce handler to deal with bounces.

**Comment by Elessar64** [comment]
Don't be mad at me for not understanding how all of this works :/

I had to google "MTA" to understand what you were talking about.

I thought my case was just another case of non-delivery, who could result in an smtp error, witch worked fine until now. For exemple if my script try to send an email to an adress that doesn't exist, the script will receive a non-delivery status and move on to the next email. I thought it was the same here, and maybe I didn't use the right function or something.

Thanks for your help, I'll try to understand how to deal with it with the informations you gave me.

(Sorry for my English, i'm not a native speaker but I try my best ;) )

**Comment by Synchro** [comment]
Sorry, an MTA is a name for a full mail server or Mail Transfer Agent. PHPMailer is only an MUA - a Mail User Agent - and so does not have support for queuing, retrying or bounce handling, though it will report delivery-time errors. The best way to use PHPMailer is to have a local or nearby mail server that you can deliver to via SMTP - this means messages will be submitted very quickly, leaving your PHP scripts to get on with other stuff, and the mail server deals with remote delivery, retrying etc.

In order to handle delivery failures after it's been handed to the mail server by PHPMailer, you need to set up a bounce handler that will accept the rejections from your mail server. Most significantly, this is asynchronous - bounces may happen immediately during initial delivery, or much later. It's not hard to configure your mail server to feed bounces into a PHP script, but actually processing them is deeply unpleasant.
