### ISSUE TITLE
Encrypted mail without an external mailserver

### ISSUE THREAD

**Issue by karacho** [PHPMailer/PHPMailer#860]
Hello,

this is likely not an issue but a question ;)
Is it possible to send an encrypted mail only via sendmail? (Without an external mailserver)
And if yes, how do i have to configure the server correctly...

Thank you and sorry if this is not the right place for my question...

**Comment by Synchro** [comment]
There are two main ways that email can involve encryption:

* At the transport level, so that an unencrypted message is transferred using TLS encryption, rendering it unreadable to outsiders.
* At the message level, where the message itself is encrypted prior to transmission.

You can of course combine the two and send an encrypted message over an encrypted transport, and that can help hide metadata that is not hidden by message encryption (for example who a message is to). Sendmail does not provide any support for encryption at the transport level, but that doesn't really matter because it will usually be submitting to a local mail server (thus no exposure), which may use transport encryption to send the message on to its destination.

For encrypting messages the main choices are [S/MIME](https://en.wikipedia.org/wiki/S/MIME) and [PGP](https://en.wikipedia.org/wiki/Pretty_Good_Privacy). Both are common standards that are supported by many systems, though PGP usually requires additional software. PHPMailer supports S/MIME for *signing* messages, but not for *encrypting* them (though there is an open ticket for that in #127). PHPMailer has no support for PGP, however there is a child class that may work for you discussed in #505.

With message-level encryption, you don't need to configure anything on the server, it's just a message that's sent like any other, but you can force your local mail server to refuse to send unless the connection is encrypted, as in [this question](http://serverfault.com/questions/120123/forcing-smtp-outgoing-mail-encryption-on-postfix/120145#120145).

HTH
