### ISSUE TITLE
Error:SMTP connect() failed

### ISSUE THREAD

**Issue by farhadarshad2000** [PHPMailer/PHPMailer#889]
Error:SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

I got no fix of that yet.
It was working fine on my server suddenly emails are not sending since last 4 days.

**Comment by Synchro** [comment]
So read the docs it links you to, do what it says.

**Comment by farhadarshad2000** [comment]
According to the URL I have to update the PHPMailer version. But How could I test the version of PHP mailer

**Comment by Synchro** [comment]
Look in the code. It will tell you what version you have. Also, it doesn't matter - just get the latest version and use it instead of whatever you have now. Then read all the other things it says.

**Comment by farhadarshad2000** [comment]
In which file of code?

**Comment by Synchro** [comment]
You could try reading what I said instead.

**Comment by farhadarshad2000** [comment]
secondly, How can I install the lastest version of it on Linux.

**Comment by farhadarshad2000** [comment]
would you please help me in that

**Comment by Synchro** [comment]
Seriously, you need to put in just a tiny bit of effort. Go here: https://github.com/PHPMailer/PHPMailer read what it says, then do it. There is also a download link that page.

**Comment by farhadarshad2000** [comment]
there is but you didn;t get my point. I mean in Linux we do write apt-get install application_
name
so what we will do for PHP mailer in this case.

**Comment by Synchro** [comment]
To start with you read the readme where it tells you how to load it. PHPMailer, like nearly every PHP package there is, is usually installed either manually, along with your own scripts, or using [composer](https://getcomposer.org), also covered in the readme. PHP packages are almost never supplied as .deb packages; there is nothing stopping you from creating one yourself, but I would not recommend it because composer does a much better job.

**Comment by farhadarshad2000** [comment]
It's resolved. I have just updated PHPMailer module.
