### ISSUE TITLE
Auto loader missing with 6.X

### ISSUE THREAD

**Issue by vincent-guesnard** [PHPMailer/PHPMailer#898]
Hello,

Please, recover an auto-loader. Some of us really can't use Composer which just not fit at all on our development guildlines. Since there is no "must have" dependency, i don't know where the problem is.

Best regards,

Vincent

**Comment by Synchro** [comment]
The autoloader never went away in 5.2, only in 6. Using composer is not really any different from using PHPMailer's autoloader - the only differences are that it's in the `vendor` folder and has a different name. The alternative is that you simply load the classes manually - typically this will only involve 2 or 3 files. PHPMailer does have multiple external dependencies (which themselves have other dependencies) if you use OAuth, and handling that within its own autoloader is pointless as it only duplicates what composer already makes a much better job of, which was the reason for getting rid of the duplicate functionality of the autoloader.

**Comment by vincent-guesnard** [comment]
I have not been accurate on my affirmation : "no 'must have' dependency". I agree with you if we use OAuth (that's not my case).

Dealing with dependencies and manage to keep softwares up to date in a multiple dependencies context is a true work. 

Composer allow everyone to put a huge potential amount of unnecessary dependencies and some project's managers forget to manage standalone version of their software. Some projects becoming useless one because of some dependencies make it incompatible with our softwares. That's why i'm afraid every time i see Composer becoming a prerequis inside projects.

If you manage to keep an internal autoloader, that force you to manualy manage dependencies, and that's a good things, because you keep in mind that a dependency is a potential problem for someone.

Well, in all case, i understand your point of view. I just hope this project will not become a alien in the futur because of Composer.

**Comment by Synchro** [comment]
I really don't see the problem. If you use composer to include PHPMailer, you'll just get PHPMailer, nothing else, so the overhead is really minimal. If you include a bunch of other packages with many sub-dependencies, you will get lots of other files - but that is entirely up to you and has nothing to do with PHPMailer. Composer itself does not imply some massive expansion in file count and complexity; it's really pretty simple. Managing large numbers of dependencies *without* composer makes unnecessary work for yourself and is asking for problems.

PHPMailer is just one tiny library, a leaf on the tree, it's not a framework that should be dictating large-scale autoloading strategy. It's likely to be just one of many packages in any given project, and it works fine with plain requires if you need it to. This shouldn't be alienating anyone. Coming up with a separate autoloading system that has potential conflicts with other autoloaders is reinventing the wheel, adds more code that needs to be maintained. If you want to bundle libraries with your app, just commit the vendor folder; that's all there is to it. Remember that the old autoloader was added before composer existed, and now it's not needed because composer does a much better job.

**Comment by Synchro** [comment]
One other note:

> Some projects becoming useless one because of some dependencies make it incompatible with our softwares

The fact that a package has a dependency on another package that you have problem with simply means you need to find a different implementation of the same functionality. This is not in any way composer's fault - if you used the same package outside composer, you would still have exactly the same problem.
