### ISSUE TITLE
Error using Outlook mail  PHPMailer

### ISSUE THREAD

**Issue by affaz2** [PHPMailer/PHPMailer#917]
Sending mail using outlook mail is giving error 'SMTP Error: Could not authenticate. '. What is wrong..Should i make any changes in settings of outlook account? This code is working well with gmail..
Please help me soon.

Code is below

require('phpmailer/class.phpmailer.php');
require('phpmailer/class.smtp.php');
$mail = new PHPMailer();
$emailBody = "helo";

$mail->IsSMTP();
$mail->SMTPDebug = 0;
$mail->SMTPAuth = TRUE;
$mail->SMTPSecure = "tsl";
$mail->Port = 587;
$mail->Username = MAIL_USERNAME;
$mail->Password = MAIL_PASSWORD;
$mail->Host = 'mail.live.com';
$mail->Mailer = 'smtp';

$mail->SetFrom(SENDER_EMAIL, SENDER_NAME);
$mail->AddReplyTo(SENDER_EMAIL, SENDER_NAME);
$mail->ReturnPath=SENDER_EMAIL;
$mail->AddAddress($user["email"]);
$mail->Subject = "Test";
$mail->MsgHTML($emailBody);
$mail->IsHTML(true);

if(!$mail->Send()) {
$error_message = 'Problem in Sending Password Recovery Email';
} else {
$success_message = 'Please check your email to reset password!';
}

**Comment by Synchro** [comment]
You have quite a few mistakes in here - base your code on the examples provided (you've used an old, obsolete one), don't set random things for no good reason, and read the docs. `SMTPSecure` should be `tls`, not `tsl`. There's no need to set `Mailer` yourself - `isSMTP()` does that. Similarly, `msgHTML` calls `isHTML` for you. If you're going to check for errors on send, examine the contents of `ErrorInfo` afterwards and it will tell you what the problem is. If you still have trouble, set `SMTPDebug = 2` and look at what it says.

**Comment by pranayteja2773** [comment]
I am using old php mailer. Sending mail using Outlook credentails given by IT team in organization. It is not giving any error but mails are not going. Will please tell what is the issue here?. It is because of PHP mailer old version or something else. 
Note: Using same credentials from Dotnet, emails are going.

**Comment by Synchro** [comment]
I can't tell. Set `SMTPDebug = 2` and look at the output.
