### ISSUE TITLE
Huge security issue according to 'patchman'

### ISSUE THREAD

**Issue by Ramsz** [PHPMailer/PHPMailer#925]
Not sure why but patchman has deemed this file harmfull and edited this file, do we need to do something? thanks!

**Comment by Synchro** [comment]
Links helpful. Generally, yes, you need to update to the latest PHPMailer.

**Comment by Ramsz** [comment]
Thanks for the quick reply.
More details here: https://www.wordfence.com/blog/2016/12/phpmailer-vulnerability/

I compared both versions;  '5.2.19' and '5.2.14' that WordPress uses. I could not tell if the security issue at hand was fixed in .19. Could you confirm this using the information given in the wordfence URL. Thank you.

**Comment by Zenexer** [comment]
There have been numerous developments since that blog post was written.  You should update to 5.2.20 as soon as possible.  I've been informed by the WordPress team that WordPress isn't directly vulnerable, probably [because of this](https://github.com/PHPMailer/PHPMailer/wiki/About-the-CVE-2016-10033-and-CVE-2016-10045-vulnerabilities#youre-safe-if).
