### ISSUE TITLE
[Question] PHPMailer Exploit

### ISSUE THREAD

**Issue by zinroc** [PHPMailer/PHPMailer#934]
Where can we follow progress on this issue/monitor for a fix?
https://threatpost.com/phpmailer-bug-leaves-millions-of-websites-open-to-attack/122775/ 

Also, this might not be the right place to ask but, are there any contact form plugins that don't use PHPMailer library for the meantime?

**Comment by Synchro** [comment]
On the home page and changelog of this project is the definitive place to start. Fixes have now been released for both vulns in PHPMailer, so no more needs to happen here on that subject, but you should monitor for updates for any projects that depend on it. Note that nearly all PHP email libraries are vulnerable to both the same attacks, so switching libraries isn't going to help (especially now that PHPMailer has a fix). Also be aware that just because you're running an older version doesn't mean you're necessarily vulnerable. See [the notes in the wiki](https://github.com/PHPMailer/PHPMailer/wiki/About-the-CVE-2016-10033-and-CVE-2016-10045-vulnerabilities#youre-safe-if).
