### ISSUE TITLE
Which versions are affected by CVE-2016-10033 security issue ?

### ISSUE THREAD

**Issue by lramarojaona** [PHPMailer/PHPMailer#941]
Hello,

I would like to know wich versions of PHPMailer must be updated?

I have a very old site that is still using PHPMailer 1.73 and I assume that upgrading PHPMailer to 5.2.21 will require rewriting the php script that is using it.

Thank you for your answer!

**Comment by Synchro** [comment]
That really is very old! All versions should be upgraded to be sure, but if you're stuck on that version, you can avoid the recent security issue by making sure you're not using it in an unsafe way - the main thing is to make sure you're not using a user-submitted address as a from address. It's also safe if you're sending with SMTP. That said, it's quite likely that you're vulnerable to other security issues that have been fixed in the many years since that release, so I do recommend you upgrade anyway.

**Comment by lramarojaona** [comment]
Ok, I'll check that.

Many thanks for your quick answer! :)
