### ISSUE TITLE
isShellSafe() prevents inclusion of VERP

### ISSUE THREAD

**Issue by BurninLeo** [PHPMailer/PHPMailer#944]
[VERP](https://en.wikipedia.org/wiki/Variable_envelope_return_path) is a common and wide-used method to properly handle bounces. It works by adding information to the sender.

PHPMailer supports that but only for SMTP (PHPMailer::$do_verp).

In earlier versions of PHPMailer it was possible to set the PHPMailer::$Sender manually, for example:

$mail->Sender = "mailer+VERP=info@example.com";

In more recent versions, the $Sender is filtered by PHPMailer::isShellSafe() - which explicitly disallows even the plus sign. Although this is a sensible measure regarding security issues, it also disallows the intended use of + to add VERP information.

I suggest to make the PHPMailer::$do_verp working for sendmail/mail(). Another possible solution would be to allow more strings, as a = or + alone will probably not allow to hack any shell or sendmail?!

**Comment by Synchro** [comment]
This is mentioned in [the 5.2.20 release notes](https://github.com/PHPMailer/PHPMailer/releases/tag/v5.2.20). Unfortunately both `=` and `+` have significant meaning in some shells, so they can't be considered safe (because we can't tell what shell is in use - this is what makes the whole of that vulnerability so much more serious well beyond PHPMailer. The workaround is simple though - switch to SMTP to localhost. This opens up quite a bit more flexibility, completely avoids the issue, and it's also faster. All that most sendmail binaries do is open a synchronous SMTP connection to localhost anyway, so you're losing overhead by talking SMTP directly. This is also what [the postfix docs recommend](http://www.postfix.org/TUNING_README.html#mailing_tips) for best performance.
