### ISSUE TITLE
Clicking link to SmartMessages.net results in Google Chrome SSL warning

### ISSUE THREAD

**Issue by UweKeim** [PHPMailer/PHPMailer#958]
Clicking on the [SmartMessages.net](http://smartmessages.net) link in the [Sponsorship section](https://github.com/PHPMailer/PHPMailer#sponsorship) results in my Google Chrome (version 57.0.2970.0) to display a SSL warning:

> NET::ERR_CERT_AUTHORITY_INVALID

Also, running an [SSL check through SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=smartmessages.net) results in (to me) strange results.

Maybe you could fix it or remove the link?

**Comment by Synchro** [comment]
I know about that. This is because of the pending [removal of Startcom's root cert](https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html) from some future browsers - you're running Canary, which is not yet released. Startcom have promised to have a solution for this before the end of January 2017 (prior to the scheduled release of affected versions of Chrome and Firefox), but if they don't, I will be replacing the certs using a different CA.

**Comment by UweKeim** [comment]
Thanks. 

(I'm _not_ running Canary channel, I'm running Dev channel)

**Comment by Synchro** [comment]
Either way, it's pre-release.
