### ISSUE TITLE
PHPmailer doesn't show images since Update!

### ISSUE THREAD

**Issue by mathishuettl** [PHPMailer/PHPMailer#974]
Before the Update I used $phpmailer->AddEmbeddedImage to add images to emails and it no longer works as it used to be. Now the Images doesn't appear in the E-Mail..

Below is my code:

```
global $phpmailer;

add_action("phpmailer_init", function(&$phpmailer) use ($file, $uid, $name) {
    $phpmailer->SMTPKeepAlive = true;
    $phpmailer->AddEmbeddedImage($file, $uid, $name);
});
```

Emails get send alright, but without images.

How can I fix this?

**Comment by Synchro** [comment]
Check your return values, check your paths.

**Comment by mathishuettl** [comment]
As I wrote it worked before the update so the paths are 100% correct and which return values you mean?

**Comment by Synchro** [comment]
Check again. Check the return value from `$phpmailer->AddEmbeddedImage($file, $uid, $name);`

**Comment by hturkoz** [comment]
Hi,
sorry yes this was another problem..  i have try with another "network" and no problem.
Sorry.

Close the issue.
Regards and still sorry

**Comment by bees4ever** [comment]
I even don't get images in my mail by adding just the html code with relative links to the image. I also  just changes the phpmailer library and nothing else. 
I now reseted my phpmailer to version 5.2.14 because of this. Sorry, I hope someone find the bug and the next release will include the fix or I found it myself. 

Or does anyone has an idea?

**Comment by Synchro** [comment]
@bees4ever please don't hijack threads. Relative paths to images will not work in email. You can use them in msgHTML, but a recent change is that you *must* provide a root directory when doing that.
