### ISSUE TITLE
Version 5.2.22: default AuthType = CRAM-MD5 instead of LOGIN

### ISSUE THREAD

**Issue by bees4ever** [PHPMailer/PHPMailer#978]
Hi PHPMailer - Team!

I just updated phpmailer to the stable release 5.2.22. I got an error because of smpt-login. After debuging I figured out that phpmailer set the default value to "CRAM-MD5" instead of "LOGIN".

However, if I have some time this evening I will look into the code lines to get it fixed. So if make a fork request you know why. 

Regards
Benny

**Comment by Synchro** [comment]
You'll find that while that is the default, it does not get used if the server does not offer it. It gets highest priority because it's the most secure of the common mechanisms, so should be tried first. If you have trouble with a particular mail server, you can simply override it. No changes are needed in the library.

If you find a bug in the selection mechanism, PRs welcome!
