### ISSUE TITLE
PHPMailer says the mail is sent successfully, but recipient never receives the mail

### ISSUE THREAD

**Issue by kwatts59** [PHPMailer/PHPMailer#997]
I have a problem sending mail with PHPMailer. There is no error and the recipient never receives the email. Below is an excerpt of the code:

```
<?php
require_once('class.phpmailer.php'); 
require_once('class.smtp.php');
/*
extraneous code was removed to avoid confusion
*/
$email_addr = "kwatts59@gmail.com";
$fname = "tf_enrichment.out";
echo "Sending email<br>";
$email = new PHPMailer();
# $email->From      = 'noreply@emory.edu';
$email->setFrom("noreply@emory.edu", "Emory.com");
$email->FromName  = 'TF Enrichment';
$email->Subject   = 'TF Enrichment';
$email->Body      = 'The following attachment are the results of your TF Enrichment query.';
$email->AddAddress( $email_addr );
$file_to_attach = '/var/www/html/tf_enrichment/';
$email->AddAttachment( $file_to_attach , $fname );
if(!$email->Send())
{   echo "Message could not be sent. <br>";
   echo "Mailer Error: " . $mail->ErrorInfo;
   echo "<br>"; }
else
{ echo "Message has been sent<br>"; }
?>

```
The output is as follows:

```
Sending email
Message has been sent
```
Any help would be greatly appreciated.

**Comment by Synchro** [comment]
You're using the default `isMail` transport, so it's submitting to your local mail server using PHP's `mail()` function, and so the message is passed to your local mail server successfully. What happens to it after that is out of PHPMailer's control, but you can usually find out by looking in your mail server's log, usually in `/var/log/mail.log`. This is covered in the troubleshooting guide.

Incidentally you've got this:

    $file_to_attach = '/var/www/html/tf_enrichment/';

You're passing that to `addAttachment()`; that won't work because it's a directory, not a file.
